// Code generated by protoc-gen-go. DO NOT EDIT.
// source: serial_port_service.proto

package firmware

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	empty "github.com/golang/protobuf/ptypes/empty"
	wrappers "github.com/golang/protobuf/ptypes/wrappers"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type SerialPortConfig struct {
	Name                 string   `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`
	Baud                 int64    `protobuf:"varint,2,opt,name=Baud,proto3" json:"Baud,omitempty"`
	ReadTimeout          int64    `protobuf:"varint,3,opt,name=ReadTimeout,proto3" json:"ReadTimeout,omitempty"`
	SizeParityStop       []byte   `protobuf:"bytes,4,opt,name=SizeParityStop,proto3" json:"SizeParityStop,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SerialPortConfig) Reset()         { *m = SerialPortConfig{} }
func (m *SerialPortConfig) String() string { return proto.CompactTextString(m) }
func (*SerialPortConfig) ProtoMessage()    {}
func (*SerialPortConfig) Descriptor() ([]byte, []int) {
	return fileDescriptor_1c93d18dee411c11, []int{0}
}

func (m *SerialPortConfig) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SerialPortConfig.Unmarshal(m, b)
}
func (m *SerialPortConfig) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SerialPortConfig.Marshal(b, m, deterministic)
}
func (m *SerialPortConfig) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SerialPortConfig.Merge(m, src)
}
func (m *SerialPortConfig) XXX_Size() int {
	return xxx_messageInfo_SerialPortConfig.Size(m)
}
func (m *SerialPortConfig) XXX_DiscardUnknown() {
	xxx_messageInfo_SerialPortConfig.DiscardUnknown(m)
}

var xxx_messageInfo_SerialPortConfig proto.InternalMessageInfo

func (m *SerialPortConfig) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *SerialPortConfig) GetBaud() int64 {
	if m != nil {
		return m.Baud
	}
	return 0
}

func (m *SerialPortConfig) GetReadTimeout() int64 {
	if m != nil {
		return m.ReadTimeout
	}
	return 0
}

func (m *SerialPortConfig) GetSizeParityStop() []byte {
	if m != nil {
		return m.SizeParityStop
	}
	return nil
}

func init() {
	proto.RegisterType((*SerialPortConfig)(nil), "tast.cros.firmware.SerialPortConfig")
}

func init() { proto.RegisterFile("serial_port_service.proto", fileDescriptor_1c93d18dee411c11) }

var fileDescriptor_1c93d18dee411c11 = []byte{
	// 340 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x52, 0x4d, 0x4b, 0xc3, 0x40,
	0x14, 0x34, 0x6d, 0x2a, 0xb8, 0x8a, 0xe8, 0x1e, 0x24, 0xa6, 0x22, 0xa1, 0x48, 0xc9, 0x69, 0x03,
	0xad, 0x08, 0xbd, 0xb6, 0x58, 0xe8, 0x45, 0x4b, 0xe2, 0x07, 0x78, 0x29, 0xdb, 0xf6, 0xb5, 0x5d,
	0x48, 0xb2, 0x61, 0xf7, 0xc5, 0x52, 0xcf, 0xfe, 0x4b, 0xff, 0x8c, 0x64, 0x63, 0x51, 0x5a, 0x2d,
	0x78, 0x7b, 0xbc, 0x79, 0x33, 0x3b, 0x33, 0x2c, 0x39, 0xd7, 0xa0, 0x04, 0x8f, 0x47, 0x99, 0x54,
	0x38, 0xd2, 0xa0, 0x5e, 0xc5, 0x04, 0x58, 0xa6, 0x24, 0x4a, 0x4a, 0x91, 0x6b, 0x64, 0x13, 0x25,
	0x35, 0x9b, 0x09, 0x95, 0x2c, 0xb9, 0x02, 0xb7, 0x3e, 0x97, 0x72, 0x1e, 0x43, 0x60, 0x2e, 0xc6,
	0xf9, 0x2c, 0x80, 0x24, 0xc3, 0x55, 0x49, 0x70, 0x2f, 0x37, 0xc1, 0xa5, 0xe2, 0x59, 0x06, 0x4a,
	0x97, 0x78, 0xe3, 0xdd, 0x22, 0x27, 0x91, 0x79, 0x6e, 0x28, 0x15, 0xf6, 0x64, 0x3a, 0x13, 0x73,
	0x4a, 0x89, 0x7d, 0xc7, 0x13, 0x70, 0x2c, 0xcf, 0xf2, 0x0f, 0x42, 0x33, 0x17, 0xbb, 0x2e, 0xcf,
	0xa7, 0x4e, 0xc5, 0xb3, 0xfc, 0x6a, 0x68, 0x66, 0xea, 0x91, 0xc3, 0x10, 0xf8, 0xf4, 0x41, 0x24,
	0x20, 0x73, 0x74, 0xaa, 0x06, 0xfa, 0xb9, 0xa2, 0x4d, 0x72, 0x1c, 0x89, 0x37, 0x18, 0x72, 0x25,
	0x70, 0x15, 0xa1, 0xcc, 0x1c, 0xdb, 0xb3, 0xfc, 0xa3, 0x70, 0x63, 0xdb, 0xfa, 0xa8, 0x90, 0xd3,
	0x6f, 0x1b, 0x51, 0x99, 0x99, 0xf6, 0x89, 0x7d, 0x9f, 0x41, 0x4a, 0xaf, 0xd8, 0x76, 0x6c, 0xb6,
	0xe9, 0xda, 0x3d, 0x63, 0x65, 0x56, 0xb6, 0xce, 0xca, 0x6e, 0x8b, 0x22, 0x1a, 0x7b, 0xb4, 0x47,
	0xec, 0xc2, 0x14, 0xbd, 0xd8, 0xba, 0x78, 0x1c, 0xa4, 0xd8, 0x6e, 0x3d, 0xf1, 0x38, 0x07, 0xb7,
	0xbe, 0x85, 0x76, 0x57, 0x08, 0xda, 0x80, 0x46, 0xa4, 0xf6, 0xac, 0x04, 0x02, 0xdd, 0x75, 0xf7,
	0x8b, 0xc8, 0x20, 0xc5, 0x9b, 0xeb, 0xb5, 0x48, 0x87, 0xd4, 0xfa, 0x71, 0xae, 0x17, 0xf4, 0x0f,
	0xb3, 0x3b, 0x42, 0x74, 0x48, 0xad, 0x17, 0x4b, 0x0d, 0xff, 0xa7, 0x76, 0xfd, 0x97, 0xe6, 0x64,
	0xa1, 0x64, 0x22, 0xf2, 0x44, 0xea, 0xa0, 0xe8, 0x32, 0xf8, 0xfa, 0x56, 0x3a, 0x28, 0x4a, 0x0d,
	0xd6, 0xa5, 0x8e, 0xf7, 0x0d, 0xb7, 0xfd, 0x19, 0x00, 0x00, 0xff, 0xff, 0x43, 0x82, 0xf2, 0x70,
	0x83, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// SerialPortServiceClient is the client API for SerialPortService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type SerialPortServiceClient interface {
	Open(ctx context.Context, in *SerialPortConfig, opts ...grpc.CallOption) (*empty.Empty, error)
	Read(ctx context.Context, in *wrappers.UInt32Value, opts ...grpc.CallOption) (*wrappers.BytesValue, error)
	Write(ctx context.Context, in *wrappers.BytesValue, opts ...grpc.CallOption) (*wrappers.Int64Value, error)
	Flush(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*empty.Empty, error)
	Close(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*empty.Empty, error)
}

type serialPortServiceClient struct {
	cc *grpc.ClientConn
}

func NewSerialPortServiceClient(cc *grpc.ClientConn) SerialPortServiceClient {
	return &serialPortServiceClient{cc}
}

func (c *serialPortServiceClient) Open(ctx context.Context, in *SerialPortConfig, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/tast.cros.firmware.SerialPortService/Open", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *serialPortServiceClient) Read(ctx context.Context, in *wrappers.UInt32Value, opts ...grpc.CallOption) (*wrappers.BytesValue, error) {
	out := new(wrappers.BytesValue)
	err := c.cc.Invoke(ctx, "/tast.cros.firmware.SerialPortService/Read", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *serialPortServiceClient) Write(ctx context.Context, in *wrappers.BytesValue, opts ...grpc.CallOption) (*wrappers.Int64Value, error) {
	out := new(wrappers.Int64Value)
	err := c.cc.Invoke(ctx, "/tast.cros.firmware.SerialPortService/Write", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *serialPortServiceClient) Flush(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/tast.cros.firmware.SerialPortService/Flush", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *serialPortServiceClient) Close(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/tast.cros.firmware.SerialPortService/Close", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SerialPortServiceServer is the server API for SerialPortService service.
type SerialPortServiceServer interface {
	Open(context.Context, *SerialPortConfig) (*empty.Empty, error)
	Read(context.Context, *wrappers.UInt32Value) (*wrappers.BytesValue, error)
	Write(context.Context, *wrappers.BytesValue) (*wrappers.Int64Value, error)
	Flush(context.Context, *empty.Empty) (*empty.Empty, error)
	Close(context.Context, *empty.Empty) (*empty.Empty, error)
}

// UnimplementedSerialPortServiceServer can be embedded to have forward compatible implementations.
type UnimplementedSerialPortServiceServer struct {
}

func (*UnimplementedSerialPortServiceServer) Open(ctx context.Context, req *SerialPortConfig) (*empty.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Open not implemented")
}
func (*UnimplementedSerialPortServiceServer) Read(ctx context.Context, req *wrappers.UInt32Value) (*wrappers.BytesValue, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Read not implemented")
}
func (*UnimplementedSerialPortServiceServer) Write(ctx context.Context, req *wrappers.BytesValue) (*wrappers.Int64Value, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Write not implemented")
}
func (*UnimplementedSerialPortServiceServer) Flush(ctx context.Context, req *empty.Empty) (*empty.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Flush not implemented")
}
func (*UnimplementedSerialPortServiceServer) Close(ctx context.Context, req *empty.Empty) (*empty.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Close not implemented")
}

func RegisterSerialPortServiceServer(s *grpc.Server, srv SerialPortServiceServer) {
	s.RegisterService(&_SerialPortService_serviceDesc, srv)
}

func _SerialPortService_Open_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SerialPortConfig)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SerialPortServiceServer).Open(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/tast.cros.firmware.SerialPortService/Open",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SerialPortServiceServer).Open(ctx, req.(*SerialPortConfig))
	}
	return interceptor(ctx, in, info, handler)
}

func _SerialPortService_Read_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(wrappers.UInt32Value)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SerialPortServiceServer).Read(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/tast.cros.firmware.SerialPortService/Read",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SerialPortServiceServer).Read(ctx, req.(*wrappers.UInt32Value))
	}
	return interceptor(ctx, in, info, handler)
}

func _SerialPortService_Write_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(wrappers.BytesValue)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SerialPortServiceServer).Write(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/tast.cros.firmware.SerialPortService/Write",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SerialPortServiceServer).Write(ctx, req.(*wrappers.BytesValue))
	}
	return interceptor(ctx, in, info, handler)
}

func _SerialPortService_Flush_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(empty.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SerialPortServiceServer).Flush(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/tast.cros.firmware.SerialPortService/Flush",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SerialPortServiceServer).Flush(ctx, req.(*empty.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _SerialPortService_Close_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(empty.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SerialPortServiceServer).Close(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/tast.cros.firmware.SerialPortService/Close",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SerialPortServiceServer).Close(ctx, req.(*empty.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

var _SerialPortService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "tast.cros.firmware.SerialPortService",
	HandlerType: (*SerialPortServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Open",
			Handler:    _SerialPortService_Open_Handler,
		},
		{
			MethodName: "Read",
			Handler:    _SerialPortService_Read_Handler,
		},
		{
			MethodName: "Write",
			Handler:    _SerialPortService_Write_Handler,
		},
		{
			MethodName: "Flush",
			Handler:    _SerialPortService_Flush_Handler,
		},
		{
			MethodName: "Close",
			Handler:    _SerialPortService_Close_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "serial_port_service.proto",
}
