// Copyright 2022 The ChromiumOS Authors
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

package graphics

// To update test parameters after modifying this file, run:
// TAST_GENERATE_UPDATE=1 ~/trunk/src/platform/tast/tools/go.sh test -count=1 chromiumos/tast/local/bundles/cros/graphics

import (
	"strings"
	"testing"

	"chromiumos/tast/common/genparams"
)

type paramData struct {
	Name       string   // The test name.
	Executable string   // The test executable name.
	Args       string   // The list of args for the executable.
	ExtraAttr  []string // The extra group attribute for when to run the test.
	Timeout    int      // The timeout for the test.
}

var oclCtsParams []paramData

func addTest(suite, args, additionalArgs string, timeout int, extraAttr []string) {
	argsAggregate := strings.Replace(args, " ", "_", -1)
	name := strings.ToLower(suite + "_" + argsAggregate)
	oclCtsParams = append(oclCtsParams,
		paramData{
			Name:       name,
			Executable: "test_" + suite,
			Args:       strings.Trim(strings.Join([]string{args, additionalArgs}, " "), " "),
			ExtraAttr:  extraAttr,
			Timeout:    timeout,
		})
}

func TestOpenclCtsParamsAreGenerated(t *testing.T) {
	addTest("allocations", "multiple 1 buffer_non_blocking", "", 1, nil)
	addTest("allocations", "multiple 1 buffer", "", 1, nil)
	addTest("allocations", "multiple 1 image2d_read_non_blocking", "", 1, nil)
	addTest("allocations", "multiple 1 image2d_read", "", 1, nil)
	addTest("allocations", "multiple 1 image2d_write_non_blocking", "", 1, nil)
	addTest("allocations", "multiple 1 image2d_write", "", 1, nil)
	addTest("allocations", "single 1 buffer_non_blocking", "", 1, nil)
	addTest("allocations", "single 1 buffer", "", 1, nil)
	addTest("allocations", "single 1 image2d_read_non_blocking", "", 1, nil)
	addTest("allocations", "single 1 image2d_read", "", 1, nil)
	addTest("allocations", "single 1 image2d_write_non_blocking", "", 1, nil)
	addTest("allocations", "single 1 image2d_write", "", 1, nil)
	addTest("api", "binary_create", "", 1, nil)
	addTest("api", "binary_get", "", 1, nil)
	addTest("api", "bool_type", "", 1, nil)
	addTest("api", "buffer_properties_queries", "", 1, nil)
	addTest("api", "clone_kernel", "", 1, nil)
	addTest("api", "consistency_2d_image_from_buffer", "", 1, nil)
	addTest("api", "consistency_3d_image_writes", "", 1, nil)
	addTest("api", "consistency_depth_images", "", 1, nil)
	addTest("api", "consistency_device_and_host_timer", "", 1, nil)
	addTest("api", "consistency_device_enqueue", "", 1, nil)
	addTest("api", "consistency_il_programs", "", 1, nil)
	addTest("api", "consistency_memory_model", "", 1, nil)
	addTest("api", "consistency_non_uniform_work_group", "", 1, nil)
	addTest("api", "consistency_pipes", "", 1, nil)
	addTest("api", "consistency_prog_ctor_dtor", "", 1, nil)
	addTest("api", "consistency_progvar", "", 1, nil)
	addTest("api", "consistency_read_write_images", "", 1, nil)
	addTest("api", "consistency_subgroups", "", 1, nil)
	addTest("api", "consistency_svm", "", 1, nil)
	addTest("api", "context_destructor_callback", "", 1, nil)
	addTest("api", "create_context_from_type", "", 1, nil)
	addTest("api", "create_kernels_in_program", "", 1, nil)
	addTest("api", "enqueue_task", "", 1, nil)
	addTest("api", "execute_kernel_local_sizes", "", 1, nil)
	addTest("api", "get_buffer_info", "", 1, nil)
	addTest("api", "get_command_queue_info_compatibility", "", 1, nil)
	addTest("api", "get_command_queue_info", "", 1, nil)
	addTest("api", "get_context_info", "", 1, nil)
	addTest("api", "get_device_info", "", 1, nil)
	addTest("api", "get_image1d_array_info", "", 1, nil)
	addTest("api", "get_image1d_info", "", 1, nil)
	addTest("api", "get_image2d_array_info", "", 1, nil)
	addTest("api", "get_image2d_info", "", 1, nil)
	addTest("api", "get_image3d_info", "", 1, nil)
	addTest("api", "get_kernel_arg_info", "", 1, nil)
	addTest("api", "get_kernel_info", "", 1, nil)
	addTest("api", "get_platform_ids", "", 1, nil)
	addTest("api", "get_platform_info", "", 1, nil)
	addTest("api", "get_program_info_kernel_names", "", 1, nil)
	addTest("api", "get_sampler_info_compatibility", "", 1, nil)
	addTest("api", "get_sampler_info", "", 1, nil)
	addTest("api", "image_properties_queries", "", 1, nil)
	addTest("api", "kernel_arg_changes", "", 1, nil)
	addTest("api", "kernel_arg_multi_setup_random", "", 10, nil)
	addTest("api", "kernel_global_constant", "", 1, nil)
	addTest("api", "kernel_private_memory_size", "", 1, nil)
	addTest("api", "kernel_required_group_size", "", 1, nil)
	addTest("api", "load_single_kernel", "", 1, nil)
	addTest("api", "load_two_kernels_in_one", "", 1, nil)
	addTest("api", "load_two_kernels_manually", "", 1, nil)
	addTest("api", "load_two_kernels", "", 1, nil)
	addTest("api", "mem_object_destructor_callback", "", 1, nil)
	addTest("api", "min_data_type_align_size_alignment", "", 1, nil)
	addTest("api", "min_image_formats", "", 1, nil)
	addTest("api", "min_max_address_bits", "", 1, nil)
	addTest("api", "min_max_compute_units", "", 1, nil)
	addTest("api", "min_max_constant_args", "", 1, nil)
	addTest("api", "min_max_constant_buffer_size", "", 1, nil)
	addTest("api", "min_max_device_version", "", 1, nil)
	addTest("api", "min_max_double_fp_config", "", 1, nil)
	addTest("api", "min_max_execution_capabilities", "", 1, nil)
	addTest("api", "min_max_image_2d_height", "", 1, nil)
	addTest("api", "min_max_image_2d_width", "", 1, nil)
	addTest("api", "min_max_image_3d_depth", "", 1, nil)
	addTest("api", "min_max_image_3d_height", "", 1, nil)
	addTest("api", "min_max_image_3d_width", "", 1, nil)
	addTest("api", "min_max_image_array_size", "", 1, nil)
	addTest("api", "min_max_image_buffer_size", "", 1, nil)
	addTest("api", "min_max_kernel_preferred_work_group_size_multiple", "", 1, nil)
	addTest("api", "min_max_language_version", "", 1, nil)
	addTest("api", "min_max_local_mem_size", "", 1, nil)
	addTest("api", "min_max_mem_alloc_size", "", 1, nil)
	addTest("api", "min_max_parameter_size", "", 1, nil)
	addTest("api", "min_max_queue_properties", "", 1, nil)
	addTest("api", "min_max_read_image_args", "", 1, nil)
	addTest("api", "min_max_samplers", "", 1, nil)
	addTest("api", "min_max_single_fp_config", "", 1, nil)
	addTest("api", "min_max_thread_dimensions", "", 1, nil)
	addTest("api", "min_max_work_group_size", "", 1, nil)
	addTest("api", "min_max_work_items_sizes", "", 1, nil)
	addTest("api", "min_max_write_image_args", "", 1, nil)
	addTest("api", "native_kernel", "", 1, nil)
	addTest("api", "null_buffer_arg", "", 1, nil)
	addTest("api", "pipe_properties_queries", "", 1, nil)
	addTest("api", "platform_extensions", "", 1, nil)
	addTest("api", "queue_flush_on_release", "", 1, nil)
	addTest("api", "queue_hint", "", 1, nil)
	addTest("api", "queue_properties", "", 1, nil)
	addTest("api", "queue_properties_queries", "", 1, nil)
	addTest("api", "release_during_execute", "", 1, nil)
	addTest("api", "release_kernel_order", "", 1, nil)
	addTest("api", "repeated_setup_cleanup", "", 10, nil)
	addTest("api", "retain_mem_object_multiple", "", 1, nil)
	addTest("api", "retain_mem_object_set_kernel_arg", "", 1, nil)
	addTest("api", "retain_mem_object_single", "", 1, nil)
	addTest("api", "retain_queue_multiple", "", 1, nil)
	addTest("api", "retain_queue_single", "", 1, nil)
	addTest("api", "set_kernel_arg_by_index", "", 1, nil)
	addTest("api", "set_kernel_arg_constant", "", 1, nil)
	addTest("api", "set_kernel_arg_struct_array", "", 1, nil)
	addTest("api", "sub_group_dispatch", "", 1, nil)
	addTest("api", "zero_sized_enqueue", "", 1, nil)
	addTest("atomics", "atomic_add_index_bin", "", 1, nil)
	addTest("atomics", "atomic_add_index", "", 1, nil)
	addTest("atomics", "atomic_add", "", 1, nil)
	addTest("atomics", "atomic_and", "", 1, nil)
	addTest("atomics", "atomic_cmpxchg", "", 1, nil)
	addTest("atomics", "atomic_dec", "", 1, nil)
	addTest("atomics", "atomic_inc", "", 1, nil)
	addTest("atomics", "atomic_max", "", 1, nil)
	addTest("atomics", "atomic_min", "", 1, nil)
	addTest("atomics", "atomic_or", "", 1, nil)
	addTest("atomics", "atomic_sub", "", 1, nil)
	addTest("atomics", "atomic_xchg", "", 1, nil)
	addTest("atomics", "atomic_xor", "", 1, nil)
	addTest("basic", "arraycopy", "", 1, nil)
	addTest("basic", "arrayimagecopy3d", "", 1, nil)
	addTest("basic", "arrayimagecopy", "", 1, nil)
	addTest("basic", "arrayreadwrite", "", 1, nil)
	addTest("basic", "astype", "", 10, nil)
	addTest("basic", "async_copy_global_to_local", "", 10, nil)
	addTest("basic", "async_copy_local_to_global", "", 10, nil)
	addTest("basic", "async_strided_copy_global_to_local", "", 10, nil)
	addTest("basic", "async_strided_copy_local_to_global", "", 10, nil)
	addTest("basic", "barrier", "", 1, nil)
	addTest("basic", "bufferreadwriterect", "", 1, nil)
	addTest("basic", "constant", "", 1, nil)
	addTest("basic", "constant_source", "", 1, nil)
	addTest("basic", "createkernelsinprogram", "", 1, nil)
	addTest("basic", "enqueued_local_size", "", 1, nil)
	addTest("basic", "enqueue_map_buffer", "", 1, nil)
	addTest("basic", "enqueue_map_image", "", 1, nil)
	addTest("basic", "explicit_s2v_char", "", 1, nil)
	addTest("basic", "explicit_s2v_double", "", 1, nil)
	addTest("basic", "explicit_s2v_float", "", 1, nil)
	addTest("basic", "explicit_s2v_int", "", 1, nil)
	addTest("basic", "explicit_s2v_long", "", 1, nil)
	addTest("basic", "explicit_s2v_short", "", 1, nil)
	addTest("basic", "explicit_s2v_uchar", "", 1, nil)
	addTest("basic", "explicit_s2v_uint", "", 1, nil)
	addTest("basic", "explicit_s2v_ulong", "", 1, nil)
	addTest("basic", "explicit_s2v_ushort", "", 1, nil)
	addTest("basic", "float2int", "", 1, nil)
	addTest("basic", "fpmath_float2", "", 1, nil)
	addTest("basic", "fpmath_float4", "", 1, nil)
	addTest("basic", "fpmath_float", "", 1, nil)
	addTest("basic", "get_global_offset", "", 1, nil)
	addTest("basic", "get_linear_ids", "", 1, nil)
	addTest("basic", "global_linear_id", "", 1, nil)
	addTest("basic", "global_work_offsets", "", 1, nil)
	addTest("basic", "hiloeo", "", 10, nil)
	addTest("basic", "host_numeric_constants", "", 1, nil)
	addTest("basic", "hostptr", "", 1, nil)
	addTest("basic", "if", "", 1, nil)
	addTest("basic", "imagearraycopy3d", "", 1, nil)
	addTest("basic", "imagearraycopy", "", 1, nil)
	addTest("basic", "imagecopy3d", "", 1, nil)
	addTest("basic", "imagecopy", "", 1, nil)
	addTest("basic", "imagedim_non_pow2", "", 10, nil)
	addTest("basic", "imagedim_pow2", "", 10, nil)
	addTest("basic", "image_multipass_float_coord", "", 1, nil)
	addTest("basic", "image_multipass_integer_coord", "", 1, nil)
	addTest("basic", "imagenpot", "", 1, nil)
	addTest("basic", "image_param", "", 1, nil)
	addTest("basic", "image_r8", "", 1, nil)
	addTest("basic", "imagerandomcopy", "", 1, nil)
	addTest("basic", "imagereadwrite3d", "", 1, nil)
	addTest("basic", "imagereadwrite", "", 1, nil)
	addTest("basic", "int2float", "", 1, nil)
	addTest("basic", "intmath_int2", "", 1, nil)
	addTest("basic", "intmath_int4", "", 1, nil)
	addTest("basic", "intmath_int", "", 1, nil)
	addTest("basic", "intmath_long2", "", 1, nil)
	addTest("basic", "intmath_long4", "", 1, nil)
	addTest("basic", "intmath_long", "", 1, nil)
	addTest("basic", "kernel_call_kernel_function", "", 1, nil)
	addTest("basic", "kernel_limit_constants", "", 1, nil)
	addTest("basic", "kernel_memory_alignment_constant", "", 1, nil)
	addTest("basic", "kernel_memory_alignment_global", "", 1, nil)
	addTest("basic", "kernel_memory_alignment_local", "", 1, nil)
	addTest("basic", "kernel_memory_alignment_private", "", 1, nil)
	addTest("basic", "kernel_numeric_constants", "", 1, nil)
	addTest("basic", "kernel_preprocessor_macros", "", 1, nil)
	addTest("basic", "local_arg_def", "", 1, nil)
	addTest("basic", "local_kernel_def", "", 1, nil)
	addTest("basic", "local_kernel_scope", "", 1, nil)
	addTest("basic", "local_linear_id", "", 1, nil)
	addTest("basic", "loop", "", 1, nil)
	addTest("basic", "mri_multiple", "", 1, nil)
	addTest("basic", "mri_one", "", 1, nil)
	addTest("basic", "parameter_types", "", 1, nil)
	addTest("basic", "pointer_cast", "", 1, nil)
	addTest("basic", "prefetch", "", 10, nil)
	addTest("basic", "progvar_func_scope", "", 1, nil)
	addTest("basic", "progvar_prog_scope_init", "", 1, nil)
	addTest("basic", "progvar_prog_scope_misc", "", 1, nil)
	addTest("basic", "progvar_prog_scope_uninit", "", 1, nil)
	addTest("basic", "readimage3d_fp32", "", 1, nil)
	addTest("basic", "readimage3d_int16", "", 1, nil)
	addTest("basic", "readimage3d", "", 1, nil)
	addTest("basic", "readimage_fp32", "", 1, nil)
	addTest("basic", "readimage_int16", "", 1, nil)
	addTest("basic", "readimage", "", 1, nil)
	addTest("basic", "rw_image_access_qualifier", "", 1, nil)
	addTest("basic", "simple_read_image_pitch", "", 1, nil)
	addTest("basic", "simple_write_image_pitch", "", 1, nil)
	addTest("basic", "sizeof", "", 10, nil)
	addTest("basic", "vector_creation", "", 10, nil)
	addTest("basic", "vector_swizzle", "", 5, nil)
	addTest("basic", "vec_type_hint", "", 10, nil)
	addTest("basic", "vload_constant", "", 10, nil)
	addTest("basic", "vload_global", "", 10, nil)
	addTest("basic", "vload_local", "", 10, nil)
	addTest("basic", "vload_private", "", 10, nil)
	addTest("basic", "vstore_global", "", 10, nil)
	addTest("basic", "vstore_local", "", 10, nil)
	addTest("basic", "vstore_private", "", 10, nil)
	addTest("basic", "wg_barrier", "", 1, nil)
	addTest("basic", "work_item_functions", "", 1, nil)
	addTest("basic", "writeimage_fp32", "", 1, nil)
	addTest("basic", "writeimage_int16", "", 1, nil)
	addTest("basic", "writeimage", "", 1, nil)
	addTest("bruteforce", "acosh", "-w -1", 1, nil)
	addTest("bruteforce", "acospi", "-w -1", 1, nil)
	addTest("bruteforce", "acos", "-w -1", 1, nil)
	addTest("bruteforce", "add", "-w -1", 1, nil)
	addTest("bruteforce", "asinh", "-w -1", 1, nil)
	addTest("bruteforce", "asinpi", "-w -1", 1, nil)
	addTest("bruteforce", "asin", "-w -1", 1, nil)
	addTest("bruteforce", "assignment", "-w -1", 1, nil)
	addTest("bruteforce", "atan2pi", "-w -1", 1, nil)
	addTest("bruteforce", "atan2", "-w -1", 1, nil)
	addTest("bruteforce", "atanh", "-w -1", 1, nil)
	addTest("bruteforce", "atanpi", "-w -1", 1, nil)
	addTest("bruteforce", "atan", "-w -1", 1, nil)
	addTest("bruteforce", "cbrt", "-w -1", 1, nil)
	addTest("bruteforce", "ceil", "-w -1", 1, nil)
	addTest("bruteforce", "copysign", "-w -1", 1, nil)
	addTest("bruteforce", "cosh", "-w -1", 1, nil)
	addTest("bruteforce", "cospi", "-w -1", 1, nil)
	addTest("bruteforce", "cos", "-w -1", 1, nil)
	addTest("bruteforce", "divide_cr", "-w -1", 1, nil)
	addTest("bruteforce", "divide", "-w -1", 1, nil)
	addTest("bruteforce", "exp10", "-w -1", 1, nil)
	addTest("bruteforce", "exp2", "-w -1", 1, nil)
	addTest("bruteforce", "expm1", "-w -1", 1, nil)
	addTest("bruteforce", "exp", "-w -1", 1, nil)
	addTest("bruteforce", "fabs", "-w -1", 1, nil)
	addTest("bruteforce", "fdim", "-w -1", 1, nil)
	addTest("bruteforce", "floor", "-w -1", 1, nil)
	addTest("bruteforce", "fma", "-w -1", 1, nil)
	addTest("bruteforce", "fmax", "-w -1", 1, nil)
	addTest("bruteforce", "fmin", "-w -1", 1, nil)
	addTest("bruteforce", "fmod", "-w -1", 1, nil)
	addTest("bruteforce", "fract", "-w -1", 1, nil)
	addTest("bruteforce", "frexp", "-w -1", 1, nil)
	addTest("bruteforce", "half_cos", "-w -1", 1, nil)
	addTest("bruteforce", "half_divide", "-w -1", 1, nil)
	addTest("bruteforce", "half_exp10", "-w -1", 1, nil)
	addTest("bruteforce", "half_exp2", "-w -1", 1, nil)
	addTest("bruteforce", "half_exp", "-w -1", 1, nil)
	addTest("bruteforce", "half_log10", "-w -1", 1, nil)
	addTest("bruteforce", "half_log2", "-w -1", 1, nil)
	addTest("bruteforce", "half_log", "-w -1", 1, nil)
	addTest("bruteforce", "half_powr", "-w -1", 1, nil)
	addTest("bruteforce", "half_recip", "-w -1", 1, nil)
	addTest("bruteforce", "half_rsqrt", "-w -1", 1, nil)
	addTest("bruteforce", "half_sin", "-w -1", 1, nil)
	addTest("bruteforce", "half_sqrt", "-w -1", 1, nil)
	addTest("bruteforce", "half_tan", "-w -1", 1, nil)
	addTest("bruteforce", "hypot", "-w -1", 1, nil)
	addTest("bruteforce", "ilogb", "-w -1", 1, nil)
	addTest("bruteforce", "isequal", "-w -1", 1, nil)
	addTest("bruteforce", "isfinite", "-w -1", 1, nil)
	addTest("bruteforce", "isgreaterequal", "-w -1", 1, nil)
	addTest("bruteforce", "isgreater", "-w -1", 1, nil)
	addTest("bruteforce", "isinf", "-w -1", 1, nil)
	addTest("bruteforce", "islessequal", "-w -1", 1, nil)
	addTest("bruteforce", "islessgreater", "-w -1", 1, nil)
	addTest("bruteforce", "isless", "-w -1", 1, nil)
	addTest("bruteforce", "isnan", "-w -1", 1, nil)
	addTest("bruteforce", "isnormal", "-w -1", 1, nil)
	addTest("bruteforce", "isnotequal", "-w -1", 1, nil)
	addTest("bruteforce", "isordered", "-w -1", 1, nil)
	addTest("bruteforce", "isunordered", "-w -1", 1, nil)
	addTest("bruteforce", "ldexp", "-w -1", 1, nil)
	addTest("bruteforce", "lgamma_r", "-w -1", 1, nil)
	addTest("bruteforce", "lgamma", "-w -1", 1, nil)
	addTest("bruteforce", "log10", "-w -1", 1, nil)
	addTest("bruteforce", "log1p", "-w -1", 1, nil)
	addTest("bruteforce", "log2", "-w -1", 1, nil)
	addTest("bruteforce", "logb", "-w -1", 1, nil)
	addTest("bruteforce", "log", "-w -1", 1, nil)
	addTest("bruteforce", "mad", "-w -1", 1, nil)
	addTest("bruteforce", "maxmag", "-w -1", 1, nil)
	addTest("bruteforce", "minmag", "-w -1", 1, nil)
	addTest("bruteforce", "modf", "-w -1", 1, nil)
	addTest("bruteforce", "multiply", "-w -1", 1, nil)
	addTest("bruteforce", "nan", "-w -1", 1, nil)
	addTest("bruteforce", "nextafter", "-w -1", 1, nil)
	addTest("bruteforce", "not", "-w -1", 1, nil)
	addTest("bruteforce", "pown", "-w -1", 1, nil)
	addTest("bruteforce", "powr", "-w -1", 1, nil)
	addTest("bruteforce", "pow", "-w -1", 1, nil)
	addTest("bruteforce", "remainder", "-w -1", 1, nil)
	addTest("bruteforce", "remquo", "-w -1", 1, nil)
	addTest("bruteforce", "rint", "-w -1", 1, nil)
	addTest("bruteforce", "rootn", "-w -1", 1, nil)
	addTest("bruteforce", "round", "-w -1", 1, nil)
	addTest("bruteforce", "rsqrt", "-w -1", 1, nil)
	addTest("bruteforce", "signbit", "-w -1", 1, nil)
	addTest("bruteforce", "sincos", "-w -1", 1, nil)
	addTest("bruteforce", "sinh", "-w -1", 1, nil)
	addTest("bruteforce", "sinpi", "-w -1", 1, nil)
	addTest("bruteforce", "sin", "-w -1", 1, nil)
	addTest("bruteforce", "sqrt_cr", "-w -1", 1, nil)
	addTest("bruteforce", "sqrt", "-w -1", 1, nil)
	addTest("bruteforce", "subtract", "-w -1", 1, nil)
	addTest("bruteforce", "tanh", "-w -1", 1, nil)
	addTest("bruteforce", "tanpi", "-w -1", 1, nil)
	addTest("bruteforce", "tan", "-w -1", 1, nil)
	addTest("bruteforce", "trunc", "-w -1", 1, nil)
	addTest("buffers", "array_info_size", "", 1, nil)
	addTest("buffers", "buffer_copy", "", 1, nil)
	addTest("buffers", "buffer_fill_char", "", 1, nil)
	addTest("buffers", "buffer_fill_float", "", 1, nil)
	addTest("buffers", "buffer_fill_int", "", 1, nil)
	addTest("buffers", "buffer_fill_long", "", 1, nil)
	addTest("buffers", "buffer_fill_short", "", 1, nil)
	addTest("buffers", "buffer_fill_struct", "", 1, nil)
	addTest("buffers", "buffer_fill_uchar", "", 1, nil)
	addTest("buffers", "buffer_fill_uint", "", 1, nil)
	addTest("buffers", "buffer_fill_ulong", "", 1, nil)
	addTest("buffers", "buffer_fill_ushort", "", 1, nil)
	addTest("buffers", "buffer_map_read_char", "", 1, nil)
	addTest("buffers", "buffer_map_read_float", "", 1, nil)
	addTest("buffers", "buffer_map_read_int", "", 1, nil)
	addTest("buffers", "buffer_map_read_long", "", 1, nil)
	addTest("buffers", "buffer_map_read_short", "", 1, nil)
	addTest("buffers", "buffer_map_read_struct", "", 1, nil)
	addTest("buffers", "buffer_map_read_uchar", "", 1, nil)
	addTest("buffers", "buffer_map_read_uint", "", 1, nil)
	addTest("buffers", "buffer_map_read_ulong", "", 1, nil)
	addTest("buffers", "buffer_map_read_ushort", "", 1, nil)
	addTest("buffers", "buffer_map_write_char", "", 1, nil)
	addTest("buffers", "buffer_map_write_float", "", 1, nil)
	addTest("buffers", "buffer_map_write_int", "", 1, nil)
	addTest("buffers", "buffer_map_write_long", "", 1, nil)
	addTest("buffers", "buffer_map_write_short", "", 1, nil)
	addTest("buffers", "buffer_map_write_struct", "", 1, nil)
	addTest("buffers", "buffer_map_write_uchar", "", 1, nil)
	addTest("buffers", "buffer_map_write_uint", "", 1, nil)
	addTest("buffers", "buffer_map_write_ulong", "", 1, nil)
	addTest("buffers", "buffer_map_write_ushort", "", 1, nil)
	addTest("buffers", "buffer_migrate", "", 1, nil)
	addTest("buffers", "buffer_partial_copy", "", 1, nil)
	addTest("buffers", "buffer_read_array_barrier_char", "", 1, nil)
	addTest("buffers", "buffer_read_array_barrier_float", "", 1, nil)
	addTest("buffers", "buffer_read_array_barrier_int", "", 1, nil)
	addTest("buffers", "buffer_read_array_barrier_long", "", 1, nil)
	addTest("buffers", "buffer_read_array_barrier_short", "", 1, nil)
	addTest("buffers", "buffer_read_array_barrier_uchar", "", 1, nil)
	addTest("buffers", "buffer_read_array_barrier_uint", "", 1, nil)
	addTest("buffers", "buffer_read_array_barrier_ulong", "", 1, nil)
	addTest("buffers", "buffer_read_array_barrier_ushort", "", 1, nil)
	addTest("buffers", "buffer_read_async_char", "", 1, nil)
	addTest("buffers", "buffer_read_async_float", "", 1, nil)
	addTest("buffers", "buffer_read_async_int", "", 1, nil)
	addTest("buffers", "buffer_read_async_long", "", 1, nil)
	addTest("buffers", "buffer_read_async_short", "", 1, nil)
	addTest("buffers", "buffer_read_async_uchar", "", 1, nil)
	addTest("buffers", "buffer_read_async_uint", "", 1, nil)
	addTest("buffers", "buffer_read_async_ulong", "", 1, nil)
	addTest("buffers", "buffer_read_async_ushort", "", 1, nil)
	addTest("buffers", "buffer_read_char", "", 1, nil)
	addTest("buffers", "buffer_read_float", "", 1, nil)
	addTest("buffers", "buffer_read_half", "", 1, nil)
	addTest("buffers", "buffer_read_int", "", 1, nil)
	addTest("buffers", "buffer_read_long", "", 1, nil)
	addTest("buffers", "buffer_read_random_size", "", 1, nil)
	addTest("buffers", "buffer_read_short", "", 1, nil)
	addTest("buffers", "buffer_read_struct", "", 1, nil)
	addTest("buffers", "buffer_read_uchar", "", 1, nil)
	addTest("buffers", "buffer_read_uint", "", 1, nil)
	addTest("buffers", "buffer_read_ulong", "", 1, nil)
	addTest("buffers", "buffer_read_ushort", "", 1, nil)
	addTest("buffers", "buffer_write_async_char", "", 10, nil)
	addTest("buffers", "buffer_write_async_float", "", 10, nil)
	addTest("buffers", "buffer_write_async_int", "", 10, nil)
	addTest("buffers", "buffer_write_async_long", "", 10, nil)
	addTest("buffers", "buffer_write_async_short", "", 10, nil)
	addTest("buffers", "buffer_write_async_uchar", "", 10, nil)
	addTest("buffers", "buffer_write_async_uint", "", 10, nil)
	addTest("buffers", "buffer_write_async_ulong", "", 10, nil)
	addTest("buffers", "buffer_write_async_ushort", "", 10, nil)
	addTest("buffers", "buffer_write_char", "", 1, nil)
	addTest("buffers", "buffer_write_float", "", 1, nil)
	addTest("buffers", "buffer_write_half", "", 1, nil)
	addTest("buffers", "buffer_write_int", "", 1, nil)
	addTest("buffers", "buffer_write_long", "", 1, nil)
	addTest("buffers", "buffer_write_short", "", 1, nil)
	addTest("buffers", "buffer_write_struct", "", 1, nil)
	addTest("buffers", "buffer_write_uchar", "", 1, nil)
	addTest("buffers", "buffer_write_uint", "", 1, nil)
	addTest("buffers", "buffer_write_ulong", "", 1, nil)
	addTest("buffers", "buffer_write_ushort", "", 1, nil)
	addTest("buffers", "image_migrate", "", 1, nil)
	addTest("buffers", "mem_alloc_ref_flags", "", 1, nil)
	addTest("buffers", "mem_copy_host_flags", "", 1, nil)
	addTest("buffers", "mem_read_only_flags", "", 1, nil)
	addTest("buffers", "mem_read_write_flags", "", 1, nil)
	addTest("buffers", "mem_write_only_flags", "", 1, nil)
	addTest("buffers", "sub_buffers_overlapping", "", 1, nil)
	addTest("buffers", "sub_buffers_read_write_dual_devices", "", 1, nil)
	addTest("buffers", "sub_buffers_read_write", "", 1, nil)
	addTest("cl_copy_images", "1Darray CL_FLOAT", "", 1, nil)
	addTest("cl_copy_images", "1Darray CL_HALF_FLOAT", "", 1, nil)
	addTest("cl_copy_images", "1Darray CL_SIGNED_INT16", "", 1, nil)
	addTest("cl_copy_images", "1Darray CL_SIGNED_INT32", "", 1, nil)
	addTest("cl_copy_images", "1Darray CL_SIGNED_INT8", "", 1, nil)
	addTest("cl_copy_images", "1Darray CL_SNORM_INT16", "", 1, nil)
	addTest("cl_copy_images", "1Darray CL_SNORM_INT8", "", 1, nil)
	addTest("cl_copy_images", "1Darray CL_UNORM_INT_101010", "", 1, nil)
	addTest("cl_copy_images", "1Darray CL_UNORM_INT16", "", 1, nil)
	addTest("cl_copy_images", "1Darray CL_UNORM_INT8", "", 1, nil)
	addTest("cl_copy_images", "1Darray CL_UNORM_SHORT_555", "", 1, nil)
	addTest("cl_copy_images", "1Darray CL_UNORM_SHORT_565", "", 1, nil)
	addTest("cl_copy_images", "1Darray CL_UNSIGNED_INT16", "", 1, nil)
	addTest("cl_copy_images", "1Darray CL_UNSIGNED_INT32", "", 1, nil)
	addTest("cl_copy_images", "1Darray CL_UNSIGNED_INT8", "", 1, nil)
	addTest("cl_copy_images", "1D CL_FLOAT", "", 1, nil)
	addTest("cl_copy_images", "1D CL_HALF_FLOAT", "", 1, nil)
	addTest("cl_copy_images", "1D CL_SIGNED_INT16", "", 1, nil)
	addTest("cl_copy_images", "1D CL_SIGNED_INT32", "", 1, nil)
	addTest("cl_copy_images", "1D CL_SIGNED_INT8", "", 1, nil)
	addTest("cl_copy_images", "1D CL_SNORM_INT16", "", 1, nil)
	addTest("cl_copy_images", "1D CL_SNORM_INT8", "", 1, nil)
	addTest("cl_copy_images", "1D CL_UNORM_INT_101010", "", 1, nil)
	addTest("cl_copy_images", "1D CL_UNORM_INT16", "", 1, nil)
	addTest("cl_copy_images", "1D CL_UNORM_INT8", "", 1, nil)
	addTest("cl_copy_images", "1D CL_UNORM_SHORT_555", "", 1, nil)
	addTest("cl_copy_images", "1D CL_UNORM_SHORT_565", "", 1, nil)
	addTest("cl_copy_images", "1D CL_UNSIGNED_INT16", "", 1, nil)
	addTest("cl_copy_images", "1D CL_UNSIGNED_INT32", "", 1, nil)
	addTest("cl_copy_images", "1D CL_UNSIGNED_INT8", "", 1, nil)
	addTest("cl_copy_images", "2Darray CL_FLOAT", "", 1, nil)
	addTest("cl_copy_images", "2Darray CL_HALF_FLOAT", "", 1, nil)
	addTest("cl_copy_images", "2Darray CL_SIGNED_INT16", "", 1, nil)
	addTest("cl_copy_images", "2Darray CL_SIGNED_INT32", "", 1, nil)
	addTest("cl_copy_images", "2Darray CL_SIGNED_INT8", "", 1, nil)
	addTest("cl_copy_images", "2Darray CL_SNORM_INT16", "", 1, nil)
	addTest("cl_copy_images", "2Darray CL_SNORM_INT8", "", 1, nil)
	addTest("cl_copy_images", "2Darray CL_UNORM_INT_101010", "", 1, nil)
	addTest("cl_copy_images", "2Darray CL_UNORM_INT16", "", 1, nil)
	addTest("cl_copy_images", "2Darray CL_UNORM_INT8", "", 1, nil)
	addTest("cl_copy_images", "2Darray CL_UNORM_SHORT_555", "", 1, nil)
	addTest("cl_copy_images", "2Darray CL_UNORM_SHORT_565", "", 1, nil)
	addTest("cl_copy_images", "2Darray CL_UNSIGNED_INT16", "", 1, nil)
	addTest("cl_copy_images", "2Darray CL_UNSIGNED_INT32", "", 1, nil)
	addTest("cl_copy_images", "2Darray CL_UNSIGNED_INT8", "", 1, nil)
	addTest("cl_copy_images", "2Darrayto2D CL_FLOAT", "", 1, nil)
	addTest("cl_copy_images", "2Darrayto2D CL_HALF_FLOAT", "", 1, nil)
	addTest("cl_copy_images", "2Darrayto2D CL_SIGNED_INT16", "", 1, nil)
	addTest("cl_copy_images", "2Darrayto2D CL_SIGNED_INT32", "", 1, nil)
	addTest("cl_copy_images", "2Darrayto2D CL_SIGNED_INT8", "", 1, nil)
	addTest("cl_copy_images", "2Darrayto2D CL_SNORM_INT16", "", 1, nil)
	addTest("cl_copy_images", "2Darrayto2D CL_SNORM_INT8", "", 1, nil)
	addTest("cl_copy_images", "2Darrayto2D CL_UNORM_INT_101010", "", 1, nil)
	addTest("cl_copy_images", "2Darrayto2D CL_UNORM_INT16", "", 1, nil)
	addTest("cl_copy_images", "2Darrayto2D CL_UNORM_INT8", "", 1, nil)
	addTest("cl_copy_images", "2Darrayto2D CL_UNORM_SHORT_555", "", 1, nil)
	addTest("cl_copy_images", "2Darrayto2D CL_UNORM_SHORT_565", "", 1, nil)
	addTest("cl_copy_images", "2Darrayto2D CL_UNSIGNED_INT16", "", 1, nil)
	addTest("cl_copy_images", "2Darrayto2D CL_UNSIGNED_INT32", "", 1, nil)
	addTest("cl_copy_images", "2Darrayto2D CL_UNSIGNED_INT8", "", 1, nil)
	addTest("cl_copy_images", "2Darrayto3D CL_FLOAT", "", 1, nil)
	addTest("cl_copy_images", "2Darrayto3D CL_HALF_FLOAT", "", 1, nil)
	addTest("cl_copy_images", "2Darrayto3D CL_SIGNED_INT16", "", 1, nil)
	addTest("cl_copy_images", "2Darrayto3D CL_SIGNED_INT32", "", 1, nil)
	addTest("cl_copy_images", "2Darrayto3D CL_SIGNED_INT8", "", 1, nil)
	addTest("cl_copy_images", "2Darrayto3D CL_SNORM_INT16", "", 1, nil)
	addTest("cl_copy_images", "2Darrayto3D CL_SNORM_INT8", "", 1, nil)
	addTest("cl_copy_images", "2Darrayto3D CL_UNORM_INT_101010", "", 1, nil)
	addTest("cl_copy_images", "2Darrayto3D CL_UNORM_INT16", "", 1, nil)
	addTest("cl_copy_images", "2Darrayto3D CL_UNORM_INT8", "", 1, nil)
	addTest("cl_copy_images", "2Darrayto3D CL_UNORM_SHORT_555", "", 1, nil)
	addTest("cl_copy_images", "2Darrayto3D CL_UNORM_SHORT_565", "", 1, nil)
	addTest("cl_copy_images", "2Darrayto3D CL_UNSIGNED_INT16", "", 1, nil)
	addTest("cl_copy_images", "2Darrayto3D CL_UNSIGNED_INT32", "", 1, nil)
	addTest("cl_copy_images", "2Darrayto3D CL_UNSIGNED_INT8", "", 1, nil)
	addTest("cl_copy_images", "2D CL_FLOAT", "", 1, nil)
	addTest("cl_copy_images", "2D CL_HALF_FLOAT", "", 1, nil)
	addTest("cl_copy_images", "2D CL_SIGNED_INT16", "", 1, nil)
	addTest("cl_copy_images", "2D CL_SIGNED_INT32", "", 1, nil)
	addTest("cl_copy_images", "2D CL_SIGNED_INT8", "", 1, nil)
	addTest("cl_copy_images", "2D CL_SNORM_INT16", "", 1, nil)
	addTest("cl_copy_images", "2D CL_SNORM_INT8", "", 1, nil)
	addTest("cl_copy_images", "2D CL_UNORM_INT_101010", "", 1, nil)
	addTest("cl_copy_images", "2D CL_UNORM_INT16", "", 1, nil)
	addTest("cl_copy_images", "2D CL_UNORM_INT8", "", 1, nil)
	addTest("cl_copy_images", "2D CL_UNORM_SHORT_555", "", 1, nil)
	addTest("cl_copy_images", "2D CL_UNORM_SHORT_565", "", 1, nil)
	addTest("cl_copy_images", "2D CL_UNSIGNED_INT16", "", 1, nil)
	addTest("cl_copy_images", "2D CL_UNSIGNED_INT32", "", 1, nil)
	addTest("cl_copy_images", "2D CL_UNSIGNED_INT8", "", 1, nil)
	addTest("cl_copy_images", "2Dto2Darray CL_FLOAT", "", 1, nil)
	addTest("cl_copy_images", "2Dto2Darray CL_HALF_FLOAT", "", 1, nil)
	addTest("cl_copy_images", "2Dto2Darray CL_SIGNED_INT16", "", 1, nil)
	addTest("cl_copy_images", "2Dto2Darray CL_SIGNED_INT32", "", 1, nil)
	addTest("cl_copy_images", "2Dto2Darray CL_SIGNED_INT8", "", 1, nil)
	addTest("cl_copy_images", "2Dto2Darray CL_SNORM_INT16", "", 1, nil)
	addTest("cl_copy_images", "2Dto2Darray CL_SNORM_INT8", "", 1, nil)
	addTest("cl_copy_images", "2Dto2Darray CL_UNORM_INT_101010", "", 1, nil)
	addTest("cl_copy_images", "2Dto2Darray CL_UNORM_INT16", "", 1, nil)
	addTest("cl_copy_images", "2Dto2Darray CL_UNORM_INT8", "", 1, nil)
	addTest("cl_copy_images", "2Dto2Darray CL_UNORM_SHORT_555", "", 1, nil)
	addTest("cl_copy_images", "2Dto2Darray CL_UNORM_SHORT_565", "", 1, nil)
	addTest("cl_copy_images", "2Dto2Darray CL_UNSIGNED_INT16", "", 1, nil)
	addTest("cl_copy_images", "2Dto2Darray CL_UNSIGNED_INT32", "", 1, nil)
	addTest("cl_copy_images", "2Dto2Darray CL_UNSIGNED_INT8", "", 1, nil)
	addTest("cl_copy_images", "2Dto3D CL_FLOAT", "", 1, nil)
	addTest("cl_copy_images", "2Dto3D CL_HALF_FLOAT", "", 1, nil)
	addTest("cl_copy_images", "2Dto3D CL_SIGNED_INT16", "", 1, nil)
	addTest("cl_copy_images", "2Dto3D CL_SIGNED_INT32", "", 1, nil)
	addTest("cl_copy_images", "2Dto3D CL_SIGNED_INT8", "", 1, nil)
	addTest("cl_copy_images", "2Dto3D CL_SNORM_INT16", "", 1, nil)
	addTest("cl_copy_images", "2Dto3D CL_SNORM_INT8", "", 1, nil)
	addTest("cl_copy_images", "2Dto3D CL_UNORM_INT_101010", "", 1, nil)
	addTest("cl_copy_images", "2Dto3D CL_UNORM_INT16", "", 1, nil)
	addTest("cl_copy_images", "2Dto3D CL_UNORM_INT8", "", 1, nil)
	addTest("cl_copy_images", "2Dto3D CL_UNORM_SHORT_555", "", 1, nil)
	addTest("cl_copy_images", "2Dto3D CL_UNORM_SHORT_565", "", 1, nil)
	addTest("cl_copy_images", "2Dto3D CL_UNSIGNED_INT16", "", 1, nil)
	addTest("cl_copy_images", "2Dto3D CL_UNSIGNED_INT32", "", 1, nil)
	addTest("cl_copy_images", "2Dto3D CL_UNSIGNED_INT8", "", 1, nil)
	addTest("cl_copy_images", "3D CL_FLOAT", "", 1, nil)
	addTest("cl_copy_images", "3D CL_HALF_FLOAT", "", 1, nil)
	addTest("cl_copy_images", "3D CL_SIGNED_INT16", "", 1, nil)
	addTest("cl_copy_images", "3D CL_SIGNED_INT32", "", 1, nil)
	addTest("cl_copy_images", "3D CL_SIGNED_INT8", "", 1, nil)
	addTest("cl_copy_images", "3D CL_SNORM_INT16", "", 1, nil)
	addTest("cl_copy_images", "3D CL_SNORM_INT8", "", 1, nil)
	addTest("cl_copy_images", "3D CL_UNORM_INT_101010", "", 1, nil)
	addTest("cl_copy_images", "3D CL_UNORM_INT16", "", 1, nil)
	addTest("cl_copy_images", "3D CL_UNORM_INT8", "", 1, nil)
	addTest("cl_copy_images", "3D CL_UNORM_SHORT_555", "", 1, nil)
	addTest("cl_copy_images", "3D CL_UNORM_SHORT_565", "", 1, nil)
	addTest("cl_copy_images", "3D CL_UNSIGNED_INT16", "", 1, nil)
	addTest("cl_copy_images", "3D CL_UNSIGNED_INT32", "", 1, nil)
	addTest("cl_copy_images", "3D CL_UNSIGNED_INT8", "", 1, nil)
	addTest("cl_copy_images", "3Dto2Darray CL_FLOAT", "", 1, nil)
	addTest("cl_copy_images", "3Dto2Darray CL_HALF_FLOAT", "", 1, nil)
	addTest("cl_copy_images", "3Dto2Darray CL_SIGNED_INT16", "", 1, nil)
	addTest("cl_copy_images", "3Dto2Darray CL_SIGNED_INT32", "", 1, nil)
	addTest("cl_copy_images", "3Dto2Darray CL_SIGNED_INT8", "", 1, nil)
	addTest("cl_copy_images", "3Dto2Darray CL_SNORM_INT16", "", 1, nil)
	addTest("cl_copy_images", "3Dto2Darray CL_SNORM_INT8", "", 1, nil)
	addTest("cl_copy_images", "3Dto2Darray CL_UNORM_INT_101010", "", 1, nil)
	addTest("cl_copy_images", "3Dto2Darray CL_UNORM_INT16", "", 1, nil)
	addTest("cl_copy_images", "3Dto2Darray CL_UNORM_INT8", "", 1, nil)
	addTest("cl_copy_images", "3Dto2Darray CL_UNORM_SHORT_555", "", 1, nil)
	addTest("cl_copy_images", "3Dto2Darray CL_UNORM_SHORT_565", "", 1, nil)
	addTest("cl_copy_images", "3Dto2Darray CL_UNSIGNED_INT16", "", 1, nil)
	addTest("cl_copy_images", "3Dto2Darray CL_UNSIGNED_INT32", "", 1, nil)
	addTest("cl_copy_images", "3Dto2Darray CL_UNSIGNED_INT8", "", 1, nil)
	addTest("cl_copy_images", "3Dto2D CL_FLOAT", "", 1, nil)
	addTest("cl_copy_images", "3Dto2D CL_HALF_FLOAT", "", 1, nil)
	addTest("cl_copy_images", "3Dto2D CL_SIGNED_INT16", "", 1, nil)
	addTest("cl_copy_images", "3Dto2D CL_SIGNED_INT32", "", 1, nil)
	addTest("cl_copy_images", "3Dto2D CL_SIGNED_INT8", "", 1, nil)
	addTest("cl_copy_images", "3Dto2D CL_SNORM_INT16", "", 1, nil)
	addTest("cl_copy_images", "3Dto2D CL_SNORM_INT8", "", 1, nil)
	addTest("cl_copy_images", "3Dto2D CL_UNORM_INT_101010", "", 1, nil)
	addTest("cl_copy_images", "3Dto2D CL_UNORM_INT16", "", 1, nil)
	addTest("cl_copy_images", "3Dto2D CL_UNORM_INT8", "", 1, nil)
	addTest("cl_copy_images", "3Dto2D CL_UNORM_SHORT_555", "", 1, nil)
	addTest("cl_copy_images", "3Dto2D CL_UNORM_SHORT_565", "", 1, nil)
	addTest("cl_copy_images", "3Dto2D CL_UNSIGNED_INT16", "", 1, nil)
	addTest("cl_copy_images", "3Dto2D CL_UNSIGNED_INT32", "", 1, nil)
	addTest("cl_copy_images", "3Dto2D CL_UNSIGNED_INT8", "", 1, nil)
	addTest("cl_fill_images", "1Darray CL_FLOAT", "", 1, nil)
	addTest("cl_fill_images", "1Darray CL_HALF_FLOAT", "", 1, nil)
	addTest("cl_fill_images", "1Darray CL_SIGNED_INT16", "", 1, nil)
	addTest("cl_fill_images", "1Darray CL_SIGNED_INT32", "", 1, nil)
	addTest("cl_fill_images", "1Darray CL_SIGNED_INT8", "", 1, nil)
	addTest("cl_fill_images", "1Darray CL_SNORM_INT16", "", 1, nil)
	addTest("cl_fill_images", "1Darray CL_SNORM_INT8", "", 1, nil)
	addTest("cl_fill_images", "1Darray CL_UNORM_INT_101010", "", 1, nil)
	addTest("cl_fill_images", "1Darray CL_UNORM_INT16", "", 1, nil)
	addTest("cl_fill_images", "1Darray CL_UNORM_INT8", "", 1, nil)
	addTest("cl_fill_images", "1Darray CL_UNORM_SHORT_555", "", 1, nil)
	addTest("cl_fill_images", "1Darray CL_UNORM_SHORT_565", "", 1, nil)
	addTest("cl_fill_images", "1Darray CL_UNSIGNED_INT16", "", 1, nil)
	addTest("cl_fill_images", "1Darray CL_UNSIGNED_INT32", "", 1, nil)
	addTest("cl_fill_images", "1Darray CL_UNSIGNED_INT8", "", 1, nil)
	addTest("cl_fill_images", "1D CL_FLOAT", "", 1, nil)
	addTest("cl_fill_images", "1D CL_HALF_FLOAT", "", 1, nil)
	addTest("cl_fill_images", "1D CL_SIGNED_INT16", "", 1, nil)
	addTest("cl_fill_images", "1D CL_SIGNED_INT32", "", 1, nil)
	addTest("cl_fill_images", "1D CL_SIGNED_INT8", "", 1, nil)
	addTest("cl_fill_images", "1D CL_SNORM_INT16", "", 1, nil)
	addTest("cl_fill_images", "1D CL_SNORM_INT8", "", 1, nil)
	addTest("cl_fill_images", "1D CL_UNORM_INT_101010", "", 1, nil)
	addTest("cl_fill_images", "1D CL_UNORM_INT16", "", 1, nil)
	addTest("cl_fill_images", "1D CL_UNORM_INT8", "", 1, nil)
	addTest("cl_fill_images", "1D CL_UNORM_SHORT_555", "", 1, nil)
	addTest("cl_fill_images", "1D CL_UNORM_SHORT_565", "", 1, nil)
	addTest("cl_fill_images", "1D CL_UNSIGNED_INT16", "", 1, nil)
	addTest("cl_fill_images", "1D CL_UNSIGNED_INT32", "", 1, nil)
	addTest("cl_fill_images", "1D CL_UNSIGNED_INT8", "", 1, nil)
	addTest("cl_fill_images", "2Darray CL_FLOAT", "", 1, nil)
	addTest("cl_fill_images", "2Darray CL_HALF_FLOAT", "", 1, nil)
	addTest("cl_fill_images", "2Darray CL_SIGNED_INT16", "", 1, nil)
	addTest("cl_fill_images", "2Darray CL_SIGNED_INT32", "", 1, nil)
	addTest("cl_fill_images", "2Darray CL_SIGNED_INT8", "", 1, nil)
	addTest("cl_fill_images", "2Darray CL_SNORM_INT16", "", 1, nil)
	addTest("cl_fill_images", "2Darray CL_SNORM_INT8", "", 1, nil)
	addTest("cl_fill_images", "2Darray CL_UNORM_INT_101010", "", 1, nil)
	addTest("cl_fill_images", "2Darray CL_UNORM_INT16", "", 1, nil)
	addTest("cl_fill_images", "2Darray CL_UNORM_INT8", "", 1, nil)
	addTest("cl_fill_images", "2Darray CL_UNORM_SHORT_555", "", 1, nil)
	addTest("cl_fill_images", "2Darray CL_UNORM_SHORT_565", "", 1, nil)
	addTest("cl_fill_images", "2Darray CL_UNSIGNED_INT16", "", 1, nil)
	addTest("cl_fill_images", "2Darray CL_UNSIGNED_INT32", "", 1, nil)
	addTest("cl_fill_images", "2Darray CL_UNSIGNED_INT8", "", 1, nil)
	addTest("cl_fill_images", "2D CL_FLOAT", "", 1, nil)
	addTest("cl_fill_images", "2D CL_HALF_FLOAT", "", 1, nil)
	addTest("cl_fill_images", "2D CL_SIGNED_INT16", "", 1, nil)
	addTest("cl_fill_images", "2D CL_SIGNED_INT32", "", 1, nil)
	addTest("cl_fill_images", "2D CL_SIGNED_INT8", "", 1, nil)
	addTest("cl_fill_images", "2D CL_SNORM_INT16", "", 1, nil)
	addTest("cl_fill_images", "2D CL_SNORM_INT8", "", 1, nil)
	addTest("cl_fill_images", "2D CL_UNORM_INT_101010", "", 1, nil)
	addTest("cl_fill_images", "2D CL_UNORM_INT16", "", 1, nil)
	addTest("cl_fill_images", "2D CL_UNORM_INT8", "", 1, nil)
	addTest("cl_fill_images", "2D CL_UNORM_SHORT_555", "", 1, nil)
	addTest("cl_fill_images", "2D CL_UNORM_SHORT_565", "", 1, nil)
	addTest("cl_fill_images", "2D CL_UNSIGNED_INT16", "", 1, nil)
	addTest("cl_fill_images", "2D CL_UNSIGNED_INT32", "", 1, nil)
	addTest("cl_fill_images", "2D CL_UNSIGNED_INT8", "", 1, nil)
	addTest("cl_fill_images", "3D CL_FLOAT", "", 1, nil)
	addTest("cl_fill_images", "3D CL_HALF_FLOAT", "", 1, nil)
	addTest("cl_fill_images", "3D CL_SIGNED_INT16", "", 1, nil)
	addTest("cl_fill_images", "3D CL_SIGNED_INT32", "", 1, nil)
	addTest("cl_fill_images", "3D CL_SIGNED_INT8", "", 1, nil)
	addTest("cl_fill_images", "3D CL_SNORM_INT16", "", 1, nil)
	addTest("cl_fill_images", "3D CL_SNORM_INT8", "", 1, nil)
	addTest("cl_fill_images", "3D CL_UNORM_INT_101010", "", 1, nil)
	addTest("cl_fill_images", "3D CL_UNORM_INT16", "", 1, nil)
	addTest("cl_fill_images", "3D CL_UNORM_INT8", "", 1, nil)
	addTest("cl_fill_images", "3D CL_UNORM_SHORT_555", "", 1, nil)
	addTest("cl_fill_images", "3D CL_UNORM_SHORT_565", "", 1, nil)
	addTest("cl_fill_images", "3D CL_UNSIGNED_INT16", "", 1, nil)
	addTest("cl_fill_images", "3D CL_UNSIGNED_INT32", "", 1, nil)
	addTest("cl_fill_images", "3D CL_UNSIGNED_INT8", "", 1, nil)
	addTest("cl_get_info", "1Darray CL_FLOAT", "", 1, nil)
	addTest("cl_get_info", "1Darray CL_HALF_FLOAT", "", 1, nil)
	addTest("cl_get_info", "1Darray CL_SIGNED_INT16", "", 1, nil)
	addTest("cl_get_info", "1Darray CL_SIGNED_INT32", "", 1, nil)
	addTest("cl_get_info", "1Darray CL_SIGNED_INT8", "", 1, nil)
	addTest("cl_get_info", "1Darray CL_SNORM_INT16", "", 1, nil)
	addTest("cl_get_info", "1Darray CL_SNORM_INT8", "", 1, nil)
	addTest("cl_get_info", "1Darray CL_UNORM_INT_101010", "", 1, nil)
	addTest("cl_get_info", "1Darray CL_UNORM_INT16", "", 1, nil)
	addTest("cl_get_info", "1Darray CL_UNORM_INT8", "", 1, nil)
	addTest("cl_get_info", "1Darray CL_UNORM_SHORT_555", "", 1, nil)
	addTest("cl_get_info", "1Darray CL_UNORM_SHORT_565", "", 1, nil)
	addTest("cl_get_info", "1Darray CL_UNSIGNED_INT16", "", 1, nil)
	addTest("cl_get_info", "1Darray CL_UNSIGNED_INT32", "", 1, nil)
	addTest("cl_get_info", "1Darray CL_UNSIGNED_INT8", "", 1, nil)
	addTest("cl_get_info", "1D CL_FLOAT", "", 1, nil)
	addTest("cl_get_info", "1D CL_HALF_FLOAT", "", 1, nil)
	addTest("cl_get_info", "1D CL_SIGNED_INT16", "", 1, nil)
	addTest("cl_get_info", "1D CL_SIGNED_INT32", "", 1, nil)
	addTest("cl_get_info", "1D CL_SIGNED_INT8", "", 1, nil)
	addTest("cl_get_info", "1D CL_SNORM_INT16", "", 1, nil)
	addTest("cl_get_info", "1D CL_SNORM_INT8", "", 1, nil)
	addTest("cl_get_info", "1D CL_UNORM_INT_101010", "", 1, nil)
	addTest("cl_get_info", "1D CL_UNORM_INT16", "", 1, nil)
	addTest("cl_get_info", "1D CL_UNORM_INT8", "", 1, nil)
	addTest("cl_get_info", "1D CL_UNORM_SHORT_555", "", 1, nil)
	addTest("cl_get_info", "1D CL_UNORM_SHORT_565", "", 1, nil)
	addTest("cl_get_info", "1D CL_UNSIGNED_INT16", "", 1, nil)
	addTest("cl_get_info", "1D CL_UNSIGNED_INT32", "", 1, nil)
	addTest("cl_get_info", "1D CL_UNSIGNED_INT8", "", 1, nil)
	addTest("cl_get_info", "2Darray CL_FLOAT", "", 1, nil)
	addTest("cl_get_info", "2Darray CL_HALF_FLOAT", "", 1, nil)
	addTest("cl_get_info", "2Darray CL_SIGNED_INT16", "", 1, nil)
	addTest("cl_get_info", "2Darray CL_SIGNED_INT32", "", 1, nil)
	addTest("cl_get_info", "2Darray CL_SIGNED_INT8", "", 1, nil)
	addTest("cl_get_info", "2Darray CL_SNORM_INT16", "", 1, nil)
	addTest("cl_get_info", "2Darray CL_SNORM_INT8", "", 1, nil)
	addTest("cl_get_info", "2Darray CL_UNORM_INT_101010", "", 1, nil)
	addTest("cl_get_info", "2Darray CL_UNORM_INT16", "", 1, nil)
	addTest("cl_get_info", "2Darray CL_UNORM_INT8", "", 1, nil)
	addTest("cl_get_info", "2Darray CL_UNORM_SHORT_555", "", 1, nil)
	addTest("cl_get_info", "2Darray CL_UNORM_SHORT_565", "", 1, nil)
	addTest("cl_get_info", "2Darray CL_UNSIGNED_INT16", "", 1, nil)
	addTest("cl_get_info", "2Darray CL_UNSIGNED_INT32", "", 1, nil)
	addTest("cl_get_info", "2Darray CL_UNSIGNED_INT8", "", 1, nil)
	addTest("cl_get_info", "2D CL_FLOAT", "", 1, nil)
	addTest("cl_get_info", "2D CL_HALF_FLOAT", "", 1, nil)
	addTest("cl_get_info", "2D CL_SIGNED_INT16", "", 1, nil)
	addTest("cl_get_info", "2D CL_SIGNED_INT32", "", 1, nil)
	addTest("cl_get_info", "2D CL_SIGNED_INT8", "", 1, nil)
	addTest("cl_get_info", "2D CL_SNORM_INT16", "", 1, nil)
	addTest("cl_get_info", "2D CL_SNORM_INT8", "", 1, nil)
	addTest("cl_get_info", "2D CL_UNORM_INT_101010", "", 1, nil)
	addTest("cl_get_info", "2D CL_UNORM_INT16", "", 1, nil)
	addTest("cl_get_info", "2D CL_UNORM_INT8", "", 1, nil)
	addTest("cl_get_info", "2D CL_UNORM_SHORT_555", "", 1, nil)
	addTest("cl_get_info", "2D CL_UNORM_SHORT_565", "", 1, nil)
	addTest("cl_get_info", "2D CL_UNSIGNED_INT16", "", 1, nil)
	addTest("cl_get_info", "2D CL_UNSIGNED_INT32", "", 1, nil)
	addTest("cl_get_info", "2D CL_UNSIGNED_INT8", "", 1, nil)
	addTest("cl_get_info", "3D CL_FLOAT", "", 1, nil)
	addTest("cl_get_info", "3D CL_HALF_FLOAT", "", 1, nil)
	addTest("cl_get_info", "3D CL_SIGNED_INT16", "", 1, nil)
	addTest("cl_get_info", "3D CL_SIGNED_INT32", "", 1, nil)
	addTest("cl_get_info", "3D CL_SIGNED_INT8", "", 1, nil)
	addTest("cl_get_info", "3D CL_SNORM_INT16", "", 1, nil)
	addTest("cl_get_info", "3D CL_SNORM_INT8", "", 1, nil)
	addTest("cl_get_info", "3D CL_UNORM_INT_101010", "", 1, nil)
	addTest("cl_get_info", "3D CL_UNORM_INT16", "", 1, nil)
	addTest("cl_get_info", "3D CL_UNORM_INT8", "", 1, nil)
	addTest("cl_get_info", "3D CL_UNORM_SHORT_555", "", 1, nil)
	addTest("cl_get_info", "3D CL_UNORM_SHORT_565", "", 1, nil)
	addTest("cl_get_info", "3D CL_UNSIGNED_INT16", "", 1, nil)
	addTest("cl_get_info", "3D CL_UNSIGNED_INT32", "", 1, nil)
	addTest("cl_get_info", "3D CL_UNSIGNED_INT8", "", 1, nil)
	addTest("cl_read_write_images", "1Darray CL_FLOAT", "", 1, nil)
	addTest("cl_read_write_images", "1Darray CL_HALF_FLOAT", "", 1, nil)
	addTest("cl_read_write_images", "1Darray CL_SIGNED_INT16", "", 1, nil)
	addTest("cl_read_write_images", "1Darray CL_SIGNED_INT32", "", 1, nil)
	addTest("cl_read_write_images", "1Darray CL_SIGNED_INT8", "", 1, nil)
	addTest("cl_read_write_images", "1Darray CL_SNORM_INT16", "", 1, nil)
	addTest("cl_read_write_images", "1Darray CL_SNORM_INT8", "", 1, nil)
	addTest("cl_read_write_images", "1Darray CL_UNORM_INT_101010", "", 1, nil)
	addTest("cl_read_write_images", "1Darray CL_UNORM_INT16", "", 1, nil)
	addTest("cl_read_write_images", "1Darray CL_UNORM_INT8", "", 1, nil)
	addTest("cl_read_write_images", "1Darray CL_UNORM_SHORT_555", "", 1, nil)
	addTest("cl_read_write_images", "1Darray CL_UNORM_SHORT_565", "", 1, nil)
	addTest("cl_read_write_images", "1Darray CL_UNSIGNED_INT16", "", 1, nil)
	addTest("cl_read_write_images", "1Darray CL_UNSIGNED_INT32", "", 1, nil)
	addTest("cl_read_write_images", "1Darray CL_UNSIGNED_INT8", "", 1, nil)
	addTest("cl_read_write_images", "1D CL_FLOAT", "", 1, nil)
	addTest("cl_read_write_images", "1D CL_HALF_FLOAT", "", 1, nil)
	addTest("cl_read_write_images", "1D CL_SIGNED_INT16", "", 1, nil)
	addTest("cl_read_write_images", "1D CL_SIGNED_INT32", "", 1, nil)
	addTest("cl_read_write_images", "1D CL_SIGNED_INT8", "", 1, nil)
	addTest("cl_read_write_images", "1D CL_SNORM_INT16", "", 1, nil)
	addTest("cl_read_write_images", "1D CL_SNORM_INT8", "", 1, nil)
	addTest("cl_read_write_images", "1D CL_UNORM_INT_101010", "", 1, nil)
	addTest("cl_read_write_images", "1D CL_UNORM_INT16", "", 1, nil)
	addTest("cl_read_write_images", "1D CL_UNORM_INT8", "", 1, nil)
	addTest("cl_read_write_images", "1D CL_UNORM_SHORT_555", "", 1, nil)
	addTest("cl_read_write_images", "1D CL_UNORM_SHORT_565", "", 1, nil)
	addTest("cl_read_write_images", "1D CL_UNSIGNED_INT16", "", 1, nil)
	addTest("cl_read_write_images", "1D CL_UNSIGNED_INT32", "", 1, nil)
	addTest("cl_read_write_images", "1D CL_UNSIGNED_INT8", "", 1, nil)
	addTest("cl_read_write_images", "2Darray CL_FLOAT", "", 1, nil)
	addTest("cl_read_write_images", "2Darray CL_HALF_FLOAT", "", 1, nil)
	addTest("cl_read_write_images", "2Darray CL_SIGNED_INT16", "", 1, nil)
	addTest("cl_read_write_images", "2Darray CL_SIGNED_INT32", "", 1, nil)
	addTest("cl_read_write_images", "2Darray CL_SIGNED_INT8", "", 1, nil)
	addTest("cl_read_write_images", "2Darray CL_SNORM_INT16", "", 1, nil)
	addTest("cl_read_write_images", "2Darray CL_SNORM_INT8", "", 1, nil)
	addTest("cl_read_write_images", "2Darray CL_UNORM_INT_101010", "", 1, nil)
	addTest("cl_read_write_images", "2Darray CL_UNORM_INT16", "", 1, nil)
	addTest("cl_read_write_images", "2Darray CL_UNORM_INT8", "", 1, nil)
	addTest("cl_read_write_images", "2Darray CL_UNORM_SHORT_555", "", 1, nil)
	addTest("cl_read_write_images", "2Darray CL_UNORM_SHORT_565", "", 1, nil)
	addTest("cl_read_write_images", "2Darray CL_UNSIGNED_INT16", "", 1, nil)
	addTest("cl_read_write_images", "2Darray CL_UNSIGNED_INT32", "", 1, nil)
	addTest("cl_read_write_images", "2Darray CL_UNSIGNED_INT8", "", 1, nil)
	addTest("cl_read_write_images", "2D CL_FLOAT", "", 1, nil)
	addTest("cl_read_write_images", "2D CL_HALF_FLOAT", "", 1, nil)
	addTest("cl_read_write_images", "2D CL_SIGNED_INT16", "", 1, nil)
	addTest("cl_read_write_images", "2D CL_SIGNED_INT32", "", 1, nil)
	addTest("cl_read_write_images", "2D CL_SIGNED_INT8", "", 1, nil)
	addTest("cl_read_write_images", "2D CL_SNORM_INT16", "", 1, nil)
	addTest("cl_read_write_images", "2D CL_SNORM_INT8", "", 1, nil)
	addTest("cl_read_write_images", "2D CL_UNORM_INT_101010", "", 1, nil)
	addTest("cl_read_write_images", "2D CL_UNORM_INT16", "", 1, nil)
	addTest("cl_read_write_images", "2D CL_UNORM_INT8", "", 1, nil)
	addTest("cl_read_write_images", "2D CL_UNORM_SHORT_555", "", 1, nil)
	addTest("cl_read_write_images", "2D CL_UNORM_SHORT_565", "", 1, nil)
	addTest("cl_read_write_images", "2D CL_UNSIGNED_INT16", "", 1, nil)
	addTest("cl_read_write_images", "2D CL_UNSIGNED_INT32", "", 1, nil)
	addTest("cl_read_write_images", "2D CL_UNSIGNED_INT8", "", 1, nil)
	addTest("cl_read_write_images", "3D CL_FLOAT", "", 1, nil)
	addTest("cl_read_write_images", "3D CL_HALF_FLOAT", "", 1, nil)
	addTest("cl_read_write_images", "3D CL_SIGNED_INT16", "", 1, nil)
	addTest("cl_read_write_images", "3D CL_SIGNED_INT32", "", 1, nil)
	addTest("cl_read_write_images", "3D CL_SIGNED_INT8", "", 1, nil)
	addTest("cl_read_write_images", "3D CL_SNORM_INT16", "", 1, nil)
	addTest("cl_read_write_images", "3D CL_SNORM_INT8", "", 1, nil)
	addTest("cl_read_write_images", "3D CL_UNORM_INT_101010", "", 1, nil)
	addTest("cl_read_write_images", "3D CL_UNORM_INT16", "", 1, nil)
	addTest("cl_read_write_images", "3D CL_UNORM_INT8", "", 1, nil)
	addTest("cl_read_write_images", "3D CL_UNORM_SHORT_555", "", 1, nil)
	addTest("cl_read_write_images", "3D CL_UNORM_SHORT_565", "", 1, nil)
	addTest("cl_read_write_images", "3D CL_UNSIGNED_INT16", "", 1, nil)
	addTest("cl_read_write_images", "3D CL_UNSIGNED_INT32", "", 1, nil)
	addTest("cl_read_write_images", "3D CL_UNSIGNED_INT8", "", 1, nil)
	addTest("commonfns", "clamp", "", 1, nil)
	addTest("commonfns", "degrees", "", 1, nil)
	addTest("commonfns", "fmaxf", "", 1, nil)
	addTest("commonfns", "fmax", "", 1, nil)
	addTest("commonfns", "fminf", "", 1, nil)
	addTest("commonfns", "fmin", "", 1, nil)
	addTest("commonfns", "maxf", "", 1, nil)
	addTest("commonfns", "max", "", 1, nil)
	addTest("commonfns", "minf", "", 1, nil)
	addTest("commonfns", "min", "", 1, nil)
	addTest("commonfns", "mix", "", 1, nil)
	addTest("commonfns", "radians", "", 1, nil)
	addTest("commonfns", "sign", "", 1, nil)
	addTest("commonfns", "smoothstepf", "", 1, nil)
	addTest("commonfns", "smoothstep", "", 1, nil)
	addTest("commonfns", "stepf", "", 1, nil)
	addTest("commonfns", "step", "", 1, nil)
	addTest("compiler", "async_build", "", 1, nil)
	addTest("compiler", "compile_and_link_status_options_log", "", 1, nil)
	addTest("compiler", "compiler_defines_for_extensions", "", 1, nil)
	addTest("compiler", "execute_after_embedded_header_link", "", 1, nil)
	addTest("compiler", "execute_after_included_header_link", "", 1, nil)
	addTest("compiler", "execute_after_serialize_reload_library", "", 1, nil)
	addTest("compiler", "execute_after_serialize_reload_object", "", 1, nil)
	addTest("compiler", "execute_after_simple_compile_and_link_no_device_info", "", 1, nil)
	addTest("compiler", "execute_after_simple_compile_and_link", "", 1, nil)
	addTest("compiler", "execute_after_simple_compile_and_link_with_callbacks", "", 1, nil)
	addTest("compiler", "execute_after_simple_compile_and_link_with_defines", "", 1, nil)
	addTest("compiler", "execute_after_simple_library_with_link", "", 1, nil)
	addTest("compiler", "execute_after_two_file_link", "", 1, nil)
	addTest("compiler", "features_macro", "", 1, nil)
	addTest("compiler", "get_program_build_info", "", 1, nil)
	addTest("compiler", "get_program_info", "", 1, nil)
	addTest("compiler", "get_program_source", "", 1, nil)
	addTest("compiler", "image_macro", "", 1, nil)
	addTest("compiler", "large_compile", "", 1, nil)
	addTest("compiler", "load_discreet_length_source", "", 1, nil)
	addTest("compiler", "load_multistring_source", "", 1, nil)
	addTest("compiler", "load_null_terminated_multi_line_source", "", 1, nil)
	addTest("compiler", "load_null_terminated_partial_multi_line_source", "", 1, nil)
	addTest("compiler", "load_null_terminated_source", "", 1, nil)
	addTest("compiler", "load_program_source", "", 1, nil)
	addTest("compiler", "load_two_kernel_source", "", 1, nil)
	addTest("compiler", "multi_file_libraries", "", 1, nil)
	addTest("compiler", "multiple_embedded_headers", "", 1, nil)
	addTest("compiler", "multiple_files", "", 1, nil)
	addTest("compiler", "multiple_files_multiple_libraries", "", 1, nil)
	addTest("compiler", "multiple_libraries", "", 1, nil)
	addTest("compiler", "opencl_c_versions", "", 1, nil)
	addTest("compiler", "options_build_macro_existence", "", 1, nil)
	addTest("compiler", "options_build_macro", "", 1, nil)
	addTest("compiler", "options_build_optimizations", "", 1, nil)
	addTest("compiler", "options_denorm_cache", "", 1, nil)
	addTest("compiler", "options_include_directory", "", 1, nil)
	addTest("compiler", "pragma_unroll", "", 1, nil)
	addTest("compiler", "preprocessor_define_udef", "", 1, nil)
	addTest("compiler", "preprocessor_include", "", 1, nil)
	addTest("compiler", "preprocessor_line_error", "", 1, nil)
	addTest("compiler", "preprocessor_pragma", "", 1, nil)
	addTest("compiler", "program_binary_type", "", 1, nil)
	addTest("compiler", "simple_compile_only", "", 1, nil)
	addTest("compiler", "simple_compile_with_callback", "", 1, nil)
	addTest("compiler", "simple_embedded_header_compile", "", 1, nil)
	addTest("compiler", "simple_embedded_header_link", "", 1, nil)
	addTest("compiler", "simple_extern_compile_only", "", 1, nil)
	addTest("compiler", "simple_library_only", "", 1, nil)
	addTest("compiler", "simple_library_with_callback", "", 1, nil)
	addTest("compiler", "simple_library_with_link", "", 1, nil)
	addTest("compiler", "simple_link_only", "", 1, nil)
	addTest("compiler", "simple_link_with_callback", "", 1, nil)
	addTest("compiler", "simple_static_compile_only", "", 1, nil)
	addTest("compiler", "two_file_link", "", 1, nil)
	addTest("compiler", "two_file_regular_function_access", "", 1, nil)
	addTest("compiler", "two_file_regular_struct_access", "", 1, nil)
	addTest("compiler", "two_file_regular_variable_access", "", 1, nil)
	addTest("compiler", "unload_build_info", "", 1, nil)
	addTest("compiler", "unload_build_threaded", "", 1, nil)
	addTest("compiler", "unload_build_unload_create_kernel", "", 1, nil)
	addTest("compiler", "unload_compile_unload_link", "", 1, nil)
	addTest("compiler", "unload_link_different", "", 1, nil)
	addTest("compiler", "unload_program_binaries", "", 1, nil)
	addTest("compiler", "unload_repeated", "", 1, nil)
	addTest("compiler", "unload_valid", "", 1, nil)
	addTest("computeinfo", "computeinfo", "", 1, nil)
	addTest("computeinfo", "conformance_version", "", 1, nil)
	addTest("computeinfo", "device_uuid", "", 1, nil)
	addTest("computeinfo", "extended_versioning", "", 1, nil)
	addTest("contractions", "contractions_double_0", "", 1, nil)
	addTest("contractions", "contractions_double_1", "", 1, nil)
	addTest("contractions", "contractions_double_2", "", 1, nil)
	addTest("contractions", "contractions_double_3", "", 1, nil)
	addTest("contractions", "contractions_double_4", "", 1, nil)
	addTest("contractions", "contractions_double_5", "", 1, nil)
	addTest("contractions", "contractions_double_6", "", 1, nil)
	addTest("contractions", "contractions_double_7", "", 1, nil)
	addTest("contractions", "contractions_float_0", "", 1, nil)
	addTest("contractions", "contractions_float_1", "", 1, nil)
	addTest("contractions", "contractions_float_2", "", 1, nil)
	addTest("contractions", "contractions_float_3", "", 1, nil)
	addTest("contractions", "contractions_float_4", "", 1, nil)
	addTest("contractions", "contractions_float_5", "", 1, nil)
	addTest("contractions", "contractions_float_6", "", 1, nil)
	addTest("contractions", "contractions_float_7", "", 1, nil)
	addTest("conversions", "char_char", "-w -1", 1, nil)
	addTest("conversions", "char_float", "-w -1", 1, nil)
	addTest("conversions", "char_int", "-w -1", 1, nil)
	addTest("conversions", "char_long", "-w -1", 1, nil)
	addTest("conversions", "char_short", "-w -1", 1, nil)
	addTest("conversions", "char_uchar", "-w -1", 1, nil)
	addTest("conversions", "char_uint", "-w -1", 1, nil)
	addTest("conversions", "char_ulong", "-w -1", 1, nil)
	addTest("conversions", "char_ushort", "-w -1", 1, nil)
	addTest("conversions", "float_char", "-w -1", 1, nil)
	addTest("conversions", "float_float", "-w -1", 1, nil)
	addTest("conversions", "float_int", "-w -1", 1, nil)
	addTest("conversions", "float_long", "-w -1", 1, nil)
	addTest("conversions", "float_short", "-w -1", 1, nil)
	addTest("conversions", "float_uchar", "-w -1", 1, nil)
	addTest("conversions", "float_uint", "-w -1", 1, nil)
	addTest("conversions", "float_ulong", "-w -1", 1, nil)
	addTest("conversions", "float_ushort", "-w -1", 1, nil)
	addTest("conversions", "int_char", "-w -1", 1, nil)
	addTest("conversions", "int_float", "-w -1", 1, nil)
	addTest("conversions", "int_int", "-w -1", 1, nil)
	addTest("conversions", "int_long", "-w -1", 1, nil)
	addTest("conversions", "int_short", "-w -1", 1, nil)
	addTest("conversions", "int_uchar", "-w -1", 1, nil)
	addTest("conversions", "int_uint", "-w -1", 1, nil)
	addTest("conversions", "int_ulong", "-w -1", 1, nil)
	addTest("conversions", "int_ushort", "-w -1", 1, nil)
	addTest("conversions", "long_char", "-w -1", 1, nil)
	addTest("conversions", "long_float", "-w -1", 1, nil)
	addTest("conversions", "long_int", "-w -1", 1, nil)
	addTest("conversions", "long_long", "-w -1", 1, nil)
	addTest("conversions", "long_short", "-w -1", 1, nil)
	addTest("conversions", "long_uchar", "-w -1", 1, nil)
	addTest("conversions", "long_uint", "-w -1", 1, nil)
	addTest("conversions", "long_ulong", "-w -1", 1, nil)
	addTest("conversions", "long_ushort", "-w -1", 1, nil)
	addTest("conversions", "short_char", "-w -1", 1, nil)
	addTest("conversions", "short_float", "-w -1", 1, nil)
	addTest("conversions", "short_int", "-w -1", 1, nil)
	addTest("conversions", "short_long", "-w -1", 1, nil)
	addTest("conversions", "short_short", "-w -1", 1, nil)
	addTest("conversions", "short_uchar", "-w -1", 1, nil)
	addTest("conversions", "short_uint", "-w -1", 1, nil)
	addTest("conversions", "short_ulong", "-w -1", 1, nil)
	addTest("conversions", "short_ushort", "-w -1", 1, nil)
	addTest("conversions", "uchar_char", "-w -1", 1, nil)
	addTest("conversions", "uchar_float", "-w -1", 1, nil)
	addTest("conversions", "uchar_int", "-w -1", 1, nil)
	addTest("conversions", "uchar_long", "-w -1", 1, nil)
	addTest("conversions", "uchar_short", "-w -1", 1, nil)
	addTest("conversions", "uchar_uchar", "-w -1", 1, nil)
	addTest("conversions", "uchar_uint", "-w -1", 1, nil)
	addTest("conversions", "uchar_ulong", "-w -1", 1, nil)
	addTest("conversions", "uchar_ushort", "-w -1", 1, nil)
	addTest("conversions", "uint_char", "-w -1", 1, nil)
	addTest("conversions", "uint_float", "-w -1", 1, nil)
	addTest("conversions", "uint_int", "-w -1", 1, nil)
	addTest("conversions", "uint_long", "-w -1", 1, nil)
	addTest("conversions", "uint_short", "-w -1", 1, nil)
	addTest("conversions", "uint_uchar", "-w -1", 1, nil)
	addTest("conversions", "uint_uint", "-w -1", 1, nil)
	addTest("conversions", "uint_ulong", "-w -1", 1, nil)
	addTest("conversions", "uint_ushort", "-w -1", 1, nil)
	addTest("conversions", "ulong_char", "-w -1", 1, nil)
	addTest("conversions", "ulong_float", "-w -1", 1, nil)
	addTest("conversions", "ulong_int", "-w -1", 1, nil)
	addTest("conversions", "ulong_long", "-w -1", 1, nil)
	addTest("conversions", "ulong_short", "-w -1", 1, nil)
	addTest("conversions", "ulong_uchar", "-w -1", 1, nil)
	addTest("conversions", "ulong_uint", "-w -1", 1, nil)
	addTest("conversions", "ulong_ulong", "-w -1", 1, nil)
	addTest("conversions", "ulong_ushort", "-w -1", 1, nil)
	addTest("conversions", "ushort_char", "-w -1", 1, nil)
	addTest("conversions", "ushort_float", "-w -1", 1, nil)
	addTest("conversions", "ushort_int", "-w -1", 1, nil)
	addTest("conversions", "ushort_long", "-w -1", 1, nil)
	addTest("conversions", "ushort_short", "-w -1", 1, nil)
	addTest("conversions", "ushort_uchar", "-w -1", 1, nil)
	addTest("conversions", "ushort_uint", "-w -1", 1, nil)
	addTest("conversions", "ushort_ulong", "-w -1", 1, nil)
	addTest("conversions", "ushort_ushort", "-w -1", 1, nil)
	addTest("events", "callbacks", "", 1, nil)
	addTest("events", "callbacks_simultaneous", "", 1, nil)
	addTest("events", "event_enqueue_barrier_with_event_list", "", 1, nil)
	addTest("events", "event_enqueue_marker", "", 1, nil)
	addTest("events", "event_enqueue_marker_with_event_list", "", 1, nil)
	addTest("events", "event_finish_array", "", 1, nil)
	addTest("events", "event_finish_execute", "", 1, nil)
	addTest("events", "event_flush", "", 1, nil)
	addTest("events", "event_get_execute_status", "", 1, nil)
	addTest("events", "event_get_info", "", 1, nil)
	addTest("events", "event_get_read_array_status", "", 1, nil)
	addTest("events", "event_get_write_array_status", "", 1, nil)
	addTest("events", "event_release_before_done", "", 1, nil)
	addTest("events", "event_wait_for_array", "", 1, nil)
	addTest("events", "event_wait_for_execute", "", 1, nil)
	addTest("events", "out_of_order_event_enqueue_barrier_single_queue", "", 1, nil)
	addTest("events", "out_of_order_event_enqueue_marker_multi_queue_multi_device", "", 1, nil)
	addTest("events", "out_of_order_event_enqueue_marker_multi_queue", "", 1, nil)
	addTest("events", "out_of_order_event_enqueue_marker_single_queue", "", 1, nil)
	addTest("events", "out_of_order_event_enqueue_wait_for_events_multi_queue_multi_device", "", 1, nil)
	addTest("events", "out_of_order_event_enqueue_wait_for_events_multi_queue", "", 1, nil)
	addTest("events", "out_of_order_event_enqueue_wait_for_events_single_queue", "", 1, nil)
	addTest("events", "out_of_order_event_waitlist_multi_queue_multi_device", "", 1, nil)
	addTest("events", "out_of_order_event_waitlist_multi_queue", "", 1, nil)
	addTest("events", "out_of_order_event_waitlist_single_queue", "", 1, nil)
	addTest("events", "userevents_multithreaded", "", 1, nil)
	addTest("events", "userevents", "", 1, nil)
	addTest("events", "waitlists", "", 1, nil)
	addTest("geometrics", "geom_cross", "", 1, nil)
	addTest("geometrics", "geom_distance", "", 1, nil)
	addTest("geometrics", "geom_dot", "", 1, nil)
	addTest("geometrics", "geom_fast_distance", "", 1, nil)
	addTest("geometrics", "geom_fast_length", "", 1, nil)
	addTest("geometrics", "geom_fast_normalize", "", 1, nil)
	addTest("geometrics", "geom_length", "", 1, nil)
	addTest("geometrics", "geom_normalize", "", 1, nil)
	addTest("half", "roundTrip", "-w", 1, nil)
	addTest("half", "vloada_half", "-w", 1, nil)
	addTest("half", "vload_half", "-w", 1, nil)
	addTest("half", "vstorea_half_rte", "-w", 1, nil)
	addTest("half", "vstorea_half_rtn", "-w", 1, nil)
	addTest("half", "vstorea_half_rtp", "-w", 1, nil)
	addTest("half", "vstorea_half_rtz", "-w", 1, nil)
	addTest("half", "vstorea_half", "-w", 1, nil)
	addTest("half", "vstore_half_rte", "-w", 1, nil)
	addTest("half", "vstore_half_rtn", "-w", 1, nil)
	addTest("half", "vstore_half_rtp", "-w", 1, nil)
	addTest("half", "vstore_half_rtz", "-w", 1, nil)
	addTest("half", "vstore_half", "-w", 1, nil)
	addTest("image_streams", "1Darray CL_FLOAT", "", 10, nil)
	addTest("image_streams", "1Darray CL_HALF_FLOAT", "", 10, nil)
	addTest("image_streams", "1Darray CL_SIGNED_INT16", "", 1, nil)
	addTest("image_streams", "1Darray CL_SIGNED_INT32", "", 1, nil)
	addTest("image_streams", "1Darray CL_SIGNED_INT8", "", 1, nil)
	addTest("image_streams", "1Darray CL_SNORM_INT16", "", 10, nil)
	addTest("image_streams", "1Darray CL_SNORM_INT8", "", 10, nil)
	addTest("image_streams", "1Darray CL_UNORM_INT_101010", "", 1, nil)
	addTest("image_streams", "1Darray CL_UNORM_INT16", "", 10, nil)
	addTest("image_streams", "1Darray CL_UNORM_INT8", "", 10, nil)
	addTest("image_streams", "1Darray CL_UNORM_SHORT_555", "", 1, nil)
	addTest("image_streams", "1Darray CL_UNORM_SHORT_565", "", 1, nil)
	addTest("image_streams", "1Darray CL_UNSIGNED_INT16", "", 1, nil)
	addTest("image_streams", "1Darray CL_UNSIGNED_INT32", "", 1, nil)
	addTest("image_streams", "1Darray CL_UNSIGNED_INT8", "", 1, nil)
	addTest("image_streams", "1D CL_FLOAT", "", 10, nil)
	addTest("image_streams", "1D CL_HALF_FLOAT", "", 10, nil)
	addTest("image_streams", "1D CL_SIGNED_INT16", "", 1, nil)
	addTest("image_streams", "1D CL_SIGNED_INT32", "", 1, nil)
	addTest("image_streams", "1D CL_SIGNED_INT8", "", 1, nil)
	addTest("image_streams", "1D CL_SNORM_INT16", "", 10, nil)
	addTest("image_streams", "1D CL_SNORM_INT8", "", 10, nil)
	addTest("image_streams", "1D CL_UNORM_INT_101010", "", 1, nil)
	addTest("image_streams", "1D CL_UNORM_INT16", "", 10, nil)
	addTest("image_streams", "1D CL_UNORM_INT8", "", 10, nil)
	addTest("image_streams", "1D CL_UNORM_SHORT_555", "", 1, nil)
	addTest("image_streams", "1D CL_UNORM_SHORT_565", "", 1, nil)
	addTest("image_streams", "1D CL_UNSIGNED_INT16", "", 1, nil)
	addTest("image_streams", "1D CL_UNSIGNED_INT32", "", 1, nil)
	addTest("image_streams", "1D CL_UNSIGNED_INT8", "", 1, nil)
	addTest("image_streams", "2Darray CL_FLOAT", "", 10, nil)
	addTest("image_streams", "2Darray CL_HALF_FLOAT", "", 10, nil)
	addTest("image_streams", "2Darray CL_SIGNED_INT16", "", 10, nil)
	addTest("image_streams", "2Darray CL_SIGNED_INT32", "", 10, nil)
	addTest("image_streams", "2Darray CL_SIGNED_INT8", "", 10, nil)
	addTest("image_streams", "2Darray CL_SNORM_INT16", "", 10, nil)
	addTest("image_streams", "2Darray CL_SNORM_INT8", "", 10, nil)
	addTest("image_streams", "2Darray CL_UNORM_INT_101010", "", 1, nil)
	addTest("image_streams", "2Darray CL_UNORM_INT16", "", 10, nil)
	addTest("image_streams", "2Darray CL_UNORM_INT8", "", 10, nil)
	addTest("image_streams", "2Darray CL_UNORM_SHORT_555", "", 1, nil)
	addTest("image_streams", "2Darray CL_UNORM_SHORT_565", "", 1, nil)
	addTest("image_streams", "2Darray CL_UNSIGNED_INT16", "", 10, nil)
	addTest("image_streams", "2Darray CL_UNSIGNED_INT32", "", 10, nil)
	addTest("image_streams", "2Darray CL_UNSIGNED_INT8", "", 10, nil)
	addTest("image_streams", "2D CL_FLOAT", "", 10, nil)
	addTest("image_streams", "2D CL_HALF_FLOAT", "", 10, nil)
	addTest("image_streams", "2D CL_SIGNED_INT16", "", 10, nil)
	addTest("image_streams", "2D CL_SIGNED_INT32", "", 10, nil)
	addTest("image_streams", "2D CL_SIGNED_INT8", "", 10, nil)
	addTest("image_streams", "2D CL_SNORM_INT16", "", 10, nil)
	addTest("image_streams", "2D CL_SNORM_INT8", "", 10, nil)
	addTest("image_streams", "2D CL_UNORM_INT_101010", "", 1, nil)
	addTest("image_streams", "2D CL_UNORM_INT16", "", 10, nil)
	addTest("image_streams", "2D CL_UNORM_INT8", "", 10, nil)
	addTest("image_streams", "2D CL_UNORM_SHORT_555", "", 1, nil)
	addTest("image_streams", "2D CL_UNORM_SHORT_565", "", 1, nil)
	addTest("image_streams", "2D CL_UNSIGNED_INT16", "", 10, nil)
	addTest("image_streams", "2D CL_UNSIGNED_INT32", "", 10, nil)
	addTest("image_streams", "2D CL_UNSIGNED_INT8", "", 10, nil)
	addTest("image_streams", "3D CL_FLOAT", "", 10, nil)
	addTest("image_streams", "3D CL_HALF_FLOAT", "", 10, nil)
	addTest("image_streams", "3D CL_SIGNED_INT16", "", 10, nil)
	addTest("image_streams", "3D CL_SIGNED_INT32", "", 10, nil)
	addTest("image_streams", "3D CL_SIGNED_INT8", "", 10, nil)
	addTest("image_streams", "3D CL_SNORM_INT16", "", 10, nil)
	addTest("image_streams", "3D CL_SNORM_INT8", "", 10, nil)
	addTest("image_streams", "3D CL_UNORM_INT_101010", "", 1, nil)
	addTest("image_streams", "3D CL_UNORM_INT16", "", 10, nil)
	addTest("image_streams", "3D CL_UNORM_INT8", "", 10, nil)
	addTest("image_streams", "3D CL_UNORM_SHORT_555", "", 1, nil)
	addTest("image_streams", "3D CL_UNORM_SHORT_565", "", 1, nil)
	addTest("image_streams", "3D CL_UNSIGNED_INT16", "", 10, nil)
	addTest("image_streams", "3D CL_UNSIGNED_INT32", "", 10, nil)
	addTest("image_streams", "3D CL_UNSIGNED_INT8", "", 10, nil)
	addTest("integer_ops", "char_compare", "", 10, nil)
	addTest("integer_ops", "char_logic", "", 10, nil)
	addTest("integer_ops", "char_math", "", 10, nil)
	addTest("integer_ops", "char_shift", "", 10, nil)
	addTest("integer_ops", "int_compare", "", 10, nil)
	addTest("integer_ops", "integer_abs", "", 1, nil)
	addTest("integer_ops", "integer_abs_diff", "", 1, nil)
	addTest("integer_ops", "integer_addAssign", "", 1, nil)
	addTest("integer_ops", "integer_add_sat", "", 1, nil)
	addTest("integer_ops", "integer_andAssign", "", 1, nil)
	addTest("integer_ops", "integer_clamp", "", 1, nil)
	addTest("integer_ops", "integer_clz", "", 1, nil)
	addTest("integer_ops", "integer_ctz", "", 1, nil)
	addTest("integer_ops", "integer_divideAssign", "", 1, nil)
	addTest("integer_ops", "integer_exclusiveOrAssign", "", 1, nil)
	addTest("integer_ops", "integer_hadd", "", 1, nil)
	addTest("integer_ops", "integer_mad24", "", 1, nil)
	addTest("integer_ops", "integer_mad_hi", "", 1, nil)
	addTest("integer_ops", "integer_mad_sat", "", 1, nil)
	addTest("integer_ops", "integer_max", "", 1, nil)
	addTest("integer_ops", "integer_min", "", 1, nil)
	addTest("integer_ops", "integer_moduloAssign", "", 1, nil)
	addTest("integer_ops", "integer_mul24", "", 1, nil)
	addTest("integer_ops", "integer_mul_hi", "", 1, nil)
	addTest("integer_ops", "integer_multiplyAssign", "", 1, nil)
	addTest("integer_ops", "integer_orAssign", "", 1, nil)
	addTest("integer_ops", "integer_rhadd", "", 1, nil)
	addTest("integer_ops", "integer_rotate", "", 1, nil)
	addTest("integer_ops", "integer_sub_sat", "", 1, nil)
	addTest("integer_ops", "integer_subtractAssign", "", 1, nil)
	addTest("integer_ops", "integer_upsample", "", 1, nil)
	addTest("integer_ops", "int_logic", "", 10, nil)
	addTest("integer_ops", "int_math", "", 10, nil)
	addTest("integer_ops", "int_shift", "", 10, nil)
	addTest("integer_ops", "long_compare", "", 10, nil)
	addTest("integer_ops", "long_logic", "", 10, nil)
	addTest("integer_ops", "long_math", "", 10, nil)
	addTest("integer_ops", "long_shift", "", 10, nil)
	addTest("integer_ops", "popcount", "", 1, nil)
	addTest("integer_ops", "quick_char_compare", "", 1, nil)
	addTest("integer_ops", "quick_char_logic", "", 1, nil)
	addTest("integer_ops", "quick_char_math", "", 1, nil)
	addTest("integer_ops", "quick_char_shift", "", 1, nil)
	addTest("integer_ops", "quick_int_compare", "", 1, nil)
	addTest("integer_ops", "quick_int_logic", "", 1, nil)
	addTest("integer_ops", "quick_int_math", "", 1, nil)
	addTest("integer_ops", "quick_int_shift", "", 1, nil)
	addTest("integer_ops", "quick_long_compare", "", 1, nil)
	addTest("integer_ops", "quick_long_logic", "", 1, nil)
	addTest("integer_ops", "quick_long_math", "", 1, nil)
	addTest("integer_ops", "quick_long_shift", "", 1, nil)
	addTest("integer_ops", "quick_short_compare", "", 1, nil)
	addTest("integer_ops", "quick_short_logic", "", 1, nil)
	addTest("integer_ops", "quick_short_math", "", 1, nil)
	addTest("integer_ops", "quick_short_shift", "", 1, nil)
	addTest("integer_ops", "quick_uchar_compare", "", 1, nil)
	addTest("integer_ops", "quick_uchar_logic", "", 1, nil)
	addTest("integer_ops", "quick_uchar_math", "", 1, nil)
	addTest("integer_ops", "quick_uchar_shift", "", 1, nil)
	addTest("integer_ops", "quick_uint_compare", "", 1, nil)
	addTest("integer_ops", "quick_uint_logic", "", 1, nil)
	addTest("integer_ops", "quick_uint_math", "", 1, nil)
	addTest("integer_ops", "quick_uint_shift", "", 1, nil)
	addTest("integer_ops", "quick_ulong_compare", "", 1, nil)
	addTest("integer_ops", "quick_ulong_logic", "", 1, nil)
	addTest("integer_ops", "quick_ulong_math", "", 1, nil)
	addTest("integer_ops", "quick_ulong_shift", "", 1, nil)
	addTest("integer_ops", "quick_ushort_compare", "", 1, nil)
	addTest("integer_ops", "quick_ushort_logic", "", 1, nil)
	addTest("integer_ops", "quick_ushort_math", "", 1, nil)
	addTest("integer_ops", "quick_ushort_shift", "", 1, nil)
	addTest("integer_ops", "short_compare", "", 10, nil)
	addTest("integer_ops", "short_logic", "", 10, nil)
	addTest("integer_ops", "short_math", "", 10, nil)
	addTest("integer_ops", "short_shift", "", 10, nil)
	addTest("integer_ops", "uchar_compare", "", 10, nil)
	addTest("integer_ops", "uchar_logic", "", 10, nil)
	addTest("integer_ops", "uchar_math", "", 10, nil)
	addTest("integer_ops", "uchar_shift", "", 10, nil)
	addTest("integer_ops", "uint_compare", "", 10, nil)
	addTest("integer_ops", "uint_logic", "", 10, nil)
	addTest("integer_ops", "uint_math", "", 10, nil)
	addTest("integer_ops", "uint_shift", "", 10, nil)
	addTest("integer_ops", "ulong_compare", "", 10, nil)
	addTest("integer_ops", "ulong_logic", "", 10, nil)
	addTest("integer_ops", "ulong_math", "", 10, nil)
	addTest("integer_ops", "ulong_shift", "", 10, nil)
	addTest("integer_ops", "unary_ops_decrement", "", 1, nil)
	addTest("integer_ops", "unary_ops_full", "", 1, nil)
	addTest("integer_ops", "unary_ops_increment", "", 1, nil)
	addTest("integer_ops", "ushort_compare", "", 10, nil)
	addTest("integer_ops", "ushort_logic", "", 10, nil)
	addTest("integer_ops", "ushort_math", "", 10, nil)
	addTest("integer_ops", "ushort_shift", "", 10, nil)
	addTest("integer_ops", "vector_scalar", "", 10, nil)
	addTest("kernel_image_methods", "1Darray CL_FLOAT", "", 1, nil)
	addTest("kernel_image_methods", "1Darray CL_HALF_FLOAT", "", 1, nil)
	addTest("kernel_image_methods", "1Darray CL_SIGNED_INT16", "", 1, nil)
	addTest("kernel_image_methods", "1Darray CL_SIGNED_INT32", "", 1, nil)
	addTest("kernel_image_methods", "1Darray CL_SIGNED_INT8", "", 1, nil)
	addTest("kernel_image_methods", "1Darray CL_SNORM_INT16", "", 1, nil)
	addTest("kernel_image_methods", "1Darray CL_SNORM_INT8", "", 1, nil)
	addTest("kernel_image_methods", "1Darray CL_UNORM_INT_101010", "", 1, nil)
	addTest("kernel_image_methods", "1Darray CL_UNORM_INT16", "", 1, nil)
	addTest("kernel_image_methods", "1Darray CL_UNORM_INT8", "", 1, nil)
	addTest("kernel_image_methods", "1Darray CL_UNORM_SHORT_555", "", 1, nil)
	addTest("kernel_image_methods", "1Darray CL_UNORM_SHORT_565", "", 1, nil)
	addTest("kernel_image_methods", "1Darray CL_UNSIGNED_INT16", "", 1, nil)
	addTest("kernel_image_methods", "1Darray CL_UNSIGNED_INT32", "", 1, nil)
	addTest("kernel_image_methods", "1Darray CL_UNSIGNED_INT8", "", 1, nil)
	addTest("kernel_image_methods", "1D CL_FLOAT", "", 1, nil)
	addTest("kernel_image_methods", "1D CL_HALF_FLOAT", "", 1, nil)
	addTest("kernel_image_methods", "1D CL_SIGNED_INT16", "", 1, nil)
	addTest("kernel_image_methods", "1D CL_SIGNED_INT32", "", 1, nil)
	addTest("kernel_image_methods", "1D CL_SIGNED_INT8", "", 1, nil)
	addTest("kernel_image_methods", "1D CL_SNORM_INT16", "", 1, nil)
	addTest("kernel_image_methods", "1D CL_SNORM_INT8", "", 1, nil)
	addTest("kernel_image_methods", "1D CL_UNORM_INT_101010", "", 1, nil)
	addTest("kernel_image_methods", "1D CL_UNORM_INT16", "", 1, nil)
	addTest("kernel_image_methods", "1D CL_UNORM_INT8", "", 1, nil)
	addTest("kernel_image_methods", "1D CL_UNORM_SHORT_555", "", 1, nil)
	addTest("kernel_image_methods", "1D CL_UNORM_SHORT_565", "", 1, nil)
	addTest("kernel_image_methods", "1D CL_UNSIGNED_INT16", "", 1, nil)
	addTest("kernel_image_methods", "1D CL_UNSIGNED_INT32", "", 1, nil)
	addTest("kernel_image_methods", "1D CL_UNSIGNED_INT8", "", 1, nil)
	addTest("kernel_image_methods", "2Darray CL_FLOAT", "", 1, nil)
	addTest("kernel_image_methods", "2Darray CL_HALF_FLOAT", "", 1, nil)
	addTest("kernel_image_methods", "2Darray CL_SIGNED_INT16", "", 1, nil)
	addTest("kernel_image_methods", "2Darray CL_SIGNED_INT32", "", 1, nil)
	addTest("kernel_image_methods", "2Darray CL_SIGNED_INT8", "", 1, nil)
	addTest("kernel_image_methods", "2Darray CL_SNORM_INT16", "", 1, nil)
	addTest("kernel_image_methods", "2Darray CL_SNORM_INT8", "", 1, nil)
	addTest("kernel_image_methods", "2Darray CL_UNORM_INT_101010", "", 1, nil)
	addTest("kernel_image_methods", "2Darray CL_UNORM_INT16", "", 1, nil)
	addTest("kernel_image_methods", "2Darray CL_UNORM_INT8", "", 1, nil)
	addTest("kernel_image_methods", "2Darray CL_UNORM_SHORT_555", "", 1, nil)
	addTest("kernel_image_methods", "2Darray CL_UNORM_SHORT_565", "", 1, nil)
	addTest("kernel_image_methods", "2Darray CL_UNSIGNED_INT16", "", 1, nil)
	addTest("kernel_image_methods", "2Darray CL_UNSIGNED_INT32", "", 1, nil)
	addTest("kernel_image_methods", "2Darray CL_UNSIGNED_INT8", "", 1, nil)
	addTest("kernel_image_methods", "2D CL_FLOAT", "", 1, nil)
	addTest("kernel_image_methods", "2D CL_HALF_FLOAT", "", 1, nil)
	addTest("kernel_image_methods", "2D CL_SIGNED_INT16", "", 1, nil)
	addTest("kernel_image_methods", "2D CL_SIGNED_INT32", "", 1, nil)
	addTest("kernel_image_methods", "2D CL_SIGNED_INT8", "", 1, nil)
	addTest("kernel_image_methods", "2D CL_SNORM_INT16", "", 1, nil)
	addTest("kernel_image_methods", "2D CL_SNORM_INT8", "", 1, nil)
	addTest("kernel_image_methods", "2D CL_UNORM_INT_101010", "", 1, nil)
	addTest("kernel_image_methods", "2D CL_UNORM_INT16", "", 1, nil)
	addTest("kernel_image_methods", "2D CL_UNORM_INT8", "", 1, nil)
	addTest("kernel_image_methods", "2D CL_UNORM_SHORT_555", "", 1, nil)
	addTest("kernel_image_methods", "2D CL_UNORM_SHORT_565", "", 1, nil)
	addTest("kernel_image_methods", "2D CL_UNSIGNED_INT16", "", 1, nil)
	addTest("kernel_image_methods", "2D CL_UNSIGNED_INT32", "", 1, nil)
	addTest("kernel_image_methods", "2D CL_UNSIGNED_INT8", "", 1, nil)
	addTest("kernel_image_methods", "3D CL_FLOAT", "", 1, nil)
	addTest("kernel_image_methods", "3D CL_HALF_FLOAT", "", 1, nil)
	addTest("kernel_image_methods", "3D CL_SIGNED_INT16", "", 1, nil)
	addTest("kernel_image_methods", "3D CL_SIGNED_INT32", "", 1, nil)
	addTest("kernel_image_methods", "3D CL_SIGNED_INT8", "", 1, nil)
	addTest("kernel_image_methods", "3D CL_SNORM_INT16", "", 1, nil)
	addTest("kernel_image_methods", "3D CL_SNORM_INT8", "", 1, nil)
	addTest("kernel_image_methods", "3D CL_UNORM_INT_101010", "", 1, nil)
	addTest("kernel_image_methods", "3D CL_UNORM_INT16", "", 1, nil)
	addTest("kernel_image_methods", "3D CL_UNORM_INT8", "", 1, nil)
	addTest("kernel_image_methods", "3D CL_UNORM_SHORT_555", "", 1, nil)
	addTest("kernel_image_methods", "3D CL_UNORM_SHORT_565", "", 1, nil)
	addTest("kernel_image_methods", "3D CL_UNSIGNED_INT16", "", 1, nil)
	addTest("kernel_image_methods", "3D CL_UNSIGNED_INT32", "", 1, nil)
	addTest("kernel_image_methods", "3D CL_UNSIGNED_INT8", "", 1, nil)
	addTest("mem_host_flags", "mem_host_no_access_buffer", "", 1, nil)
	addTest("mem_host_flags", "mem_host_no_access_image", "", 1, nil)
	addTest("mem_host_flags", "mem_host_no_access_subbuffer", "", 1, nil)
	addTest("mem_host_flags", "mem_host_read_only_buffer", "", 1, nil)
	addTest("mem_host_flags", "mem_host_read_only_image", "", 1, nil)
	addTest("mem_host_flags", "mem_host_read_only_subbuffer", "", 1, nil)
	addTest("mem_host_flags", "mem_host_write_only_buffer", "", 1, nil)
	addTest("mem_host_flags", "mem_host_write_only_image", "", 1, nil)
	addTest("mem_host_flags", "mem_host_write_only_subbuffer", "", 1, nil)
	addTest("multiples", "context_four_contexts_same_device", "", 1, nil)
	addTest("multiples", "context_multiple_contexts_same_device", "", 20, nil)
	addTest("multiples", "context_three_contexts_same_device", "", 1, nil)
	addTest("multiples", "context_two_contexts_same_device", "", 1, nil)
	addTest("multiples", "hundred_queues", "", 1, nil)
	addTest("multiples", "max_devices", "", 1, nil)
	addTest("multiples", "two_devices", "", 1, nil)
	addTest("profiling", "copy_array", "", 1, nil)
	addTest("profiling", "copy_array_to_image", "", 1, nil)
	addTest("profiling", "copy_image", "", 1, nil)
	addTest("profiling", "copy_partial_array", "", 1, nil)
	addTest("profiling", "execute", "", 1, nil)
	addTest("profiling", "read_array_char", "", 1, nil)
	addTest("profiling", "read_array_float", "", 1, nil)
	addTest("profiling", "read_array_int", "", 1, nil)
	addTest("profiling", "read_array_long", "", 1, nil)
	addTest("profiling", "read_array_short", "", 1, nil)
	addTest("profiling", "read_array_struct", "", 1, nil)
	addTest("profiling", "read_array_uchar", "", 1, nil)
	addTest("profiling", "read_array_uint", "", 1, nil)
	addTest("profiling", "read_array_ulong", "", 1, nil)
	addTest("profiling", "read_array_ushort", "", 1, nil)
	addTest("profiling", "read_image_char", "", 1, nil)
	addTest("profiling", "read_image_float", "", 1, nil)
	addTest("profiling", "read_image_uchar", "", 1, nil)
	addTest("profiling", "write_array_char", "", 1, nil)
	addTest("profiling", "write_array_float", "", 1, nil)
	addTest("profiling", "write_array_int", "", 1, nil)
	addTest("profiling", "write_array_long", "", 1, nil)
	addTest("profiling", "write_array_short", "", 1, nil)
	addTest("profiling", "write_array_struct", "", 1, nil)
	addTest("profiling", "write_array_uchar", "", 1, nil)
	addTest("profiling", "write_array_uint", "", 1, nil)
	addTest("profiling", "write_array_ulong", "", 1, nil)
	addTest("profiling", "write_array_ushort", "", 1, nil)
	addTest("profiling", "write_image_char", "", 1, nil)
	addTest("profiling", "write_image_float", "", 1, nil)
	addTest("profiling", "write_image_uchar", "", 1, nil)
	addTest("relationals", "relational_all", "", 1, nil)
	addTest("relationals", "relational_any", "", 1, nil)
	addTest("relationals", "relational_bitselect", "", 1, nil)
	addTest("relationals", "relational_isequal", "", 1, nil)
	addTest("relationals", "relational_isgreaterequal", "", 1, nil)
	addTest("relationals", "relational_isgreater", "", 1, nil)
	addTest("relationals", "relational_islessequal", "", 1, nil)
	addTest("relationals", "relational_islessgreater", "", 1, nil)
	addTest("relationals", "relational_isless", "", 1, nil)
	addTest("relationals", "relational_isnotequal", "", 1, nil)
	addTest("relationals", "relational_select_signed", "", 1, nil)
	addTest("relationals", "relational_select_unsigned", "", 1, nil)
	addTest("relationals", "shuffle_array_cast", "", 10, nil)
	addTest("relationals", "shuffle_built_in_dual_input", "", 10, nil)
	addTest("relationals", "shuffle_built_in", "", 10, nil)
	addTest("relationals", "shuffle_copy", "", 10, nil)
	addTest("relationals", "shuffle_function_call", "", 10, nil)
	addTest("samplerless_reads", "1Darray CL_FLOAT", "", 1, nil)
	addTest("samplerless_reads", "1Darray CL_HALF_FLOAT", "", 1, nil)
	addTest("samplerless_reads", "1Darray CL_SIGNED_INT16", "", 1, nil)
	addTest("samplerless_reads", "1Darray CL_SIGNED_INT32", "", 1, nil)
	addTest("samplerless_reads", "1Darray CL_SIGNED_INT8", "", 1, nil)
	addTest("samplerless_reads", "1Darray CL_SNORM_INT16", "", 1, nil)
	addTest("samplerless_reads", "1Darray CL_SNORM_INT8", "", 1, nil)
	addTest("samplerless_reads", "1Darray CL_UNORM_INT_101010", "", 1, nil)
	addTest("samplerless_reads", "1Darray CL_UNORM_INT16", "", 1, nil)
	addTest("samplerless_reads", "1Darray CL_UNORM_INT8", "", 1, nil)
	addTest("samplerless_reads", "1Darray CL_UNORM_SHORT_555", "", 1, nil)
	addTest("samplerless_reads", "1Darray CL_UNORM_SHORT_565", "", 1, nil)
	addTest("samplerless_reads", "1Darray CL_UNSIGNED_INT16", "", 1, nil)
	addTest("samplerless_reads", "1Darray CL_UNSIGNED_INT32", "", 1, nil)
	addTest("samplerless_reads", "1Darray CL_UNSIGNED_INT8", "", 1, nil)
	addTest("samplerless_reads", "1D CL_FLOAT", "", 1, nil)
	addTest("samplerless_reads", "1D CL_HALF_FLOAT", "", 1, nil)
	addTest("samplerless_reads", "1D CL_SIGNED_INT16", "", 1, nil)
	addTest("samplerless_reads", "1D CL_SIGNED_INT32", "", 1, nil)
	addTest("samplerless_reads", "1D CL_SIGNED_INT8", "", 1, nil)
	addTest("samplerless_reads", "1D CL_SNORM_INT16", "", 1, nil)
	addTest("samplerless_reads", "1D CL_SNORM_INT8", "", 1, nil)
	addTest("samplerless_reads", "1D CL_UNORM_INT_101010", "", 1, nil)
	addTest("samplerless_reads", "1D CL_UNORM_INT16", "", 1, nil)
	addTest("samplerless_reads", "1D CL_UNORM_INT8", "", 1, nil)
	addTest("samplerless_reads", "1D CL_UNORM_SHORT_555", "", 1, nil)
	addTest("samplerless_reads", "1D CL_UNORM_SHORT_565", "", 1, nil)
	addTest("samplerless_reads", "1D CL_UNSIGNED_INT16", "", 1, nil)
	addTest("samplerless_reads", "1D CL_UNSIGNED_INT32", "", 1, nil)
	addTest("samplerless_reads", "1D CL_UNSIGNED_INT8", "", 1, nil)
	addTest("samplerless_reads", "2Darray CL_FLOAT", "", 1, nil)
	addTest("samplerless_reads", "2Darray CL_HALF_FLOAT", "", 1, nil)
	addTest("samplerless_reads", "2Darray CL_SIGNED_INT16", "", 1, nil)
	addTest("samplerless_reads", "2Darray CL_SIGNED_INT32", "", 1, nil)
	addTest("samplerless_reads", "2Darray CL_SIGNED_INT8", "", 1, nil)
	addTest("samplerless_reads", "2Darray CL_SNORM_INT16", "", 1, nil)
	addTest("samplerless_reads", "2Darray CL_SNORM_INT8", "", 1, nil)
	addTest("samplerless_reads", "2Darray CL_UNORM_INT_101010", "", 1, nil)
	addTest("samplerless_reads", "2Darray CL_UNORM_INT16", "", 1, nil)
	addTest("samplerless_reads", "2Darray CL_UNORM_INT8", "", 1, nil)
	addTest("samplerless_reads", "2Darray CL_UNORM_SHORT_555", "", 1, nil)
	addTest("samplerless_reads", "2Darray CL_UNORM_SHORT_565", "", 1, nil)
	addTest("samplerless_reads", "2Darray CL_UNSIGNED_INT16", "", 1, nil)
	addTest("samplerless_reads", "2Darray CL_UNSIGNED_INT32", "", 1, nil)
	addTest("samplerless_reads", "2Darray CL_UNSIGNED_INT8", "", 1, nil)
	addTest("samplerless_reads", "2D CL_FLOAT", "", 1, nil)
	addTest("samplerless_reads", "2D CL_HALF_FLOAT", "", 1, nil)
	addTest("samplerless_reads", "2D CL_SIGNED_INT16", "", 1, nil)
	addTest("samplerless_reads", "2D CL_SIGNED_INT32", "", 1, nil)
	addTest("samplerless_reads", "2D CL_SIGNED_INT8", "", 1, nil)
	addTest("samplerless_reads", "2D CL_SNORM_INT16", "", 1, nil)
	addTest("samplerless_reads", "2D CL_SNORM_INT8", "", 1, nil)
	addTest("samplerless_reads", "2D CL_UNORM_INT_101010", "", 1, nil)
	addTest("samplerless_reads", "2D CL_UNORM_INT16", "", 1, nil)
	addTest("samplerless_reads", "2D CL_UNORM_INT8", "", 1, nil)
	addTest("samplerless_reads", "2D CL_UNORM_SHORT_555", "", 1, nil)
	addTest("samplerless_reads", "2D CL_UNORM_SHORT_565", "", 1, nil)
	addTest("samplerless_reads", "2D CL_UNSIGNED_INT16", "", 1, nil)
	addTest("samplerless_reads", "2D CL_UNSIGNED_INT32", "", 1, nil)
	addTest("samplerless_reads", "2D CL_UNSIGNED_INT8", "", 1, nil)
	addTest("samplerless_reads", "3D CL_FLOAT", "", 1, nil)
	addTest("samplerless_reads", "3D CL_HALF_FLOAT", "", 1, nil)
	addTest("samplerless_reads", "3D CL_SIGNED_INT16", "", 1, nil)
	addTest("samplerless_reads", "3D CL_SIGNED_INT32", "", 1, nil)
	addTest("samplerless_reads", "3D CL_SIGNED_INT8", "", 1, nil)
	addTest("samplerless_reads", "3D CL_SNORM_INT16", "", 1, nil)
	addTest("samplerless_reads", "3D CL_SNORM_INT8", "", 1, nil)
	addTest("samplerless_reads", "3D CL_UNORM_INT_101010", "", 1, nil)
	addTest("samplerless_reads", "3D CL_UNORM_INT16", "", 1, nil)
	addTest("samplerless_reads", "3D CL_UNORM_INT8", "", 1, nil)
	addTest("samplerless_reads", "3D CL_UNORM_SHORT_555", "", 1, nil)
	addTest("samplerless_reads", "3D CL_UNORM_SHORT_565", "", 1, nil)
	addTest("samplerless_reads", "3D CL_UNSIGNED_INT16", "", 1, nil)
	addTest("samplerless_reads", "3D CL_UNSIGNED_INT32", "", 1, nil)
	addTest("samplerless_reads", "3D CL_UNSIGNED_INT8", "", 1, nil)
	addTest("select", "select_char_char", "-w", 1, nil)
	addTest("select", "select_char_uchar", "-w", 1, nil)
	addTest("select", "select_double_long", "-w", 1, nil)
	addTest("select", "select_double_ulong", "-w", 1, nil)
	addTest("select", "select_float_int", "-w", 1, nil)
	addTest("select", "select_float_uint", "-w", 1, nil)
	addTest("select", "select_int_int", "-w", 1, nil)
	addTest("select", "select_int_uint", "-w", 1, nil)
	addTest("select", "select_long_long", "-w", 1, nil)
	addTest("select", "select_long_ulong", "-w", 1, nil)
	addTest("select", "select_short_short", "-w", 1, nil)
	addTest("select", "select_short_ushort", "-w", 1, nil)
	addTest("select", "select_uchar_char", "-w", 1, nil)
	addTest("select", "select_uchar_uchar", "-w", 1, nil)
	addTest("select", "select_uint_int", "-w", 1, nil)
	addTest("select", "select_uint_uint", "-w", 1, nil)
	addTest("select", "select_ulong_long", "-w", 1, nil)
	addTest("select", "select_ulong_ulong", "-w", 1, nil)
	addTest("select", "select_ushort_short", "-w", 1, nil)
	addTest("select", "select_ushort_ushort", "-w", 1, nil)
	addTest("thread_dimensions", "full_1d_explicit_local", "", 1, nil)
	addTest("thread_dimensions", "full_1d_implicit_local", "", 1, nil)
	addTest("thread_dimensions", "full_2d_explicit_local", "", 10, nil)
	addTest("thread_dimensions", "full_2d_implicit_local", "", 10, nil)
	addTest("thread_dimensions", "full_3d_explicit_local", "", 20, nil)
	addTest("thread_dimensions", "full_3d_implicit_local", "", 10, nil)
	addTest("thread_dimensions", "quick_1d_explicit_local", "", 1, nil)
	addTest("thread_dimensions", "quick_1d_implicit_local", "", 1, nil)
	addTest("thread_dimensions", "quick_2d_explicit_local", "", 1, nil)
	addTest("thread_dimensions", "quick_2d_implicit_local", "", 1, nil)
	addTest("thread_dimensions", "quick_3d_explicit_local", "", 1, nil)
	addTest("thread_dimensions", "quick_3d_implicit_local", "", 1, nil)
	addTest("vectors", "step_typedef_type", "", 1, nil)
	addTest("vectors", "step_typedef_var", "", 1, nil)
	addTest("vectors", "step_type", "", 1, nil)
	addTest("vectors", "step_var", "", 1, nil)
	addTest("vectors", "vec_align_array", "", 1, nil)
	addTest("vectors", "vec_align_packed_struct_arr", "", 1, nil)
	addTest("vectors", "vec_align_packed_struct", "", 1, nil)
	addTest("vectors", "vec_align_struct_arr", "", 1, nil)
	addTest("vectors", "vec_align_struct", "", 1, nil)

	code := genparams.Template(t, `{{ range . }}{
        Name: "{{ .Name }}",
        Val: oclctsTest{
            executable: "{{ .Executable }}",
            args: "{{ .Args }}",
        },
        {{ if .ExtraAttr }}
        ExtraAttr: {{ .ExtraAttr | fmt }},
        {{ end }}
        Timeout: {{ .Timeout }} * time.Minute,
    },
    {{ end }}`, oclCtsParams)
	genparams.Ensure(t, "opencl_cts.go", code)
}
