// Copyright 2020 The ChromiumOS Authors
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

package crostini

import (
	"context"
	"fmt"
	"time"

	"chromiumos/tast/ctxutil"
	"chromiumos/tast/errors"
	"chromiumos/tast/local/chrome"
	"chromiumos/tast/local/chrome/uiauto"
	"chromiumos/tast/local/chrome/uiauto/nodewith"
	"chromiumos/tast/local/chrome/uiauto/role"
	"chromiumos/tast/local/coords"
	"chromiumos/tast/local/crostini"
	"chromiumos/tast/local/crostini/ui/terminalapp"
	"chromiumos/tast/local/input"
	"chromiumos/tast/local/screenshot"
	"chromiumos/tast/local/vm"
	"chromiumos/tast/testing"
)

func init() {
	testing.AddTest(&testing.Test{
		Func:         AppEmacs,
		LacrosStatus: testing.LacrosVariantUnneeded,
		Desc:         "Opens Emacs from terminal and does some edits via keyboard",
		Contacts:     []string{"clumptini+oncall@google.com"},
		Attr:         []string{"group:mainline"},
		Vars:         screenshot.ScreenDiffVars,
		SoftwareDeps: []string{"chrome", "vm_host", "amd64"},
		Params: []testing.Param{
			// Parameters generated by params_test.go. DO NOT EDIT.
			{
				Name:              "tablet_stable",
				ExtraAttr:         []string{"informational"},
				ExtraSoftwareDeps: []string{"dlc"},
				ExtraHardwareDeps: crostini.CrostiniAppStable,
				Fixture:           "crostiniBusterLargeContainerTablet",
				Timeout:           15 * time.Minute,
			}, {
				Name:              "tablet_unstable",
				ExtraAttr:         []string{"informational"},
				ExtraSoftwareDeps: []string{"dlc"},
				ExtraHardwareDeps: crostini.CrostiniAppUnstable,
				Fixture:           "crostiniBusterLargeContainerTablet",
				Timeout:           15 * time.Minute,
			}, {
				Name:              "bullseye_tablet_stable",
				ExtraAttr:         []string{"informational"},
				ExtraSoftwareDeps: []string{"dlc"},
				ExtraHardwareDeps: crostini.CrostiniAppStable,
				Fixture:           "crostiniBullseyeLargeContainerTablet",
				Timeout:           15 * time.Minute,
			}, {
				Name:              "bullseye_tablet_unstable",
				ExtraAttr:         []string{"informational"},
				ExtraSoftwareDeps: []string{"dlc"},
				ExtraHardwareDeps: crostini.CrostiniAppUnstable,
				Fixture:           "crostiniBullseyeLargeContainerTablet",
				Timeout:           15 * time.Minute,
			}, {
				Name:              "clamshell_stable",
				ExtraSoftwareDeps: []string{"dlc"},
				ExtraHardwareDeps: crostini.CrostiniAppStable,
				Fixture:           "crostiniBusterLargeContainerClamshell",
				Timeout:           15 * time.Minute,
			}, {
				Name:              "clamshell_unstable",
				ExtraAttr:         []string{"informational"},
				ExtraSoftwareDeps: []string{"dlc"},
				ExtraHardwareDeps: crostini.CrostiniAppUnstable,
				Fixture:           "crostiniBusterLargeContainerClamshell",
				Timeout:           15 * time.Minute,
			}, {
				Name:              "bullseye_clamshell_stable",
				ExtraAttr:         []string{"informational"},
				ExtraSoftwareDeps: []string{"dlc"},
				ExtraHardwareDeps: crostini.CrostiniAppStable,
				Fixture:           "crostiniBullseyeLargeContainerClamshell",
				Timeout:           15 * time.Minute,
			}, {
				Name:              "bullseye_clamshell_unstable",
				ExtraAttr:         []string{"informational"},
				ExtraSoftwareDeps: []string{"dlc"},
				ExtraHardwareDeps: crostini.CrostiniAppUnstable,
				Fixture:           "crostiniBullseyeLargeContainerClamshell",
				Timeout:           15 * time.Minute,
			},
		},
	})
}
func AppEmacs(ctx context.Context, s *testing.State) {
	tconn := s.FixtValue().(crostini.FixtureData).Tconn
	keyboard := s.FixtValue().(crostini.FixtureData).KB
	cont := s.FixtValue().(crostini.FixtureData).Cont
	d := s.FixtValue().(crostini.FixtureData).Differ()

	// Use a shortened context for test operations to reserve time for cleanup.
	cleanupCtx := ctx
	ctx, cancel := ctxutil.Shorten(ctx, 5*time.Second)
	defer cancel()

	// Open Terminal app.
	terminalApp, err := terminalapp.Launch(ctx, tconn)
	if err != nil {
		s.Fatal("Failed to open Terminal app: ", err)
	}

	defer terminalApp.Exit(keyboard)(cleanupCtx)

	if err := createFileWithEmacs(ctx, keyboard, terminalApp, tconn, cont, d); err != nil {
		s.Fatal("Failed to create file with emacs in Terminal: ", err)
	}
}

// createFileWithEmacs creates a file with emacs and types a string into it and save it in container.
func createFileWithEmacs(ctx context.Context, keyboard *input.KeyboardEventWriter, terminalApp *terminalapp.TerminalApp, tconn *chrome.TestConn, cont *vm.Container, d screenshot.Differ) error {
	const (
		testFile   = "test.txt"
		testString = "This is a test string"
	)

	// Anything animated like blinking cursors will break screendiffs.
	cont.WriteFile(ctx, "~/.emacs", "(blink-cursor-mode 0)")

	// Open emacs in Terminal.
	// Avoid opening the splash screen since it means the screenshot will contain data like CPU architecture,
	// which is terrible for screen diffing.
	if err := terminalApp.RunCommand(keyboard, fmt.Sprintf("emacs --no-splash %s", testFile))(ctx); err != nil {
		return errors.Wrap(err, "failed to run command 'emacs' in Terminal window")
	}

	ui := uiauto.New(tconn)
	window := nodewith.Name("emacs@penguin").Role(role.Window).First()
	// Left click left-top of the emacs window.
	loc, err := ui.Location(ctx, window)
	if err != nil {
		return errors.Wrap(err, "failed to get the location of Emacs window")
	}

	if err := uiauto.Combine("Click, input, save and exit Emacs",
		// Click left top to focus on the input area.
		ui.MouseClickAtLocation(0, coords.Point{X: loc.Left, Y: loc.Top}),
		// Type string.
		keyboard.TypeAction(testString),
		// Press ctrl+x and ctrl+s to save.
		keyboard.AccelAction("ctrl+X"),
		keyboard.AccelAction("ctrl+S"),
		// After saving, wait for the "save" button to grey out.
		d.DiffWindow(ctx, "emacs", screenshot.Retries(2)),
		// Press ctrl+x and ctrl+c to and quit.
		keyboard.AccelAction("ctrl+X"),
		keyboard.AccelAction("ctrl+C"),
		// Check window closed.
		ui.WaitUntilGone(window))(ctx); err != nil {
		return err
	}

	// Check the content of the test file.
	if err := cont.CheckFileContent(ctx, testFile, testString+"\n"); err != nil {
		return errors.Wrap(err, "failed to verify the content of the file")
	}
	return nil
}
