// Copyright 2022 The ChromiumOS Authors
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

package crostini

import (
	"context"
	"regexp"
	"time"

	"chromiumos/tast/common/testexec"
	"chromiumos/tast/ctxutil"
	"chromiumos/tast/local/chrome/uiauto"
	"chromiumos/tast/local/chrome/uiauto/faillog"
	"chromiumos/tast/local/chrome/uiauto/launcher"
	"chromiumos/tast/local/chrome/uiauto/nodewith"
	"chromiumos/tast/local/chrome/uiauto/role"
	"chromiumos/tast/local/crostini"
	"chromiumos/tast/local/crostini/ui/terminalapp"
	"chromiumos/tast/local/screenshot"
	"chromiumos/tast/local/uidetection"
	"chromiumos/tast/testing"
)

func init() {
	testing.AddTest(&testing.Test{
		Func:         AppGeditInstallUninstall,
		LacrosStatus: testing.LacrosVariantUnneeded,
		Desc:         "Install Gedit, check rendering, icons, saving and uninstall behavior",
		Contacts:     []string{"alvinjia@google.com", "clumptini@google.com"},
		Attr:         []string{"group:mainline", "informational"},
		Vars:         screenshot.ScreenDiffVars,
		SoftwareDeps: []string{"chrome", "vm_host"},
		Params: []testing.Param{
			// Parameters generated by params_test.go. DO NOT EDIT.
			{
				Name:              "buster_stable",
				ExtraSoftwareDeps: []string{"dlc"},
				ExtraHardwareDeps: crostini.CrostiniStable,
				Fixture:           "crostiniBuster",
				Timeout:           12 * time.Minute,
			}, {
				Name:              "buster_unstable",
				ExtraAttr:         []string{"informational"},
				ExtraSoftwareDeps: []string{"dlc"},
				ExtraHardwareDeps: crostini.CrostiniUnstable,
				Fixture:           "crostiniBuster",
				Timeout:           12 * time.Minute,
			}, {
				Name:              "bullseye_stable",
				ExtraSoftwareDeps: []string{"dlc"},
				ExtraHardwareDeps: crostini.CrostiniStable,
				Fixture:           "crostiniBullseye",
				Timeout:           12 * time.Minute,
			}, {
				Name:              "bullseye_unstable",
				ExtraAttr:         []string{"informational"},
				ExtraSoftwareDeps: []string{"dlc"},
				ExtraHardwareDeps: crostini.CrostiniUnstable,
				Fixture:           "crostiniBullseye",
				Timeout:           12 * time.Minute,
			},
		},
	})
}
func AppGeditInstallUninstall(ctx context.Context, s *testing.State) {
	tconn := s.FixtValue().(crostini.FixtureData).Tconn
	keyboard := s.FixtValue().(crostini.FixtureData).KB
	cont := s.FixtValue().(crostini.FixtureData).Cont

	// Use a shortened context for test operations to reserve time for cleanup.
	cleanupCtx := ctx
	ctx, cancel := ctxutil.Shorten(ctx, 5*time.Second)
	defer cancel()
	defer faillog.DumpUITreeOnError(cleanupCtx, s.OutDir(), s.HasError, tconn)

	// Install Gedit.
	s.Log("Installing Gedit")
	if err := cont.Command(ctx, "sudo", "apt-get", "update").Run(testexec.DumpLogOnError); err != nil {
		s.Fatal("Failed to run apt-update: ", err)
	}
	if err := cont.Command(ctx, "sudo", "apt-get", "-y", "install", "gedit").Run(testexec.DumpLogOnError); err != nil {
		s.Fatal("Failed to install Gedit: ", err)
	}

	// Launch and test Gedit.
	s.Log("Launching Gedit from launcher")
	if err := launcher.SearchAndLaunchWithQuery(tconn, keyboard, "t", "Text Editor")(ctx); err != nil {
		s.Fatal("Failed to launch gedit: ", err)
	}

	ud := uidetection.NewDefault(tconn)
	ui := uiauto.New(tconn)
	geditWindow := nodewith.NameRegex(regexp.MustCompile(`.* - gedit`)).Role(role.Window).First()
	if err := uiauto.Combine("wait for gedit window to appear",
		ui.WaitUntilExists(geditWindow),
		ud.WaitUntilExists(uidetection.Word("Open").WithinA11yNode(geditWindow)),
	)(ctx); err != nil {
		s.Fatal("Failed to find Gedit window: ", err)
	}

	geditSaveAsWindow := nodewith.Name("Save As").Role(role.Window).First()
	if err := uiauto.Combine("edit file and save",
		keyboard.TypeAction("Hello, gedit!"),
		keyboard.AccelAction("ctrl+S"), // Bring up the save window
		ud.LeftClick(uidetection.Word("Save").WithinA11yNode(geditSaveAsWindow)),
		// Press ctrl+W twice to exit window.
		keyboard.AccelAction("ctrl+W"),
		keyboard.AccelAction("ctrl+W"),
	)(ctx); err != nil {
		s.Fatal("Failed to edit and save the Gedit file: ", err)
	}

	s.Log("Uninstall Gedit from Terminal")
	ta, err := terminalapp.Launch(ctx, tconn)
	if err != nil {
		s.Fatal("Failed to launch terminal: ", err)
	}

	if err = ta.RunCommand(keyboard, "sudo apt-get -y remove gedit")(ctx); err != nil {
		s.Fatal("Failed to run command in Terminal window: ", err)
	}

	// Close terminal.
	if err := uiauto.Combine("close Terminal window",
		ta.WaitForPrompt(), // Wait until Gedit uninstall streams finish printing.
		ta.Exit(keyboard),
	)(ctx); err != nil {
		s.Fatal("Failed to close terminal: ", err)
	}
}
