// Copyright 2020 The Chromium OS Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

package crostini

import (
	"context"
	"time"

	"chromiumos/tast/local/chrome/uiauto"
	"chromiumos/tast/local/crostini"
	"chromiumos/tast/local/crostini/ui/settings"
	"chromiumos/tast/local/vm"
	"chromiumos/tast/testing"
)

func init() {
	testing.AddTest(&testing.Test{
		Func:         ResizeCancel,
		LacrosStatus: testing.LacrosVariantUnneeded,
		Desc:         "Test cancelling resizing of Crostini from the Settings app",
		Contacts:     []string{"jinrongwu@google.com", "cros-containers-dev@google.com"},
		Attr:         []string{"group:mainline", "informational"},
		SoftwareDeps: []string{"chrome", "vm_host"},
		Vars:         []string{"keepState", "ui.gaiaPoolDefault"},
		Params: []testing.Param{
			// Parameters generated by params_test.go. DO NOT EDIT.
			{
				Name:              "buster_stable",
				ExtraSoftwareDeps: []string{"dlc"},
				ExtraHardwareDeps: crostini.CrostiniStable,
				Fixture:           "crostiniBuster",
				Timeout:           7 * time.Minute,
			}, {
				Name:              "buster_unstable",
				ExtraAttr:         []string{"informational"},
				ExtraSoftwareDeps: []string{"dlc"},
				ExtraHardwareDeps: crostini.CrostiniUnstable,
				Fixture:           "crostiniBuster",
				Timeout:           7 * time.Minute,
			}, {
				Name:              "bullseye_stable",
				ExtraSoftwareDeps: []string{"dlc"},
				ExtraHardwareDeps: crostini.CrostiniStable,
				Fixture:           "crostiniBullseye",
				Timeout:           7 * time.Minute,
			}, {
				Name:              "bullseye_unstable",
				ExtraAttr:         []string{"informational"},
				ExtraSoftwareDeps: []string{"dlc"},
				ExtraHardwareDeps: crostini.CrostiniUnstable,
				Fixture:           "crostiniBullseye",
				Timeout:           7 * time.Minute,
			},
		},
	})
}

func ResizeCancel(ctx context.Context, s *testing.State) {
	pre := s.FixtValue().(crostini.FixtureData)
	tconn := pre.Tconn
	cr := s.FixtValue().(crostini.FixtureData).ParentFixtV.Chrome()

	// Open the Linux settings.
	st, err := settings.OpenLinuxSettings(ctx, tconn, cr)
	if err != nil {
		s.Fatal("Failed to open Linux Settings: ", err)
	}

	disk, err := pre.Cont.VM.Concierge.GetVMDiskInfo(ctx, vm.DefaultVMName)
	if err != nil {
		s.Fatal("Failed to get VM disk info: ", err)
	}
	originalContDS := disk.GetSize()

	originalDSOnSettings, err := st.GetDiskSize(ctx)
	if err != nil {
		s.Fatal("Failed to get the disk size from the Settings app: ", err)
	}

	// Click Resize on Linux settings page.
	ui := uiauto.New(tconn)
	if err := uiauto.Combine("open Resize dialog and click button Cancel",
		st.ClickChange(),
		ui.LeftClick(settings.ResizeDiskDialog.Cancel),
		// TODO (crbug/1232877): remove this line when crbug/1232877 is resolved.
		tconn.ResetAutomation,
		ui.WaitUntilGone(settings.ResizeDiskDialog.Self))(ctx); err != nil {
		s.Fatal("Failed to cancel resize: ", err)
	}

	newDSOnSettings, err := st.GetDiskSize(ctx)
	if err != nil {
		s.Fatal("Failed to get the disk size from the Settings app after cancelling resizing: ", err)
	}

	disk, err = pre.Cont.VM.Concierge.GetVMDiskInfo(ctx, vm.DefaultVMName)
	if err != nil {
		s.Fatal("Failed to get VM disk info after cancelling resizing: ", err)
	}

	newContDS := disk.GetSize()
	if originalContDS != newContDS {
		s.Fatalf("Failed to verify disk size of Crostini after cancelling resizing, got %d, want %d", newContDS, originalContDS)
	}
	if originalDSOnSettings != newDSOnSettings {
		s.Fatalf("Failed to verify disk size on the Settings app after cancelling resizing, got %s, want %s", newDSOnSettings, originalDSOnSettings)
	}
}
