// Copyright 2021 The Chromium OS Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

// This file is generated by `tools/generate_automation2_constants.py`.

// Package checked describes tri-state values of a checkbox or radio button.
package checked

// Checked describes tri-state values of a checkbox or radio button.
type Checked string

// As defined in https://chromium.googlesource.com/chromium/src/+/refs/heads/master/extensions/common/api/automation.idl
const (
	True  Checked = "true"
	False Checked = "false"
	Mixed Checked = "mixed"
)
