// Code generated by protoc-gen-go. DO NOT EDIT.
// source: suspend_remote_service.proto

package arc

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	empty "github.com/golang/protobuf/ptypes/empty"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ClockValues struct {
	ClockMonotonicNs     int64    `protobuf:"varint,1,opt,name=clock_monotonic_ns,json=clockMonotonicNs,proto3" json:"clock_monotonic_ns,omitempty"`
	ClockBoottimeNs      int64    `protobuf:"varint,2,opt,name=clock_boottime_ns,json=clockBoottimeNs,proto3" json:"clock_boottime_ns,omitempty"`
	Tsc                  int64    `protobuf:"varint,3,opt,name=tsc,proto3" json:"tsc,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ClockValues) Reset()         { *m = ClockValues{} }
func (m *ClockValues) String() string { return proto.CompactTextString(m) }
func (*ClockValues) ProtoMessage()    {}
func (*ClockValues) Descriptor() ([]byte, []int) {
	return fileDescriptor_06cb3a5472d545a8, []int{0}
}

func (m *ClockValues) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ClockValues.Unmarshal(m, b)
}
func (m *ClockValues) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ClockValues.Marshal(b, m, deterministic)
}
func (m *ClockValues) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ClockValues.Merge(m, src)
}
func (m *ClockValues) XXX_Size() int {
	return xxx_messageInfo_ClockValues.Size(m)
}
func (m *ClockValues) XXX_DiscardUnknown() {
	xxx_messageInfo_ClockValues.DiscardUnknown(m)
}

var xxx_messageInfo_ClockValues proto.InternalMessageInfo

func (m *ClockValues) GetClockMonotonicNs() int64 {
	if m != nil {
		return m.ClockMonotonicNs
	}
	return 0
}

func (m *ClockValues) GetClockBoottimeNs() int64 {
	if m != nil {
		return m.ClockBoottimeNs
	}
	return 0
}

func (m *ClockValues) GetTsc() int64 {
	if m != nil {
		return m.Tsc
	}
	return 0
}

type GetClockValuesResponse struct {
	Host                 *ClockValues `protobuf:"bytes,1,opt,name=host,proto3" json:"host,omitempty"`
	Arc                  *ClockValues `protobuf:"bytes,2,opt,name=arc,proto3" json:"arc,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *GetClockValuesResponse) Reset()         { *m = GetClockValuesResponse{} }
func (m *GetClockValuesResponse) String() string { return proto.CompactTextString(m) }
func (*GetClockValuesResponse) ProtoMessage()    {}
func (*GetClockValuesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_06cb3a5472d545a8, []int{1}
}

func (m *GetClockValuesResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetClockValuesResponse.Unmarshal(m, b)
}
func (m *GetClockValuesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetClockValuesResponse.Marshal(b, m, deterministic)
}
func (m *GetClockValuesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetClockValuesResponse.Merge(m, src)
}
func (m *GetClockValuesResponse) XXX_Size() int {
	return xxx_messageInfo_GetClockValuesResponse.Size(m)
}
func (m *GetClockValuesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetClockValuesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetClockValuesResponse proto.InternalMessageInfo

func (m *GetClockValuesResponse) GetHost() *ClockValues {
	if m != nil {
		return m.Host
	}
	return nil
}

func (m *GetClockValuesResponse) GetArc() *ClockValues {
	if m != nil {
		return m.Arc
	}
	return nil
}

type SuspendRemoteServiceParams struct {
	ReadClocksPathInArc  string   `protobuf:"bytes,1,opt,name=read_clocks_path_in_arc,json=readClocksPathInArc,proto3" json:"read_clocks_path_in_arc,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SuspendRemoteServiceParams) Reset()         { *m = SuspendRemoteServiceParams{} }
func (m *SuspendRemoteServiceParams) String() string { return proto.CompactTextString(m) }
func (*SuspendRemoteServiceParams) ProtoMessage()    {}
func (*SuspendRemoteServiceParams) Descriptor() ([]byte, []int) {
	return fileDescriptor_06cb3a5472d545a8, []int{2}
}

func (m *SuspendRemoteServiceParams) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SuspendRemoteServiceParams.Unmarshal(m, b)
}
func (m *SuspendRemoteServiceParams) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SuspendRemoteServiceParams.Marshal(b, m, deterministic)
}
func (m *SuspendRemoteServiceParams) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SuspendRemoteServiceParams.Merge(m, src)
}
func (m *SuspendRemoteServiceParams) XXX_Size() int {
	return xxx_messageInfo_SuspendRemoteServiceParams.Size(m)
}
func (m *SuspendRemoteServiceParams) XXX_DiscardUnknown() {
	xxx_messageInfo_SuspendRemoteServiceParams.DiscardUnknown(m)
}

var xxx_messageInfo_SuspendRemoteServiceParams proto.InternalMessageInfo

func (m *SuspendRemoteServiceParams) GetReadClocksPathInArc() string {
	if m != nil {
		return m.ReadClocksPathInArc
	}
	return ""
}

func init() {
	proto.RegisterType((*ClockValues)(nil), "tast.cros.arc.ClockValues")
	proto.RegisterType((*GetClockValuesResponse)(nil), "tast.cros.arc.GetClockValuesResponse")
	proto.RegisterType((*SuspendRemoteServiceParams)(nil), "tast.cros.arc.SuspendRemoteServiceParams")
}

func init() { proto.RegisterFile("suspend_remote_service.proto", fileDescriptor_06cb3a5472d545a8) }

var fileDescriptor_06cb3a5472d545a8 = []byte{
	// 362 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x92, 0x51, 0x4b, 0xe3, 0x40,
	0x10, 0xc7, 0xdb, 0xcb, 0x71, 0xc7, 0x6d, 0xb9, 0xbb, 0xde, 0xde, 0xd1, 0x2b, 0xd1, 0x07, 0x8d,
	0x08, 0x2a, 0x65, 0x03, 0xd5, 0x2f, 0x60, 0x45, 0xc4, 0x07, 0x4b, 0x49, 0xc1, 0x07, 0x5f, 0x96,
	0xed, 0x76, 0x6c, 0x82, 0x4d, 0x26, 0xec, 0x6c, 0x0a, 0xfd, 0x8e, 0x7e, 0x28, 0xd9, 0x4d, 0x0b,
	0x6d, 0xa9, 0xe2, 0x5b, 0x92, 0xff, 0x6f, 0x66, 0xfe, 0xf3, 0x9f, 0xb0, 0x43, 0xaa, 0xa8, 0x84,
	0x62, 0x2a, 0x0d, 0xe4, 0x68, 0x41, 0x12, 0x98, 0x45, 0xa6, 0x41, 0x94, 0x06, 0x2d, 0xf2, 0x9f,
	0x56, 0x91, 0x15, 0xda, 0x20, 0x09, 0x65, 0x74, 0x78, 0x30, 0x43, 0x9c, 0xcd, 0x21, 0xf6, 0xe2,
	0xa4, 0x7a, 0x8e, 0x21, 0x2f, 0xed, 0xb2, 0x66, 0xa3, 0x25, 0x6b, 0xdd, 0xcc, 0x51, 0xbf, 0x3c,
	0xaa, 0x79, 0x05, 0xc4, 0x7b, 0x8c, 0x6b, 0xf7, 0x2a, 0x73, 0x2c, 0xd0, 0x62, 0x91, 0x69, 0x59,
	0x50, 0xb7, 0x79, 0xd4, 0x3c, 0x0b, 0x92, 0xb6, 0x57, 0x1e, 0xd6, 0xc2, 0x90, 0xf8, 0x05, 0xfb,
	0x53, 0xd3, 0x13, 0x44, 0x6b, 0xb3, 0x1c, 0x1c, 0xfc, 0xc5, 0xc3, 0xbf, 0xbd, 0x30, 0x58, 0x7d,
	0x1f, 0x12, 0x6f, 0xb3, 0xc0, 0x92, 0xee, 0x06, 0x5e, 0x75, 0x8f, 0xd1, 0x82, 0x75, 0xee, 0xc0,
	0x6e, 0x4c, 0x4f, 0x80, 0x4a, 0x2c, 0x08, 0xb8, 0x60, 0x5f, 0x53, 0x24, 0xeb, 0xe7, 0xb6, 0xfa,
	0xa1, 0xd8, 0xda, 0x47, 0x6c, 0x56, 0x78, 0x8e, 0xf7, 0x58, 0xa0, 0x8c, 0xf6, 0x93, 0x3f, 0xc6,
	0x1d, 0x16, 0x25, 0x2c, 0x1c, 0xd7, 0xf1, 0x25, 0x3e, 0xbd, 0x71, 0x1d, 0xde, 0x48, 0x19, 0x95,
	0x13, 0xbf, 0x62, 0xff, 0x0d, 0xa8, 0xa9, 0xf4, 0xfe, 0x49, 0x96, 0xca, 0xa6, 0x32, 0x2b, 0xa4,
	0xeb, 0xef, 0xec, 0xfc, 0x48, 0xfe, 0x3a, 0xd9, 0x37, 0xa5, 0x91, 0xb2, 0xe9, 0x7d, 0x71, 0x6d,
	0x74, 0xff, 0xb5, 0xc9, 0xfe, 0xed, 0x6b, 0xca, 0x87, 0xec, 0xfb, 0xc8, 0x40, 0xa9, 0x0c, 0xf0,
	0x8e, 0xa8, 0x0f, 0x21, 0xd6, 0x87, 0x10, 0xb7, 0xee, 0x10, 0xe1, 0xf9, 0x8e, 0xe1, 0xf7, 0xcd,
	0x45, 0x0d, 0x3e, 0x65, 0xbf, 0xb6, 0x43, 0xe3, 0x9f, 0x2f, 0x0f, 0x4f, 0x77, 0xd0, 0xfd, 0xf1,
	0x47, 0x8d, 0xc1, 0xc9, 0xd3, 0xb1, 0x4e, 0x0d, 0xe6, 0x59, 0x95, 0x23, 0xc5, 0xae, 0x28, 0x5e,
	0xfd, 0x62, 0x14, 0xbb, 0xea, 0x58, 0x19, 0x3d, 0xf9, 0xe6, 0xf7, 0xb8, 0x7c, 0x0b, 0x00, 0x00,
	0xff, 0xff, 0x02, 0x1e, 0x63, 0x79, 0x8d, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// SuspendRemoteServiceClient is the client API for SuspendRemoteService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type SuspendRemoteServiceClient interface {
	// Prepare to prepare the device for reading clocks and suspend
	Prepare(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*SuspendRemoteServiceParams, error)
	// GetPerfValues signs in to DUT and measures Android boot performance metrics.
	GetClockValues(ctx context.Context, in *SuspendRemoteServiceParams, opts ...grpc.CallOption) (*GetClockValuesResponse, error)
}

type suspendRemoteServiceClient struct {
	cc *grpc.ClientConn
}

func NewSuspendRemoteServiceClient(cc *grpc.ClientConn) SuspendRemoteServiceClient {
	return &suspendRemoteServiceClient{cc}
}

func (c *suspendRemoteServiceClient) Prepare(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*SuspendRemoteServiceParams, error) {
	out := new(SuspendRemoteServiceParams)
	err := c.cc.Invoke(ctx, "/tast.cros.arc.SuspendRemoteService/Prepare", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *suspendRemoteServiceClient) GetClockValues(ctx context.Context, in *SuspendRemoteServiceParams, opts ...grpc.CallOption) (*GetClockValuesResponse, error) {
	out := new(GetClockValuesResponse)
	err := c.cc.Invoke(ctx, "/tast.cros.arc.SuspendRemoteService/GetClockValues", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SuspendRemoteServiceServer is the server API for SuspendRemoteService service.
type SuspendRemoteServiceServer interface {
	// Prepare to prepare the device for reading clocks and suspend
	Prepare(context.Context, *empty.Empty) (*SuspendRemoteServiceParams, error)
	// GetPerfValues signs in to DUT and measures Android boot performance metrics.
	GetClockValues(context.Context, *SuspendRemoteServiceParams) (*GetClockValuesResponse, error)
}

// UnimplementedSuspendRemoteServiceServer can be embedded to have forward compatible implementations.
type UnimplementedSuspendRemoteServiceServer struct {
}

func (*UnimplementedSuspendRemoteServiceServer) Prepare(ctx context.Context, req *empty.Empty) (*SuspendRemoteServiceParams, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Prepare not implemented")
}
func (*UnimplementedSuspendRemoteServiceServer) GetClockValues(ctx context.Context, req *SuspendRemoteServiceParams) (*GetClockValuesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetClockValues not implemented")
}

func RegisterSuspendRemoteServiceServer(s *grpc.Server, srv SuspendRemoteServiceServer) {
	s.RegisterService(&_SuspendRemoteService_serviceDesc, srv)
}

func _SuspendRemoteService_Prepare_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(empty.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SuspendRemoteServiceServer).Prepare(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/tast.cros.arc.SuspendRemoteService/Prepare",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SuspendRemoteServiceServer).Prepare(ctx, req.(*empty.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _SuspendRemoteService_GetClockValues_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SuspendRemoteServiceParams)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SuspendRemoteServiceServer).GetClockValues(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/tast.cros.arc.SuspendRemoteService/GetClockValues",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SuspendRemoteServiceServer).GetClockValues(ctx, req.(*SuspendRemoteServiceParams))
	}
	return interceptor(ctx, in, info, handler)
}

var _SuspendRemoteService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "tast.cros.arc.SuspendRemoteService",
	HandlerType: (*SuspendRemoteServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Prepare",
			Handler:    _SuspendRemoteService_Prepare_Handler,
		},
		{
			MethodName: "GetClockValues",
			Handler:    _SuspendRemoteService_GetClockValues_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "suspend_remote_service.proto",
}
