// Copyright 2022 The Chromium OS Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

// Package cryptohome operates on encrypted home directories.
package cryptohome

import (
	"bytes"
	"context"
	"fmt"
	"io/ioutil"
	"os"

	"chromiumos/tast/common/testexec"
	"chromiumos/tast/errors"
)

const (
	destinationShareFile        = "dst"
	channelPubKeyFile           = "channel_pub"
	channelPrivKeyFile          = "channel_priv"
	hsmPayloadFile              = "hsm_payload"
	recoverySecretCreatedFile   = "secr_crea"
	ephemeralPubKeyFile         = "ephemeral_pub"
	recoveryRequestFile         = "recovery_req"
	recoveryResponseFile        = "response"
	recoverySecretDecryptedFile = "secr_decr"
)

// RecoveryTestTool is a command line test tool for cryptohome recovery testing.
type RecoveryTestTool struct {
	tmpFolderName string
}

// NewRecoveryTestTool creates a new instance of RecoveryTestTool with generated directory. Call RemoveDir in the end of the test.
func NewRecoveryTestTool() (*RecoveryTestTool, error) {
	// Create a temp directory.
	name, err := ioutil.TempDir("", "cryptohome_test_tool_out_*")
	if err != nil {
		return nil, errors.Wrap(err, "could not create a temp directory")
	}
	return &RecoveryTestTool{
		tmpFolderName: name,
	}, nil
}

// call calls the test tool with provided parameters.
func (c *RecoveryTestTool) call(ctx context.Context, args ...string) error {
	stdout, stderr, err := testexec.CommandContext(ctx, "cryptohome-test-tool", args...).SeparatedOutput()
	if err != nil {
		return errors.Wrapf(err, "the command failed with stdout %q and stderr %q", stdout, stderr)
	}
	return nil
}

// getFullFileName returns the full file name inside the generated directory.
func (c *RecoveryTestTool) getFullFileName(file string) string {
	return c.tmpFolderName + "/" + file
}

// getFileParam returns a parameter to cryptohome-test-tool in the format of "--param=getFullFileName(file)"
func (c *RecoveryTestTool) getFileParam(param, file string) string {
	return fmt.Sprintf("--%s=%s", param, c.getFullFileName(file))
}

// RemoveDir removes the folder generated by NewRecoveryTestTool.
func (c *RecoveryTestTool) RemoveDir() error {
	if c.tmpFolderName == "" {
		return errors.New("There is no folder set")
	}
	return os.RemoveAll(c.tmpFolderName)
}

// CreateHsmPayload calls "--action=recovery_crypto_create_hsm_payload" step.
func (c *RecoveryTestTool) CreateHsmPayload(ctx context.Context) error {
	return c.call(ctx,
		"--action=recovery_crypto_create_hsm_payload",
		c.getFileParam("destination_share_out_file", destinationShareFile),
		c.getFileParam("channel_pub_key_out_file", channelPubKeyFile),
		c.getFileParam("channel_priv_key_out_file", channelPrivKeyFile),
		c.getFileParam("serialized_hsm_payload_out_file", hsmPayloadFile),
		c.getFileParam("recovery_secret_out_file", recoverySecretCreatedFile),
	)
}

// CreateRecoveryRequest calls "--action=recovery_crypto_create_recovery_request" step.
func (c *RecoveryTestTool) CreateRecoveryRequest(ctx context.Context) error {
	return c.call(ctx,
		"--action=recovery_crypto_create_recovery_request",
		c.getFileParam("channel_pub_key_in_file", channelPubKeyFile),
		c.getFileParam("channel_priv_key_in_file", channelPrivKeyFile),
		c.getFileParam("serialized_hsm_payload_in_file", hsmPayloadFile),
		c.getFileParam("ephemeral_pub_key_out_file", ephemeralPubKeyFile),
		c.getFileParam("recovery_request_out_file", recoveryRequestFile),
	)
}

// FakeMediate calls "--action=recovery_crypto_mediate" step.
func (c *RecoveryTestTool) FakeMediate(ctx context.Context) error {
	return c.call(ctx,
		"--action=recovery_crypto_mediate",
		c.getFileParam("recovery_request_in_file", recoveryRequestFile),
		c.getFileParam("recovery_response_out_file", recoveryResponseFile),
	)
}

// Decrypt calls "--action=recovery_crypto_decrypt" step.
func (c *RecoveryTestTool) Decrypt(ctx context.Context) error {
	return c.call(ctx,
		"--action=recovery_crypto_decrypt",
		c.getFileParam("recovery_response_in_file", recoveryResponseFile),
		c.getFileParam("channel_priv_key_in_file", channelPrivKeyFile),
		c.getFileParam("ephemeral_pub_key_in_file", ephemeralPubKeyFile),
		c.getFileParam("destination_share_in_file", destinationShareFile),
		c.getFileParam("recovery_secret_out_file", recoverySecretDecryptedFile),
	)
}

// Validate compares secret created by CreateHsmPayload with secret derived by Decrypt. They are expected to be the same.
func (c *RecoveryTestTool) Validate(ctx context.Context) error {
	var recoverySecretCreatedData, recoverySecretDecrypedData []byte
	var err error
	if recoverySecretCreatedData, err = ioutil.ReadFile(c.getFullFileName(recoverySecretCreatedFile)); err != nil {
		return errors.Wrapf(err, "could not read the created recovery secret file (%s)", recoverySecretCreatedFile)
	}
	if recoverySecretDecrypedData, err = ioutil.ReadFile(c.getFullFileName(recoverySecretDecryptedFile)); err != nil {
		return errors.Wrapf(err, "could not read the decrypted recovery secret file (%s)", recoverySecretDecryptedFile)
	}
	if bytes.Compare(recoverySecretCreatedData, recoverySecretDecrypedData) != 0 {
		return errors.Errorf("Created %v, decrypted %v", string(recoverySecretCreatedData), string(recoverySecretDecrypedData))
	}
	return nil
}
