// Code generated by protoc-gen-go. DO NOT EDIT.
// source: crash_service.proto

/*
Package crash is a generated protocol buffer package.

It is generated from these files:
	crash_service.proto

It has these top-level messages:
*/
package crash

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import google_protobuf "github.com/golang/protobuf/ptypes/empty"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for CrashService service

type CrashServiceClient interface {
	// SetUp sets up the DUT for a crash test.
	// *NOTE*: If the DUT reboots during the test, it will clear
	// crash_test_in_progress state.
	// After the test is complete, you must call TearDown to clean up the
	// associated resources.
	SetUp(ctx context.Context, in *google_protobuf.Empty, opts ...grpc.CallOption) (*google_protobuf.Empty, error)
	// Close releases the resources obtained by New.
	TearDown(ctx context.Context, in *google_protobuf.Empty, opts ...grpc.CallOption) (*google_protobuf.Empty, error)
}

type crashServiceClient struct {
	cc *grpc.ClientConn
}

func NewCrashServiceClient(cc *grpc.ClientConn) CrashServiceClient {
	return &crashServiceClient{cc}
}

func (c *crashServiceClient) SetUp(ctx context.Context, in *google_protobuf.Empty, opts ...grpc.CallOption) (*google_protobuf.Empty, error) {
	out := new(google_protobuf.Empty)
	err := grpc.Invoke(ctx, "/tast.cros.crash.CrashService/SetUp", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *crashServiceClient) TearDown(ctx context.Context, in *google_protobuf.Empty, opts ...grpc.CallOption) (*google_protobuf.Empty, error) {
	out := new(google_protobuf.Empty)
	err := grpc.Invoke(ctx, "/tast.cros.crash.CrashService/TearDown", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for CrashService service

type CrashServiceServer interface {
	// SetUp sets up the DUT for a crash test.
	// *NOTE*: If the DUT reboots during the test, it will clear
	// crash_test_in_progress state.
	// After the test is complete, you must call TearDown to clean up the
	// associated resources.
	SetUp(context.Context, *google_protobuf.Empty) (*google_protobuf.Empty, error)
	// Close releases the resources obtained by New.
	TearDown(context.Context, *google_protobuf.Empty) (*google_protobuf.Empty, error)
}

func RegisterCrashServiceServer(s *grpc.Server, srv CrashServiceServer) {
	s.RegisterService(&_CrashService_serviceDesc, srv)
}

func _CrashService_SetUp_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(google_protobuf.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CrashServiceServer).SetUp(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/tast.cros.crash.CrashService/SetUp",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CrashServiceServer).SetUp(ctx, req.(*google_protobuf.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _CrashService_TearDown_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(google_protobuf.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CrashServiceServer).TearDown(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/tast.cros.crash.CrashService/TearDown",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CrashServiceServer).TearDown(ctx, req.(*google_protobuf.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

var _CrashService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "tast.cros.crash.CrashService",
	HandlerType: (*CrashServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SetUp",
			Handler:    _CrashService_SetUp_Handler,
		},
		{
			MethodName: "TearDown",
			Handler:    _CrashService_TearDown_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "crash_service.proto",
}

func init() { proto.RegisterFile("crash_service.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 165 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x4e, 0x2e, 0x4a, 0x2c,
	0xce, 0x88, 0x2f, 0x4e, 0x2d, 0x2a, 0xcb, 0x4c, 0x4e, 0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17,
	0xe2, 0x2f, 0x49, 0x2c, 0x2e, 0xd1, 0x4b, 0x2e, 0xca, 0x2f, 0xd6, 0x03, 0x4b, 0x4b, 0x49, 0xa7,
	0xe7, 0xe7, 0xa7, 0xe7, 0xa4, 0xea, 0x83, 0xa5, 0x93, 0x4a, 0xd3, 0xf4, 0x53, 0x73, 0x0b, 0x4a,
	0x2a, 0x21, 0xaa, 0x8d, 0xda, 0x19, 0xb9, 0x78, 0x9c, 0x41, 0xca, 0x82, 0x21, 0x86, 0x08, 0x59,
	0x72, 0xb1, 0x06, 0xa7, 0x96, 0x84, 0x16, 0x08, 0x89, 0xe9, 0x41, 0xf4, 0xe9, 0xc1, 0xf4, 0xe9,
	0xb9, 0x82, 0xf4, 0x49, 0xe1, 0x10, 0x57, 0x62, 0x10, 0xb2, 0xe1, 0xe2, 0x08, 0x49, 0x4d, 0x2c,
	0x72, 0xc9, 0x2f, 0xcf, 0x23, 0x5d, 0xb7, 0x93, 0x6a, 0x94, 0x72, 0x72, 0x46, 0x51, 0x7e, 0x6e,
	0x66, 0x69, 0x6e, 0x7e, 0xb1, 0x3e, 0xc8, 0x13, 0xfa, 0x50, 0x8f, 0x15, 0xeb, 0x83, 0x7c, 0xa3,
	0x0f, 0xf6, 0x4d, 0x12, 0x1b, 0x58, 0xa3, 0x31, 0x20, 0x00, 0x00, 0xff, 0xff, 0x71, 0x83, 0x7f,
	0xbb, 0xfc, 0x00, 0x00, 0x00,
}
