// Code generated by protoc-gen-go. DO NOT EDIT.
// source: wifi.proto

package network

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	empty "github.com/golang/protobuf/ptypes/empty"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Config struct {
	Ssid                 string   `protobuf:"bytes,1,opt,name=ssid,proto3" json:"ssid,omitempty"`
	Hidden               bool     `protobuf:"varint,2,opt,name=hidden,proto3" json:"hidden,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Config) Reset()         { *m = Config{} }
func (m *Config) String() string { return proto.CompactTextString(m) }
func (*Config) ProtoMessage()    {}
func (*Config) Descriptor() ([]byte, []int) {
	return fileDescriptor_14343df069b9efbf, []int{0}
}

func (m *Config) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Config.Unmarshal(m, b)
}
func (m *Config) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Config.Marshal(b, m, deterministic)
}
func (m *Config) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Config.Merge(m, src)
}
func (m *Config) XXX_Size() int {
	return xxx_messageInfo_Config.Size(m)
}
func (m *Config) XXX_DiscardUnknown() {
	xxx_messageInfo_Config.DiscardUnknown(m)
}

var xxx_messageInfo_Config proto.InternalMessageInfo

func (m *Config) GetSsid() string {
	if m != nil {
		return m.Ssid
	}
	return ""
}

func (m *Config) GetHidden() bool {
	if m != nil {
		return m.Hidden
	}
	return false
}

type Service struct {
	Path                 string   `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Service) Reset()         { *m = Service{} }
func (m *Service) String() string { return proto.CompactTextString(m) }
func (*Service) ProtoMessage()    {}
func (*Service) Descriptor() ([]byte, []int) {
	return fileDescriptor_14343df069b9efbf, []int{1}
}

func (m *Service) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Service.Unmarshal(m, b)
}
func (m *Service) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Service.Marshal(b, m, deterministic)
}
func (m *Service) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Service.Merge(m, src)
}
func (m *Service) XXX_Size() int {
	return xxx_messageInfo_Service.Size(m)
}
func (m *Service) XXX_DiscardUnknown() {
	xxx_messageInfo_Service.DiscardUnknown(m)
}

var xxx_messageInfo_Service proto.InternalMessageInfo

func (m *Service) GetPath() string {
	if m != nil {
		return m.Path
	}
	return ""
}

type SSID struct {
	Ssid                 string   `protobuf:"bytes,1,opt,name=ssid,proto3" json:"ssid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SSID) Reset()         { *m = SSID{} }
func (m *SSID) String() string { return proto.CompactTextString(m) }
func (*SSID) ProtoMessage()    {}
func (*SSID) Descriptor() ([]byte, []int) {
	return fileDescriptor_14343df069b9efbf, []int{2}
}

func (m *SSID) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SSID.Unmarshal(m, b)
}
func (m *SSID) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SSID.Marshal(b, m, deterministic)
}
func (m *SSID) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SSID.Merge(m, src)
}
func (m *SSID) XXX_Size() int {
	return xxx_messageInfo_SSID.Size(m)
}
func (m *SSID) XXX_DiscardUnknown() {
	xxx_messageInfo_SSID.DiscardUnknown(m)
}

var xxx_messageInfo_SSID proto.InternalMessageInfo

func (m *SSID) GetSsid() string {
	if m != nil {
		return m.Ssid
	}
	return ""
}

type ServiceInfo struct {
	Hidden               bool     `protobuf:"varint,1,opt,name=hidden,proto3" json:"hidden,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ServiceInfo) Reset()         { *m = ServiceInfo{} }
func (m *ServiceInfo) String() string { return proto.CompactTextString(m) }
func (*ServiceInfo) ProtoMessage()    {}
func (*ServiceInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_14343df069b9efbf, []int{3}
}

func (m *ServiceInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ServiceInfo.Unmarshal(m, b)
}
func (m *ServiceInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ServiceInfo.Marshal(b, m, deterministic)
}
func (m *ServiceInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ServiceInfo.Merge(m, src)
}
func (m *ServiceInfo) XXX_Size() int {
	return xxx_messageInfo_ServiceInfo.Size(m)
}
func (m *ServiceInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_ServiceInfo.DiscardUnknown(m)
}

var xxx_messageInfo_ServiceInfo proto.InternalMessageInfo

func (m *ServiceInfo) GetHidden() bool {
	if m != nil {
		return m.Hidden
	}
	return false
}

func init() {
	proto.RegisterType((*Config)(nil), "tast.cros.network.Config")
	proto.RegisterType((*Service)(nil), "tast.cros.network.Service")
	proto.RegisterType((*SSID)(nil), "tast.cros.network.SSID")
	proto.RegisterType((*ServiceInfo)(nil), "tast.cros.network.ServiceInfo")
}

func init() { proto.RegisterFile("wifi.proto", fileDescriptor_14343df069b9efbf) }

var fileDescriptor_14343df069b9efbf = []byte{
	// 301 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x50, 0x5f, 0x4b, 0x02, 0x41,
	0x10, 0xf7, 0x44, 0xb4, 0xa6, 0x5e, 0x5a, 0xc2, 0xec, 0xa2, 0x90, 0x05, 0xc9, 0xa7, 0x5d, 0xa8,
	0x3e, 0x81, 0x9e, 0xc1, 0x41, 0x2f, 0x79, 0x0f, 0x41, 0x6f, 0x7a, 0xce, 0xe9, 0x92, 0xee, 0xc8,
	0xee, 0x9a, 0xf8, 0x89, 0xfa, 0x9a, 0xb1, 0x77, 0x27, 0x08, 0x5d, 0xf7, 0x36, 0xc3, 0xfc, 0xfe,
	0xcd, 0x0f, 0x60, 0xaf, 0x32, 0x25, 0xb6, 0x86, 0x1c, 0xb1, 0x2b, 0x37, 0xb3, 0x4e, 0xa4, 0x86,
	0xac, 0xd0, 0xe8, 0xf6, 0x64, 0xbe, 0xc2, 0xbb, 0x25, 0xd1, 0x72, 0x8d, 0x32, 0x07, 0xcc, 0x77,
	0x99, 0xc4, 0xcd, 0xd6, 0x1d, 0x0a, 0x3c, 0x7f, 0x81, 0xf6, 0x98, 0x74, 0xa6, 0x96, 0x8c, 0x41,
	0xcb, 0x5a, 0xb5, 0xe8, 0x05, 0xfd, 0x60, 0x78, 0x3e, 0xcd, 0x67, 0xd6, 0x85, 0xf6, 0x4a, 0x2d,
	0x16, 0xa8, 0x7b, 0xcd, 0x7e, 0x30, 0x3c, 0x9b, 0x96, 0x1b, 0xbf, 0x87, 0x4e, 0x82, 0xe6, 0x5b,
	0xa5, 0xe8, 0x69, 0xdb, 0x99, 0x5b, 0x1d, 0x69, 0x7e, 0xe6, 0x21, 0xb4, 0x92, 0x24, 0x8e, 0xaa,
	0x24, 0xf9, 0x00, 0x2e, 0x4a, 0x6a, 0xac, 0x33, 0x3a, 0x71, 0x08, 0x4e, 0x1d, 0x9e, 0x7e, 0x9a,
	0xd0, 0xfa, 0x50, 0x99, 0x62, 0x23, 0xe8, 0x8c, 0x49, 0x6b, 0x4c, 0x1d, 0xbb, 0x15, 0x7f, 0x9e,
	0x13, 0x45, 0xf8, 0x30, 0xac, 0x38, 0x95, 0x36, 0xbc, 0xc1, 0x46, 0x00, 0x91, 0xb2, 0x69, 0x29,
	0x53, 0x83, 0x0d, 0xbb, 0xa2, 0x28, 0x4b, 0x1c, 0xcb, 0x12, 0x13, 0x5f, 0x16, 0x6f, 0xb0, 0x18,
	0xae, 0x23, 0x5c, 0xa3, 0xc3, 0x89, 0x76, 0x46, 0xa1, 0x7d, 0x25, 0x93, 0xff, 0x78, 0x53, 0xa5,
	0x96, 0xc4, 0x51, 0x8d, 0xd4, 0x1b, 0x5c, 0xbe, 0xef, 0xd0, 0x1c, 0x8e, 0x15, 0xd6, 0x05, 0x7a,
	0xf8, 0xff, 0xe6, 0xfb, 0xe3, 0x8d, 0xd1, 0xe3, 0xe7, 0x20, 0x5d, 0x19, 0xda, 0xa8, 0xdd, 0x86,
	0xac, 0xf4, 0x68, 0x69, 0x0b, 0x80, 0x95, 0x9e, 0x26, 0x4b, 0xda, 0xbc, 0x9d, 0x07, 0x79, 0xfe,
	0x0d, 0x00, 0x00, 0xff, 0xff, 0xf3, 0x28, 0x3e, 0xf0, 0x2f, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// WifiClient is the client API for Wifi service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type WifiClient interface {
	// Connect attempts to connect WiFi network.
	Connect(ctx context.Context, in *Config, opts ...grpc.CallOption) (*Service, error)
	// Disconnect attempts to disconnect from a service.
	Disconnect(ctx context.Context, in *Service, opts ...grpc.CallOption) (*empty.Empty, error)
	// DeleteEntriesForSSID deletes all WiFi profile entries for a given ssid.
	DeleteEntriesForSSID(ctx context.Context, in *SSID, opts ...grpc.CallOption) (*empty.Empty, error)
	// QueryService queries shill service information.
	QueryService(ctx context.Context, in *Service, opts ...grpc.CallOption) (*ServiceInfo, error)
}

type wifiClient struct {
	cc *grpc.ClientConn
}

func NewWifiClient(cc *grpc.ClientConn) WifiClient {
	return &wifiClient{cc}
}

func (c *wifiClient) Connect(ctx context.Context, in *Config, opts ...grpc.CallOption) (*Service, error) {
	out := new(Service)
	err := c.cc.Invoke(ctx, "/tast.cros.network.Wifi/Connect", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *wifiClient) Disconnect(ctx context.Context, in *Service, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/tast.cros.network.Wifi/Disconnect", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *wifiClient) DeleteEntriesForSSID(ctx context.Context, in *SSID, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/tast.cros.network.Wifi/DeleteEntriesForSSID", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *wifiClient) QueryService(ctx context.Context, in *Service, opts ...grpc.CallOption) (*ServiceInfo, error) {
	out := new(ServiceInfo)
	err := c.cc.Invoke(ctx, "/tast.cros.network.Wifi/QueryService", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// WifiServer is the server API for Wifi service.
type WifiServer interface {
	// Connect attempts to connect WiFi network.
	Connect(context.Context, *Config) (*Service, error)
	// Disconnect attempts to disconnect from a service.
	Disconnect(context.Context, *Service) (*empty.Empty, error)
	// DeleteEntriesForSSID deletes all WiFi profile entries for a given ssid.
	DeleteEntriesForSSID(context.Context, *SSID) (*empty.Empty, error)
	// QueryService queries shill service information.
	QueryService(context.Context, *Service) (*ServiceInfo, error)
}

// UnimplementedWifiServer can be embedded to have forward compatible implementations.
type UnimplementedWifiServer struct {
}

func (*UnimplementedWifiServer) Connect(ctx context.Context, req *Config) (*Service, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Connect not implemented")
}
func (*UnimplementedWifiServer) Disconnect(ctx context.Context, req *Service) (*empty.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Disconnect not implemented")
}
func (*UnimplementedWifiServer) DeleteEntriesForSSID(ctx context.Context, req *SSID) (*empty.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteEntriesForSSID not implemented")
}
func (*UnimplementedWifiServer) QueryService(ctx context.Context, req *Service) (*ServiceInfo, error) {
	return nil, status.Errorf(codes.Unimplemented, "method QueryService not implemented")
}

func RegisterWifiServer(s *grpc.Server, srv WifiServer) {
	s.RegisterService(&_Wifi_serviceDesc, srv)
}

func _Wifi_Connect_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Config)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WifiServer).Connect(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/tast.cros.network.Wifi/Connect",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WifiServer).Connect(ctx, req.(*Config))
	}
	return interceptor(ctx, in, info, handler)
}

func _Wifi_Disconnect_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Service)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WifiServer).Disconnect(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/tast.cros.network.Wifi/Disconnect",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WifiServer).Disconnect(ctx, req.(*Service))
	}
	return interceptor(ctx, in, info, handler)
}

func _Wifi_DeleteEntriesForSSID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SSID)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WifiServer).DeleteEntriesForSSID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/tast.cros.network.Wifi/DeleteEntriesForSSID",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WifiServer).DeleteEntriesForSSID(ctx, req.(*SSID))
	}
	return interceptor(ctx, in, info, handler)
}

func _Wifi_QueryService_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Service)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WifiServer).QueryService(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/tast.cros.network.Wifi/QueryService",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WifiServer).QueryService(ctx, req.(*Service))
	}
	return interceptor(ctx, in, info, handler)
}

var _Wifi_serviceDesc = grpc.ServiceDesc{
	ServiceName: "tast.cros.network.Wifi",
	HandlerType: (*WifiServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Connect",
			Handler:    _Wifi_Connect_Handler,
		},
		{
			MethodName: "Disconnect",
			Handler:    _Wifi_Disconnect_Handler,
		},
		{
			MethodName: "DeleteEntriesForSSID",
			Handler:    _Wifi_DeleteEntriesForSSID_Handler,
		},
		{
			MethodName: "QueryService",
			Handler:    _Wifi_QueryService_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "wifi.proto",
}
