// Code generated by protoc-gen-go. DO NOT EDIT.
// source: wifi.proto

package network

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	empty "github.com/golang/protobuf/ptypes/empty"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Config struct {
	Ssid                 string   `protobuf:"bytes,1,opt,name=ssid,proto3" json:"ssid,omitempty"`
	Hidden               bool     `protobuf:"varint,2,opt,name=hidden,proto3" json:"hidden,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Config) Reset()         { *m = Config{} }
func (m *Config) String() string { return proto.CompactTextString(m) }
func (*Config) ProtoMessage()    {}
func (*Config) Descriptor() ([]byte, []int) {
	return fileDescriptor_14343df069b9efbf, []int{0}
}

func (m *Config) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Config.Unmarshal(m, b)
}
func (m *Config) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Config.Marshal(b, m, deterministic)
}
func (m *Config) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Config.Merge(m, src)
}
func (m *Config) XXX_Size() int {
	return xxx_messageInfo_Config.Size(m)
}
func (m *Config) XXX_DiscardUnknown() {
	xxx_messageInfo_Config.DiscardUnknown(m)
}

var xxx_messageInfo_Config proto.InternalMessageInfo

func (m *Config) GetSsid() string {
	if m != nil {
		return m.Ssid
	}
	return ""
}

func (m *Config) GetHidden() bool {
	if m != nil {
		return m.Hidden
	}
	return false
}

type ShillVal struct {
	// Types that are valid to be assigned to Val:
	//	*ShillVal_Str
	//	*ShillVal_Bool
	Val                  isShillVal_Val `protobuf_oneof:"val"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *ShillVal) Reset()         { *m = ShillVal{} }
func (m *ShillVal) String() string { return proto.CompactTextString(m) }
func (*ShillVal) ProtoMessage()    {}
func (*ShillVal) Descriptor() ([]byte, []int) {
	return fileDescriptor_14343df069b9efbf, []int{1}
}

func (m *ShillVal) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ShillVal.Unmarshal(m, b)
}
func (m *ShillVal) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ShillVal.Marshal(b, m, deterministic)
}
func (m *ShillVal) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ShillVal.Merge(m, src)
}
func (m *ShillVal) XXX_Size() int {
	return xxx_messageInfo_ShillVal.Size(m)
}
func (m *ShillVal) XXX_DiscardUnknown() {
	xxx_messageInfo_ShillVal.DiscardUnknown(m)
}

var xxx_messageInfo_ShillVal proto.InternalMessageInfo

type isShillVal_Val interface {
	isShillVal_Val()
}

type ShillVal_Str struct {
	Str string `protobuf:"bytes,1,opt,name=str,proto3,oneof"`
}

type ShillVal_Bool struct {
	Bool bool `protobuf:"varint,2,opt,name=bool,proto3,oneof"`
}

func (*ShillVal_Str) isShillVal_Val() {}

func (*ShillVal_Bool) isShillVal_Val() {}

func (m *ShillVal) GetVal() isShillVal_Val {
	if m != nil {
		return m.Val
	}
	return nil
}

func (m *ShillVal) GetStr() string {
	if x, ok := m.GetVal().(*ShillVal_Str); ok {
		return x.Str
	}
	return ""
}

func (m *ShillVal) GetBool() bool {
	if x, ok := m.GetVal().(*ShillVal_Bool); ok {
		return x.Bool
	}
	return false
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*ShillVal) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*ShillVal_Str)(nil),
		(*ShillVal_Bool)(nil),
	}
}

type Service struct {
	Path                 string   `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Service) Reset()         { *m = Service{} }
func (m *Service) String() string { return proto.CompactTextString(m) }
func (*Service) ProtoMessage()    {}
func (*Service) Descriptor() ([]byte, []int) {
	return fileDescriptor_14343df069b9efbf, []int{2}
}

func (m *Service) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Service.Unmarshal(m, b)
}
func (m *Service) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Service.Marshal(b, m, deterministic)
}
func (m *Service) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Service.Merge(m, src)
}
func (m *Service) XXX_Size() int {
	return xxx_messageInfo_Service.Size(m)
}
func (m *Service) XXX_DiscardUnknown() {
	xxx_messageInfo_Service.DiscardUnknown(m)
}

var xxx_messageInfo_Service proto.InternalMessageInfo

func (m *Service) GetPath() string {
	if m != nil {
		return m.Path
	}
	return ""
}

type SSID struct {
	Ssid                 string   `protobuf:"bytes,1,opt,name=ssid,proto3" json:"ssid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SSID) Reset()         { *m = SSID{} }
func (m *SSID) String() string { return proto.CompactTextString(m) }
func (*SSID) ProtoMessage()    {}
func (*SSID) Descriptor() ([]byte, []int) {
	return fileDescriptor_14343df069b9efbf, []int{3}
}

func (m *SSID) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SSID.Unmarshal(m, b)
}
func (m *SSID) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SSID.Marshal(b, m, deterministic)
}
func (m *SSID) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SSID.Merge(m, src)
}
func (m *SSID) XXX_Size() int {
	return xxx_messageInfo_SSID.Size(m)
}
func (m *SSID) XXX_DiscardUnknown() {
	xxx_messageInfo_SSID.DiscardUnknown(m)
}

var xxx_messageInfo_SSID proto.InternalMessageInfo

func (m *SSID) GetSsid() string {
	if m != nil {
		return m.Ssid
	}
	return ""
}

func init() {
	proto.RegisterType((*Config)(nil), "tast.cros.network.Config")
	proto.RegisterType((*ShillVal)(nil), "tast.cros.network.ShillVal")
	proto.RegisterType((*Service)(nil), "tast.cros.network.Service")
	proto.RegisterType((*SSID)(nil), "tast.cros.network.SSID")
}

func init() { proto.RegisterFile("wifi.proto", fileDescriptor_14343df069b9efbf) }

var fileDescriptor_14343df069b9efbf = []byte{
	// 308 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x50, 0x4f, 0x4f, 0xfa, 0x40,
	0x10, 0x6d, 0x7f, 0xf4, 0x07, 0x38, 0x37, 0x37, 0x04, 0xb1, 0xc6, 0x84, 0x34, 0x31, 0x72, 0xda,
	0x26, 0xea, 0xcd, 0x5b, 0x29, 0x06, 0xae, 0x6d, 0xa2, 0x89, 0xb7, 0x52, 0xb6, 0x74, 0xe2, 0xd2,
	0x21, 0xbb, 0x0b, 0xc4, 0x8f, 0xea, 0xb7, 0x31, 0xed, 0x96, 0x93, 0xd5, 0xdb, 0xbc, 0xcc, 0xfb,
	0x33, 0xf3, 0x00, 0x4e, 0x58, 0x20, 0xdf, 0x2b, 0x32, 0xc4, 0x2e, 0x4d, 0xa6, 0x0d, 0xcf, 0x15,
	0x69, 0x5e, 0x09, 0x73, 0x22, 0xf5, 0xe1, 0xdf, 0x6c, 0x89, 0xb6, 0x52, 0x84, 0x0d, 0x61, 0x7d,
	0x28, 0x42, 0xb1, 0xdb, 0x9b, 0x4f, 0xcb, 0x0f, 0x9e, 0xa0, 0x3f, 0xa7, 0xaa, 0xc0, 0x2d, 0x63,
	0xe0, 0x69, 0x8d, 0x9b, 0x89, 0x3b, 0x75, 0x67, 0x17, 0x49, 0x33, 0xb3, 0x31, 0xf4, 0x4b, 0xdc,
	0x6c, 0x44, 0x35, 0xf9, 0x37, 0x75, 0x67, 0xc3, 0xa4, 0x45, 0xc1, 0x33, 0x0c, 0xd3, 0x12, 0xa5,
	0x7c, 0xcd, 0x24, 0x63, 0xd0, 0xd3, 0x46, 0x59, 0xd9, 0xd2, 0x49, 0x6a, 0xc0, 0x46, 0xe0, 0xad,
	0x89, 0xa4, 0x55, 0x2d, 0x9d, 0xa4, 0x41, 0xd1, 0x7f, 0xe8, 0x1d, 0x33, 0x19, 0xdc, 0xc2, 0x20,
	0x15, 0xea, 0x88, 0xb9, 0xa8, 0x33, 0xf7, 0x99, 0x29, 0xcf, 0x99, 0xf5, 0x1c, 0xf8, 0xe0, 0xa5,
	0xe9, 0x2a, 0xee, 0xba, 0xe7, 0xe1, 0xcb, 0x05, 0xef, 0x0d, 0x0b, 0x64, 0x11, 0x0c, 0xe6, 0x54,
	0x55, 0x22, 0x37, 0xec, 0x9a, 0xff, 0x78, 0x99, 0xdb, 0x97, 0x7c, 0xbf, 0x63, 0xd5, 0x46, 0x07,
	0x0e, 0x8b, 0x00, 0x62, 0xd4, 0x79, 0x6b, 0xf3, 0x07, 0xd7, 0x1f, 0x73, 0x5b, 0x21, 0x3f, 0x57,
	0xc8, 0x17, 0x75, 0x85, 0x81, 0xc3, 0x56, 0x30, 0x8a, 0x85, 0x14, 0x46, 0x2c, 0x2a, 0xa3, 0x50,
	0xe8, 0x17, 0x52, 0xcd, 0xf1, 0x57, 0x5d, 0x6e, 0xe9, 0x2a, 0xfe, 0xdd, 0x2a, 0xba, 0x7f, 0xbf,
	0xcb, 0x4b, 0x45, 0x3b, 0x3c, 0xec, 0x48, 0x87, 0xb5, 0x3c, 0xd4, 0x36, 0x5f, 0x87, 0xb5, 0x4f,
	0xd8, 0xfa, 0xac, 0xfb, 0x8d, 0xf4, 0xf1, 0x3b, 0x00, 0x00, 0xff, 0xff, 0x9c, 0x91, 0x5f, 0xd3,
	0xf7, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// WifiClient is the client API for Wifi service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type WifiClient interface {
	// Connect attempts to connect WiFi network.
	Connect(ctx context.Context, in *Config, opts ...grpc.CallOption) (*Service, error)
	// Disconnect attempts to disconnect from a service.
	Disconnect(ctx context.Context, in *Service, opts ...grpc.CallOption) (*empty.Empty, error)
	// DeleteEntriesForSSID deletes all WiFi profile entries for a given ssid.
	DeleteEntriesForSSID(ctx context.Context, in *SSID, opts ...grpc.CallOption) (*empty.Empty, error)
}

type wifiClient struct {
	cc *grpc.ClientConn
}

func NewWifiClient(cc *grpc.ClientConn) WifiClient {
	return &wifiClient{cc}
}

func (c *wifiClient) Connect(ctx context.Context, in *Config, opts ...grpc.CallOption) (*Service, error) {
	out := new(Service)
	err := c.cc.Invoke(ctx, "/tast.cros.network.Wifi/Connect", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *wifiClient) Disconnect(ctx context.Context, in *Service, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/tast.cros.network.Wifi/Disconnect", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *wifiClient) DeleteEntriesForSSID(ctx context.Context, in *SSID, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/tast.cros.network.Wifi/DeleteEntriesForSSID", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// WifiServer is the server API for Wifi service.
type WifiServer interface {
	// Connect attempts to connect WiFi network.
	Connect(context.Context, *Config) (*Service, error)
	// Disconnect attempts to disconnect from a service.
	Disconnect(context.Context, *Service) (*empty.Empty, error)
	// DeleteEntriesForSSID deletes all WiFi profile entries for a given ssid.
	DeleteEntriesForSSID(context.Context, *SSID) (*empty.Empty, error)
}

// UnimplementedWifiServer can be embedded to have forward compatible implementations.
type UnimplementedWifiServer struct {
}

func (*UnimplementedWifiServer) Connect(ctx context.Context, req *Config) (*Service, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Connect not implemented")
}
func (*UnimplementedWifiServer) Disconnect(ctx context.Context, req *Service) (*empty.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Disconnect not implemented")
}
func (*UnimplementedWifiServer) DeleteEntriesForSSID(ctx context.Context, req *SSID) (*empty.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteEntriesForSSID not implemented")
}

func RegisterWifiServer(s *grpc.Server, srv WifiServer) {
	s.RegisterService(&_Wifi_serviceDesc, srv)
}

func _Wifi_Connect_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Config)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WifiServer).Connect(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/tast.cros.network.Wifi/Connect",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WifiServer).Connect(ctx, req.(*Config))
	}
	return interceptor(ctx, in, info, handler)
}

func _Wifi_Disconnect_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Service)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WifiServer).Disconnect(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/tast.cros.network.Wifi/Disconnect",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WifiServer).Disconnect(ctx, req.(*Service))
	}
	return interceptor(ctx, in, info, handler)
}

func _Wifi_DeleteEntriesForSSID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SSID)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WifiServer).DeleteEntriesForSSID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/tast.cros.network.Wifi/DeleteEntriesForSSID",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WifiServer).DeleteEntriesForSSID(ctx, req.(*SSID))
	}
	return interceptor(ctx, in, info, handler)
}

var _Wifi_serviceDesc = grpc.ServiceDesc{
	ServiceName: "tast.cros.network.Wifi",
	HandlerType: (*WifiServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Connect",
			Handler:    _Wifi_Connect_Handler,
		},
		{
			MethodName: "Disconnect",
			Handler:    _Wifi_Disconnect_Handler,
		},
		{
			MethodName: "DeleteEntriesForSSID",
			Handler:    _Wifi_DeleteEntriesForSSID_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "wifi.proto",
}
