// Copyright 2018 The Chromium OS Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

package vm

import (
	"context"
	"path/filepath"
	"time"

	"chromiumos/tast/ctxutil"
	"chromiumos/tast/local/bundles/cros/vm/subtest"
	"chromiumos/tast/local/chrome"
	"chromiumos/tast/local/crostini"
	"chromiumos/tast/local/input"
	"chromiumos/tast/testing"
)

func init() {
	testing.AddTest(&testing.Test{
		Func:         CrostiniStartEverything,
		Desc:         "Tests Termina VM startup, container startup and other Crostini functionality",
		Contacts:     []string{"jkardatzke@chromium.org", "smbarber@chromium.org", "cros-containers-dev@google.com"},
		Attr:         []string{"informational"},
		Data:         []string{"crostini_start_everything_cros-tast-tests-deb.deb"},
		Pre:          crostini.StartedByDownload(),
		Timeout:      10 * time.Minute,
		SoftwareDeps: []string{"chrome", "vm_host"},
	})
}

func CrostiniStartEverything(ctx context.Context, s *testing.State) {
	pre := s.PreValue().(crostini.PreData)
	cr := pre.Chrome
	cont := pre.Container

	s.Log("Verifying pwd command works")
	cmd := cont.Command(ctx, "pwd")
	if err := cmd.Run(); err != nil {
		cmd.DumpLog(ctx)
		s.Fatal("Failed to run pwd: ", err)
	}

	// The VM and container have started up so we can now execute all of the other
	// Crostini tests. We need to be careful about this because we are going to be
	// testing multiple things in one test. This should be done so that no tests
	// have any known dependency on prior tests. If we hit a conflict at some
	// point then we will need to add functionality to save the VM/container image
	// at this point and then stop the VM/container and restore that image so we
	// can have a clean VM/container to start from again. Failures should not be
	// fatal so that all tests can get executed.

	subtestCtx, subtestCancel := ctxutil.Shorten(ctx, 15*time.Second)
	defer subtestCancel()

	// TODO(timzheng): Pass the keyboard to all other subtests that use the keyboard.
	keyboard, err := input.Keyboard(ctx)
	if err != nil {
		s.Fatal("Failed to find keyboard device: ", err)
	}
	defer keyboard.Close()

	// Opening a new browser window seems to sometimes also launch the Chromebook
	// landing page in a new tab.  Clean it up if it exists to prepare for
	// the screenshot tests.
	// TODO(dverkamp): Investigate if we can fix this in a more reliable way (https://crbug.com/938091)
	s.Log("Trying to close Chromebook landing page tab")
	findTabCtx, cancel := context.WithTimeout(ctx, 5*time.Second)
	defer cancel()
	conn, err := cr.NewConnForTarget(findTabCtx, chrome.MatchTargetURL("https://www.google.com/chromebook/"))
	if err == nil {
		conn.CloseTarget(ctx)
		conn.Close()
	}

	// Copy a test Debian package file to the container which will be used by
	// subsequent tests.
	const debianFilename = "crostini_start_everything_cros-tast-tests-deb.deb"
	containerDebPath := filepath.Join("/home/testuser", debianFilename)
	err = cont.PushFile(subtestCtx, s.DataPath(debianFilename), containerDebPath)
	if err != nil {
		s.Fatal("Failed copying test Debian package to container: ", err)
	}

	subtest.LinuxPackageInfo(subtestCtx, s, cont, containerDebPath)
	if err := subtest.InstallPackage(subtestCtx, cont, containerDebPath); err != nil {
		s.Fatal("Failure in performing Linux package install: ", err)
	}
	// The application IDs below are generated by the code here:
	// https://cs.chromium.org/chromium/src/chrome/browser/chromeos/crostini/crostini_registry_service.cc?g=0&l=75
	// It's a modified SHA256 hash output of a concatentation of a constant,
	// the VM name, the container name and the identifier for the .desktop file
	// the app is associated with.
	subtest.UninstallApplication(subtestCtx, s, cont, cont.VM.Concierge.GetOwnerID(),
		"x11_demo", "glkpdbkfmomgogbfppaajjcgbcgaicmi")
}
