// Copyright 2021 The Chromium OS Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

package main

import (
	// Underscore-imported packages register their tests via init functions.
	_ "chromiumos/tast-tests/local/bundles/cros/a11y"
	_ "chromiumos/tast-tests/local/bundles/cros/accountmanager"
	_ "chromiumos/tast-tests/local/bundles/cros/ad"
	_ "chromiumos/tast-tests/local/bundles/cros/apps"
	_ "chromiumos/tast-tests/local/bundles/cros/appsplatform"
	_ "chromiumos/tast-tests/local/bundles/cros/arc"
	_ "chromiumos/tast-tests/local/bundles/cros/arcappcompat"
	_ "chromiumos/tast-tests/local/bundles/cros/assistant"
	_ "chromiumos/tast-tests/local/bundles/cros/audio"
	_ "chromiumos/tast-tests/local/bundles/cros/autoupdate"
	_ "chromiumos/tast-tests/local/bundles/cros/baserpc"
	_ "chromiumos/tast-tests/local/bundles/cros/benchmark"
	_ "chromiumos/tast-tests/local/bundles/cros/biod"
	_ "chromiumos/tast-tests/local/bundles/cros/bluetooth"
	_ "chromiumos/tast-tests/local/bundles/cros/calendar"
	_ "chromiumos/tast-tests/local/bundles/cros/camera"
	_ "chromiumos/tast-tests/local/bundles/cros/cellular"
	_ "chromiumos/tast-tests/local/bundles/cros/crash"
	_ "chromiumos/tast-tests/local/bundles/cros/crosh"
	_ "chromiumos/tast-tests/local/bundles/cros/crostini"
	_ "chromiumos/tast-tests/local/bundles/cros/cryptohome"
	_ "chromiumos/tast-tests/local/bundles/cros/dbus"
	_ "chromiumos/tast-tests/local/bundles/cros/debugd"
	_ "chromiumos/tast-tests/local/bundles/cros/dev"
	_ "chromiumos/tast-tests/local/bundles/cros/diagnostics"
	_ "chromiumos/tast-tests/local/bundles/cros/dlp"
	_ "chromiumos/tast-tests/local/bundles/cros/documentscanapi"
	_ "chromiumos/tast-tests/local/bundles/cros/enterprise"
	_ "chromiumos/tast-tests/local/bundles/cros/enterpriseconnectors"
	_ "chromiumos/tast-tests/local/bundles/cros/example"
	_ "chromiumos/tast-tests/local/bundles/cros/factory"
	_ "chromiumos/tast-tests/local/bundles/cros/familylink"
	_ "chromiumos/tast-tests/local/bundles/cros/feedback"
	_ "chromiumos/tast-tests/local/bundles/cros/filemanager"
	_ "chromiumos/tast-tests/local/bundles/cros/firmware"
	_ "chromiumos/tast-tests/local/bundles/cros/firmwareupdate"
	_ "chromiumos/tast-tests/local/bundles/cros/gamepad"
	_ "chromiumos/tast-tests/local/bundles/cros/graphics"
	_ "chromiumos/tast-tests/local/bundles/cros/hammerd"
	_ "chromiumos/tast-tests/local/bundles/cros/hardware"
	_ "chromiumos/tast-tests/local/bundles/cros/health"
	_ "chromiumos/tast-tests/local/bundles/cros/holdingspace"
	_ "chromiumos/tast-tests/local/bundles/cros/hps"
	_ "chromiumos/tast-tests/local/bundles/cros/hwsec"
	_ "chromiumos/tast-tests/local/bundles/cros/inputs"
	_ "chromiumos/tast-tests/local/bundles/cros/kerberos"
	_ "chromiumos/tast-tests/local/bundles/cros/kernel"
	_ "chromiumos/tast-tests/local/bundles/cros/kiosk"
	_ "chromiumos/tast-tests/local/bundles/cros/lacros"
	_ "chromiumos/tast-tests/local/bundles/cros/launcher"
	_ "chromiumos/tast-tests/local/bundles/cros/lockscreen"
	_ "chromiumos/tast-tests/local/bundles/cros/login"
	_ "chromiumos/tast-tests/local/bundles/cros/loginapi"
	_ "chromiumos/tast-tests/local/bundles/cros/loginminutemaid"
	_ "chromiumos/tast-tests/local/bundles/cros/logs"
	_ "chromiumos/tast-tests/local/bundles/cros/meta"
	_ "chromiumos/tast-tests/local/bundles/cros/mgs"
	_ "chromiumos/tast-tests/local/bundles/cros/mlservice"
	_ "chromiumos/tast-tests/local/bundles/cros/multivm"
	_ "chromiumos/tast-tests/local/bundles/cros/nacl"
	_ "chromiumos/tast-tests/local/bundles/cros/nearbyshare"
	_ "chromiumos/tast-tests/local/bundles/cros/network"
	_ "chromiumos/tast-tests/local/bundles/cros/network/shill"
	_ "chromiumos/tast-tests/local/bundles/cros/notifications"
	_ "chromiumos/tast-tests/local/bundles/cros/ocr"
	_ "chromiumos/tast-tests/local/bundles/cros/oobe"
	_ "chromiumos/tast-tests/local/bundles/cros/osinstall"
	_ "chromiumos/tast-tests/local/bundles/cros/palmrejection"
	_ "chromiumos/tast-tests/local/bundles/cros/peripherals"
	_ "chromiumos/tast-tests/local/bundles/cros/personalization"
	_ "chromiumos/tast-tests/local/bundles/cros/phonehub"
	_ "chromiumos/tast-tests/local/bundles/cros/platform"
	_ "chromiumos/tast-tests/local/bundles/cros/policy"
	_ "chromiumos/tast-tests/local/bundles/cros/power"
	_ "chromiumos/tast-tests/local/bundles/cros/printer"
	_ "chromiumos/tast-tests/local/bundles/cros/qemu"
	_ "chromiumos/tast-tests/local/bundles/cros/quickanswers"
	_ "chromiumos/tast-tests/local/bundles/cros/quicksettings"
	_ "chromiumos/tast-tests/local/bundles/cros/scanapp"
	_ "chromiumos/tast-tests/local/bundles/cros/scanner"
	_ "chromiumos/tast-tests/local/bundles/cros/sched"
	_ "chromiumos/tast-tests/local/bundles/cros/screenshot"
	_ "chromiumos/tast-tests/local/bundles/cros/security"
	_ "chromiumos/tast-tests/local/bundles/cros/session"
	_ "chromiumos/tast-tests/local/bundles/cros/settings"
	_ "chromiumos/tast-tests/local/bundles/cros/shelf"
	_ "chromiumos/tast-tests/local/bundles/cros/shimlessrma"
	_ "chromiumos/tast-tests/local/bundles/cros/smartlock"
	_ "chromiumos/tast-tests/local/bundles/cros/storage"
	_ "chromiumos/tast-tests/local/bundles/cros/system"
	_ "chromiumos/tast-tests/local/bundles/cros/tape"
	_ "chromiumos/tast-tests/local/bundles/cros/taskmanager"
	_ "chromiumos/tast-tests/local/bundles/cros/telemetryextension"
	_ "chromiumos/tast-tests/local/bundles/cros/terminal"
	_ "chromiumos/tast-tests/local/bundles/cros/typec"
	_ "chromiumos/tast-tests/local/bundles/cros/u2fd"
	_ "chromiumos/tast-tests/local/bundles/cros/ui"
	_ "chromiumos/tast-tests/local/bundles/cros/uidetection"
	_ "chromiumos/tast-tests/local/bundles/cros/vdi"
	_ "chromiumos/tast-tests/local/bundles/cros/video"
	_ "chromiumos/tast-tests/local/bundles/cros/vm"
	_ "chromiumos/tast-tests/local/bundles/cros/wallpaper"
	_ "chromiumos/tast-tests/local/bundles/cros/webrtc"
	_ "chromiumos/tast-tests/local/bundles/cros/wifi"
	_ "chromiumos/tast-tests/local/bundles/cros/wilco"
	_ "chromiumos/tast-tests/local/bundles/cros/wmp"

	// import fixtures for arc game performance testing.
	// imports kioskLoggedIn fixtures. It is not referenced by tests as it
	// returns FixtData type from policyutil/fixtures.
	_ "chromiumos/tast-tests/local/kioskmode/fixtures"
	_ "chromiumos/tast-tests/local/meta" // import fixture for meta tests
)
