// Code generated by protoc-gen-go. DO NOT EDIT.
// source: policy.proto

package policy

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	empty "github.com/golang/protobuf/ptypes/empty"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type EnrollUsingChromeRequest struct {
	PolicyJson           []byte       `protobuf:"bytes,1,opt,name=policy_json,json=policyJson,proto3" json:"policy_json,omitempty"`
	Username             string       `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	Extensions           []*Extension `protobuf:"bytes,3,rep,name=extensions,proto3" json:"extensions,omitempty"`
	ExtraArgs            string       `protobuf:"bytes,4,opt,name=extra_args,json=extraArgs,proto3" json:"extra_args,omitempty"`
	FakedmsDir           string       `protobuf:"bytes,5,opt,name=fakedms_dir,json=fakedmsDir,proto3" json:"fakedms_dir,omitempty"`
	SkipLogin            bool         `protobuf:"varint,6,opt,name=skip_login,json=skipLogin,proto3" json:"skip_login,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *EnrollUsingChromeRequest) Reset()         { *m = EnrollUsingChromeRequest{} }
func (m *EnrollUsingChromeRequest) String() string { return proto.CompactTextString(m) }
func (*EnrollUsingChromeRequest) ProtoMessage()    {}
func (*EnrollUsingChromeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ac3b897852294d6a, []int{0}
}

func (m *EnrollUsingChromeRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EnrollUsingChromeRequest.Unmarshal(m, b)
}
func (m *EnrollUsingChromeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EnrollUsingChromeRequest.Marshal(b, m, deterministic)
}
func (m *EnrollUsingChromeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EnrollUsingChromeRequest.Merge(m, src)
}
func (m *EnrollUsingChromeRequest) XXX_Size() int {
	return xxx_messageInfo_EnrollUsingChromeRequest.Size(m)
}
func (m *EnrollUsingChromeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_EnrollUsingChromeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_EnrollUsingChromeRequest proto.InternalMessageInfo

func (m *EnrollUsingChromeRequest) GetPolicyJson() []byte {
	if m != nil {
		return m.PolicyJson
	}
	return nil
}

func (m *EnrollUsingChromeRequest) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *EnrollUsingChromeRequest) GetExtensions() []*Extension {
	if m != nil {
		return m.Extensions
	}
	return nil
}

func (m *EnrollUsingChromeRequest) GetExtraArgs() string {
	if m != nil {
		return m.ExtraArgs
	}
	return ""
}

func (m *EnrollUsingChromeRequest) GetFakedmsDir() string {
	if m != nil {
		return m.FakedmsDir
	}
	return ""
}

func (m *EnrollUsingChromeRequest) GetSkipLogin() bool {
	if m != nil {
		return m.SkipLogin
	}
	return false
}

type CreateFakeDMSDirRequest struct {
	Path                 string   `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateFakeDMSDirRequest) Reset()         { *m = CreateFakeDMSDirRequest{} }
func (m *CreateFakeDMSDirRequest) String() string { return proto.CompactTextString(m) }
func (*CreateFakeDMSDirRequest) ProtoMessage()    {}
func (*CreateFakeDMSDirRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ac3b897852294d6a, []int{1}
}

func (m *CreateFakeDMSDirRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateFakeDMSDirRequest.Unmarshal(m, b)
}
func (m *CreateFakeDMSDirRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateFakeDMSDirRequest.Marshal(b, m, deterministic)
}
func (m *CreateFakeDMSDirRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateFakeDMSDirRequest.Merge(m, src)
}
func (m *CreateFakeDMSDirRequest) XXX_Size() int {
	return xxx_messageInfo_CreateFakeDMSDirRequest.Size(m)
}
func (m *CreateFakeDMSDirRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateFakeDMSDirRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateFakeDMSDirRequest proto.InternalMessageInfo

func (m *CreateFakeDMSDirRequest) GetPath() string {
	if m != nil {
		return m.Path
	}
	return ""
}

type RemoveFakeDMSDirRequest struct {
	Path                 string   `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RemoveFakeDMSDirRequest) Reset()         { *m = RemoveFakeDMSDirRequest{} }
func (m *RemoveFakeDMSDirRequest) String() string { return proto.CompactTextString(m) }
func (*RemoveFakeDMSDirRequest) ProtoMessage()    {}
func (*RemoveFakeDMSDirRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ac3b897852294d6a, []int{2}
}

func (m *RemoveFakeDMSDirRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RemoveFakeDMSDirRequest.Unmarshal(m, b)
}
func (m *RemoveFakeDMSDirRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RemoveFakeDMSDirRequest.Marshal(b, m, deterministic)
}
func (m *RemoveFakeDMSDirRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RemoveFakeDMSDirRequest.Merge(m, src)
}
func (m *RemoveFakeDMSDirRequest) XXX_Size() int {
	return xxx_messageInfo_RemoveFakeDMSDirRequest.Size(m)
}
func (m *RemoveFakeDMSDirRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RemoveFakeDMSDirRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RemoveFakeDMSDirRequest proto.InternalMessageInfo

func (m *RemoveFakeDMSDirRequest) GetPath() string {
	if m != nil {
		return m.Path
	}
	return ""
}

type UpdatePoliciesRequest struct {
	PolicyJson           []byte   `protobuf:"bytes,1,opt,name=policy_json,json=policyJson,proto3" json:"policy_json,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdatePoliciesRequest) Reset()         { *m = UpdatePoliciesRequest{} }
func (m *UpdatePoliciesRequest) String() string { return proto.CompactTextString(m) }
func (*UpdatePoliciesRequest) ProtoMessage()    {}
func (*UpdatePoliciesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ac3b897852294d6a, []int{3}
}

func (m *UpdatePoliciesRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdatePoliciesRequest.Unmarshal(m, b)
}
func (m *UpdatePoliciesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdatePoliciesRequest.Marshal(b, m, deterministic)
}
func (m *UpdatePoliciesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdatePoliciesRequest.Merge(m, src)
}
func (m *UpdatePoliciesRequest) XXX_Size() int {
	return xxx_messageInfo_UpdatePoliciesRequest.Size(m)
}
func (m *UpdatePoliciesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdatePoliciesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdatePoliciesRequest proto.InternalMessageInfo

func (m *UpdatePoliciesRequest) GetPolicyJson() []byte {
	if m != nil {
		return m.PolicyJson
	}
	return nil
}

type ServePolicyDataRequest struct {
	Contents             []byte   `protobuf:"bytes,1,opt,name=contents,proto3" json:"contents,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ServePolicyDataRequest) Reset()         { *m = ServePolicyDataRequest{} }
func (m *ServePolicyDataRequest) String() string { return proto.CompactTextString(m) }
func (*ServePolicyDataRequest) ProtoMessage()    {}
func (*ServePolicyDataRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ac3b897852294d6a, []int{4}
}

func (m *ServePolicyDataRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ServePolicyDataRequest.Unmarshal(m, b)
}
func (m *ServePolicyDataRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ServePolicyDataRequest.Marshal(b, m, deterministic)
}
func (m *ServePolicyDataRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ServePolicyDataRequest.Merge(m, src)
}
func (m *ServePolicyDataRequest) XXX_Size() int {
	return xxx_messageInfo_ServePolicyDataRequest.Size(m)
}
func (m *ServePolicyDataRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ServePolicyDataRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ServePolicyDataRequest proto.InternalMessageInfo

func (m *ServePolicyDataRequest) GetContents() []byte {
	if m != nil {
		return m.Contents
	}
	return nil
}

type ServePolicyDataResponse struct {
	Url                  string   `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	Hash                 string   `protobuf:"bytes,2,opt,name=hash,proto3" json:"hash,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ServePolicyDataResponse) Reset()         { *m = ServePolicyDataResponse{} }
func (m *ServePolicyDataResponse) String() string { return proto.CompactTextString(m) }
func (*ServePolicyDataResponse) ProtoMessage()    {}
func (*ServePolicyDataResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_ac3b897852294d6a, []int{5}
}

func (m *ServePolicyDataResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ServePolicyDataResponse.Unmarshal(m, b)
}
func (m *ServePolicyDataResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ServePolicyDataResponse.Marshal(b, m, deterministic)
}
func (m *ServePolicyDataResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ServePolicyDataResponse.Merge(m, src)
}
func (m *ServePolicyDataResponse) XXX_Size() int {
	return xxx_messageInfo_ServePolicyDataResponse.Size(m)
}
func (m *ServePolicyDataResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ServePolicyDataResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ServePolicyDataResponse proto.InternalMessageInfo

func (m *ServePolicyDataResponse) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

func (m *ServePolicyDataResponse) GetHash() string {
	if m != nil {
		return m.Hash
	}
	return ""
}

type EvalInExtensionRequest struct {
	ExtensionId          string   `protobuf:"bytes,1,opt,name=extension_id,json=extensionId,proto3" json:"extension_id,omitempty"`
	Expression           string   `protobuf:"bytes,2,opt,name=expression,proto3" json:"expression,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EvalInExtensionRequest) Reset()         { *m = EvalInExtensionRequest{} }
func (m *EvalInExtensionRequest) String() string { return proto.CompactTextString(m) }
func (*EvalInExtensionRequest) ProtoMessage()    {}
func (*EvalInExtensionRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ac3b897852294d6a, []int{6}
}

func (m *EvalInExtensionRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EvalInExtensionRequest.Unmarshal(m, b)
}
func (m *EvalInExtensionRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EvalInExtensionRequest.Marshal(b, m, deterministic)
}
func (m *EvalInExtensionRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EvalInExtensionRequest.Merge(m, src)
}
func (m *EvalInExtensionRequest) XXX_Size() int {
	return xxx_messageInfo_EvalInExtensionRequest.Size(m)
}
func (m *EvalInExtensionRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_EvalInExtensionRequest.DiscardUnknown(m)
}

var xxx_messageInfo_EvalInExtensionRequest proto.InternalMessageInfo

func (m *EvalInExtensionRequest) GetExtensionId() string {
	if m != nil {
		return m.ExtensionId
	}
	return ""
}

func (m *EvalInExtensionRequest) GetExpression() string {
	if m != nil {
		return m.Expression
	}
	return ""
}

type EvalInExtensionResponse struct {
	Result               []byte   `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EvalInExtensionResponse) Reset()         { *m = EvalInExtensionResponse{} }
func (m *EvalInExtensionResponse) String() string { return proto.CompactTextString(m) }
func (*EvalInExtensionResponse) ProtoMessage()    {}
func (*EvalInExtensionResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_ac3b897852294d6a, []int{7}
}

func (m *EvalInExtensionResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EvalInExtensionResponse.Unmarshal(m, b)
}
func (m *EvalInExtensionResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EvalInExtensionResponse.Marshal(b, m, deterministic)
}
func (m *EvalInExtensionResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EvalInExtensionResponse.Merge(m, src)
}
func (m *EvalInExtensionResponse) XXX_Size() int {
	return xxx_messageInfo_EvalInExtensionResponse.Size(m)
}
func (m *EvalInExtensionResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_EvalInExtensionResponse.DiscardUnknown(m)
}

var xxx_messageInfo_EvalInExtensionResponse proto.InternalMessageInfo

func (m *EvalInExtensionResponse) GetResult() []byte {
	if m != nil {
		return m.Result
	}
	return nil
}

type ExtensionFile struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Contents             []byte   `protobuf:"bytes,2,opt,name=contents,proto3" json:"contents,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ExtensionFile) Reset()         { *m = ExtensionFile{} }
func (m *ExtensionFile) String() string { return proto.CompactTextString(m) }
func (*ExtensionFile) ProtoMessage()    {}
func (*ExtensionFile) Descriptor() ([]byte, []int) {
	return fileDescriptor_ac3b897852294d6a, []int{8}
}

func (m *ExtensionFile) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ExtensionFile.Unmarshal(m, b)
}
func (m *ExtensionFile) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ExtensionFile.Marshal(b, m, deterministic)
}
func (m *ExtensionFile) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ExtensionFile.Merge(m, src)
}
func (m *ExtensionFile) XXX_Size() int {
	return xxx_messageInfo_ExtensionFile.Size(m)
}
func (m *ExtensionFile) XXX_DiscardUnknown() {
	xxx_messageInfo_ExtensionFile.DiscardUnknown(m)
}

var xxx_messageInfo_ExtensionFile proto.InternalMessageInfo

func (m *ExtensionFile) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ExtensionFile) GetContents() []byte {
	if m != nil {
		return m.Contents
	}
	return nil
}

type Extension struct {
	Id                   string           `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Files                []*ExtensionFile `protobuf:"bytes,2,rep,name=files,proto3" json:"files,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *Extension) Reset()         { *m = Extension{} }
func (m *Extension) String() string { return proto.CompactTextString(m) }
func (*Extension) ProtoMessage()    {}
func (*Extension) Descriptor() ([]byte, []int) {
	return fileDescriptor_ac3b897852294d6a, []int{9}
}

func (m *Extension) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Extension.Unmarshal(m, b)
}
func (m *Extension) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Extension.Marshal(b, m, deterministic)
}
func (m *Extension) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Extension.Merge(m, src)
}
func (m *Extension) XXX_Size() int {
	return xxx_messageInfo_Extension.Size(m)
}
func (m *Extension) XXX_DiscardUnknown() {
	xxx_messageInfo_Extension.DiscardUnknown(m)
}

var xxx_messageInfo_Extension proto.InternalMessageInfo

func (m *Extension) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Extension) GetFiles() []*ExtensionFile {
	if m != nil {
		return m.Files
	}
	return nil
}

type VerifyVisibleNotificationRequest struct {
	NotificationId       string   `protobuf:"bytes,1,opt,name=notification_id,json=notificationId,proto3" json:"notification_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *VerifyVisibleNotificationRequest) Reset()         { *m = VerifyVisibleNotificationRequest{} }
func (m *VerifyVisibleNotificationRequest) String() string { return proto.CompactTextString(m) }
func (*VerifyVisibleNotificationRequest) ProtoMessage()    {}
func (*VerifyVisibleNotificationRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ac3b897852294d6a, []int{10}
}

func (m *VerifyVisibleNotificationRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VerifyVisibleNotificationRequest.Unmarshal(m, b)
}
func (m *VerifyVisibleNotificationRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VerifyVisibleNotificationRequest.Marshal(b, m, deterministic)
}
func (m *VerifyVisibleNotificationRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VerifyVisibleNotificationRequest.Merge(m, src)
}
func (m *VerifyVisibleNotificationRequest) XXX_Size() int {
	return xxx_messageInfo_VerifyVisibleNotificationRequest.Size(m)
}
func (m *VerifyVisibleNotificationRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_VerifyVisibleNotificationRequest.DiscardUnknown(m)
}

var xxx_messageInfo_VerifyVisibleNotificationRequest proto.InternalMessageInfo

func (m *VerifyVisibleNotificationRequest) GetNotificationId() string {
	if m != nil {
		return m.NotificationId
	}
	return ""
}

type EvalExpressionInChromeUrlRequest struct {
	Url                  string   `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	Expression           string   `protobuf:"bytes,2,opt,name=expression,proto3" json:"expression,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EvalExpressionInChromeUrlRequest) Reset()         { *m = EvalExpressionInChromeUrlRequest{} }
func (m *EvalExpressionInChromeUrlRequest) String() string { return proto.CompactTextString(m) }
func (*EvalExpressionInChromeUrlRequest) ProtoMessage()    {}
func (*EvalExpressionInChromeUrlRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ac3b897852294d6a, []int{11}
}

func (m *EvalExpressionInChromeUrlRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EvalExpressionInChromeUrlRequest.Unmarshal(m, b)
}
func (m *EvalExpressionInChromeUrlRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EvalExpressionInChromeUrlRequest.Marshal(b, m, deterministic)
}
func (m *EvalExpressionInChromeUrlRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EvalExpressionInChromeUrlRequest.Merge(m, src)
}
func (m *EvalExpressionInChromeUrlRequest) XXX_Size() int {
	return xxx_messageInfo_EvalExpressionInChromeUrlRequest.Size(m)
}
func (m *EvalExpressionInChromeUrlRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_EvalExpressionInChromeUrlRequest.DiscardUnknown(m)
}

var xxx_messageInfo_EvalExpressionInChromeUrlRequest proto.InternalMessageInfo

func (m *EvalExpressionInChromeUrlRequest) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

func (m *EvalExpressionInChromeUrlRequest) GetExpression() string {
	if m != nil {
		return m.Expression
	}
	return ""
}

type StartChromeRequest struct {
	PolicyJson           []byte   `protobuf:"bytes,1,opt,name=policy_json,json=policyJson,proto3" json:"policy_json,omitempty"`
	Username             string   `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	SkipLogin            bool     `protobuf:"varint,3,opt,name=skip_login,json=skipLogin,proto3" json:"skip_login,omitempty"`
	KeepEnrollment       bool     `protobuf:"varint,4,opt,name=keep_enrollment,json=keepEnrollment,proto3" json:"keep_enrollment,omitempty"`
	DeferLogin           bool     `protobuf:"varint,5,opt,name=defer_login,json=deferLogin,proto3" json:"defer_login,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StartChromeRequest) Reset()         { *m = StartChromeRequest{} }
func (m *StartChromeRequest) String() string { return proto.CompactTextString(m) }
func (*StartChromeRequest) ProtoMessage()    {}
func (*StartChromeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ac3b897852294d6a, []int{12}
}

func (m *StartChromeRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StartChromeRequest.Unmarshal(m, b)
}
func (m *StartChromeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StartChromeRequest.Marshal(b, m, deterministic)
}
func (m *StartChromeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StartChromeRequest.Merge(m, src)
}
func (m *StartChromeRequest) XXX_Size() int {
	return xxx_messageInfo_StartChromeRequest.Size(m)
}
func (m *StartChromeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_StartChromeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_StartChromeRequest proto.InternalMessageInfo

func (m *StartChromeRequest) GetPolicyJson() []byte {
	if m != nil {
		return m.PolicyJson
	}
	return nil
}

func (m *StartChromeRequest) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *StartChromeRequest) GetSkipLogin() bool {
	if m != nil {
		return m.SkipLogin
	}
	return false
}

func (m *StartChromeRequest) GetKeepEnrollment() bool {
	if m != nil {
		return m.KeepEnrollment
	}
	return false
}

func (m *StartChromeRequest) GetDeferLogin() bool {
	if m != nil {
		return m.DeferLogin
	}
	return false
}

func init() {
	proto.RegisterType((*EnrollUsingChromeRequest)(nil), "tast.cros.policy.EnrollUsingChromeRequest")
	proto.RegisterType((*CreateFakeDMSDirRequest)(nil), "tast.cros.policy.CreateFakeDMSDirRequest")
	proto.RegisterType((*RemoveFakeDMSDirRequest)(nil), "tast.cros.policy.RemoveFakeDMSDirRequest")
	proto.RegisterType((*UpdatePoliciesRequest)(nil), "tast.cros.policy.UpdatePoliciesRequest")
	proto.RegisterType((*ServePolicyDataRequest)(nil), "tast.cros.policy.ServePolicyDataRequest")
	proto.RegisterType((*ServePolicyDataResponse)(nil), "tast.cros.policy.ServePolicyDataResponse")
	proto.RegisterType((*EvalInExtensionRequest)(nil), "tast.cros.policy.EvalInExtensionRequest")
	proto.RegisterType((*EvalInExtensionResponse)(nil), "tast.cros.policy.EvalInExtensionResponse")
	proto.RegisterType((*ExtensionFile)(nil), "tast.cros.policy.ExtensionFile")
	proto.RegisterType((*Extension)(nil), "tast.cros.policy.Extension")
	proto.RegisterType((*VerifyVisibleNotificationRequest)(nil), "tast.cros.policy.VerifyVisibleNotificationRequest")
	proto.RegisterType((*EvalExpressionInChromeUrlRequest)(nil), "tast.cros.policy.EvalExpressionInChromeUrlRequest")
	proto.RegisterType((*StartChromeRequest)(nil), "tast.cros.policy.StartChromeRequest")
}

func init() { proto.RegisterFile("policy.proto", fileDescriptor_ac3b897852294d6a) }

var fileDescriptor_ac3b897852294d6a = []byte{
	// 848 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x94, 0x6d, 0x6f, 0xe3, 0x44,
	0x10, 0xc7, 0x2f, 0xed, 0xb5, 0x6a, 0xa6, 0x0f, 0x57, 0x56, 0x5c, 0xe2, 0xcb, 0x09, 0x2e, 0x58,
	0x27, 0x2e, 0x45, 0xc2, 0x11, 0x05, 0x24, 0x24, 0x24, 0x4e, 0x25, 0xc9, 0x89, 0xdc, 0x03, 0x42,
	0x0e, 0x3d, 0x04, 0x48, 0x44, 0xdb, 0x78, 0x92, 0x2c, 0x71, 0x76, 0xcd, 0xee, 0xa6, 0xa2, 0x5f,
	0x8d, 0xaf, 0xc5, 0x4b, 0xde, 0xa0, 0x5d, 0x3b, 0xae, 0x2f, 0x76, 0xdc, 0x5c, 0xd5, 0x77, 0xde,
	0xf1, 0xcc, 0x7f, 0x67, 0x66, 0x67, 0x7e, 0x70, 0x10, 0x89, 0x90, 0x8d, 0xae, 0xbc, 0x48, 0x0a,
	0x2d, 0xc8, 0xb1, 0xa6, 0x4a, 0x7b, 0x23, 0x29, 0x94, 0x17, 0xdb, 0x1b, 0x8f, 0x27, 0x42, 0x4c,
	0x42, 0x6c, 0xdb, 0xff, 0x17, 0x8b, 0x71, 0x1b, 0xe7, 0x91, 0x4e, 0xdc, 0xdd, 0x7f, 0x2b, 0xe0,
	0xf4, 0xb8, 0x14, 0x61, 0x78, 0xae, 0x18, 0x9f, 0x74, 0xa6, 0x52, 0xcc, 0xd1, 0xc7, 0xbf, 0x16,
	0xa8, 0x34, 0x79, 0x02, 0xfb, 0xb1, 0xc6, 0xf0, 0x4f, 0x25, 0xb8, 0x53, 0x69, 0x56, 0x5a, 0x07,
	0x3e, 0xc4, 0xa6, 0x97, 0x4a, 0x70, 0xd2, 0x80, 0xbd, 0x85, 0x42, 0xc9, 0xe9, 0x1c, 0x9d, 0xad,
	0x66, 0xa5, 0x55, 0xf5, 0xd3, 0x33, 0xf9, 0x16, 0x00, 0xff, 0xd6, 0xc8, 0x15, 0x13, 0x5c, 0x39,
	0xdb, 0xcd, 0xed, 0xd6, 0xfe, 0xe9, 0x63, 0x6f, 0x35, 0x3b, 0xaf, 0xb7, 0xf4, 0xf1, 0x33, 0xee,
	0xe4, 0x23, 0x1b, 0x2c, 0xe9, 0x90, 0xca, 0x89, 0x72, 0xee, 0x5b, 0xe9, 0xaa, 0xb5, 0x9c, 0xc9,
	0x89, 0x32, 0x89, 0x8d, 0xe9, 0x0c, 0x83, 0xb9, 0x1a, 0x06, 0x4c, 0x3a, 0x3b, 0xf6, 0x3f, 0x24,
	0xa6, 0x2e, 0x93, 0x26, 0x5e, 0xcd, 0x58, 0x34, 0x0c, 0xc5, 0x84, 0x71, 0x67, 0xb7, 0x59, 0x69,
	0xed, 0xf9, 0x55, 0x63, 0x79, 0x6d, 0x0c, 0xee, 0xe7, 0x50, 0xef, 0x48, 0xa4, 0x1a, 0x5f, 0xd0,
	0x19, 0x76, 0xdf, 0x0c, 0xba, 0x4c, 0x2e, 0x6b, 0x26, 0x70, 0x3f, 0xa2, 0x7a, 0x6a, 0x8b, 0xad,
	0xfa, 0xf6, 0xdb, 0xb8, 0xfb, 0x38, 0x17, 0x97, 0x1b, 0xba, 0x7f, 0x03, 0x0f, 0xcf, 0xa3, 0x80,
	0x6a, 0xfc, 0xc9, 0x94, 0xc8, 0x50, 0x6d, 0xda, 0x4f, 0xf7, 0x2b, 0xa8, 0x0d, 0x50, 0x5e, 0xc6,
	0x81, 0x57, 0x5d, 0xaa, 0xe9, 0x32, 0xb4, 0x01, 0x7b, 0x23, 0xc1, 0x35, 0x72, 0xad, 0x92, 0xb8,
	0xf4, 0xec, 0x3e, 0x87, 0x7a, 0x2e, 0x4a, 0x45, 0x82, 0x2b, 0x24, 0xc7, 0xb0, 0xbd, 0x90, 0x61,
	0x92, 0x9d, 0xf9, 0x34, 0x09, 0x4f, 0xa9, 0x9a, 0x26, 0xcf, 0x65, 0xbf, 0xdd, 0xdf, 0xa1, 0xd6,
	0xbb, 0xa4, 0x61, 0x9f, 0x5f, 0x3f, 0x46, 0x72, 0xed, 0x27, 0x70, 0x90, 0xbe, 0xca, 0x90, 0x05,
	0x89, 0xd0, 0x7e, 0x6a, 0xeb, 0x07, 0xe4, 0x63, 0xf3, 0x54, 0x91, 0x44, 0x65, 0xce, 0x89, 0x6c,
	0xc6, 0xe2, 0x7e, 0x01, 0xf5, 0x9c, 0x78, 0x92, 0x5d, 0x0d, 0x76, 0x25, 0xaa, 0x45, 0xa8, 0x93,
	0x92, 0x92, 0x93, 0xfb, 0x1c, 0x0e, 0x53, 0xe7, 0x17, 0x2c, 0x44, 0x93, 0xb4, 0x9d, 0xb1, 0xa4,
	0xcb, 0x76, 0xbe, 0xb2, 0x1d, 0xd9, 0x5a, 0xe9, 0x88, 0x0f, 0xd5, 0x54, 0x80, 0x1c, 0xc1, 0x56,
	0x9a, 0xf9, 0x16, 0x0b, 0xc8, 0xd7, 0xb0, 0x33, 0x66, 0x21, 0x9a, 0x28, 0x33, 0x93, 0x4f, 0x4a,
	0x66, 0xd2, 0x5c, 0xee, 0xc7, 0xde, 0xee, 0x2b, 0x68, 0xbe, 0x45, 0xc9, 0xc6, 0x57, 0x6f, 0x99,
	0x62, 0x17, 0x21, 0xfe, 0x28, 0x34, 0x1b, 0xb3, 0x11, 0xd5, 0x99, 0x76, 0x3d, 0x83, 0x07, 0x3c,
	0x63, 0xbe, 0xee, 0xd8, 0x51, 0xd6, 0xdc, 0x0f, 0xdc, 0x9f, 0xa1, 0x69, 0x9a, 0xd2, 0x4b, 0xdb,
	0xd4, 0xe7, 0xf1, 0xea, 0x9d, 0xcb, 0x70, 0x29, 0x96, 0x7f, 0xbb, 0x9b, 0x5a, 0xfd, 0x4f, 0x05,
	0xc8, 0x40, 0x53, 0xa9, 0xef, 0x70, 0x8d, 0xdf, 0xdd, 0xa4, 0xed, 0x95, 0x4d, 0x32, 0x15, 0xcf,
	0x10, 0xa3, 0x21, 0x5a, 0x86, 0xcc, 0x91, 0x6b, 0xbb, 0xad, 0x7b, 0xfe, 0x91, 0x31, 0xf7, 0x52,
	0xab, 0x49, 0x22, 0xc0, 0x31, 0xca, 0x44, 0x68, 0xc7, 0x3a, 0x81, 0x35, 0x59, 0xa5, 0xd3, 0xff,
	0x00, 0x0e, 0xe3, 0x09, 0x36, 0xc3, 0xcc, 0x46, 0x48, 0x7e, 0x85, 0x0f, 0x72, 0x68, 0x22, 0x9f,
	0x15, 0x3c, 0xd7, 0x1a, 0x7e, 0x35, 0x6a, 0x5e, 0x8c, 0x3e, 0x6f, 0x89, 0x3e, 0xaf, 0x67, 0xd0,
	0xe7, 0xde, 0x23, 0x03, 0x38, 0x7a, 0x77, 0x45, 0xc9, 0xb3, 0xbc, 0x6e, 0xe1, 0x12, 0x97, 0x88,
	0xf6, 0xe1, 0x61, 0x67, 0x8a, 0xa3, 0x59, 0x9c, 0xc4, 0x19, 0x0f, 0x12, 0x5c, 0x90, 0x35, 0x21,
	0x25, 0x52, 0x3f, 0xc0, 0x87, 0x03, 0x2d, 0xa2, 0x3b, 0x50, 0xfa, 0x05, 0x8e, 0x57, 0x51, 0x47,
	0x4e, 0xf2, 0xb5, 0xae, 0xc1, 0x61, 0xb9, 0xf0, 0x2a, 0x14, 0x8b, 0x84, 0xd7, 0x80, 0xb3, 0x44,
	0xf8, 0x15, 0xd4, 0xed, 0x10, 0x9b, 0x2d, 0x94, 0x9c, 0x86, 0x06, 0x68, 0x96, 0x6f, 0xf2, 0x16,
	0xe5, 0x4f, 0xe1, 0xc1, 0x0a, 0x1b, 0x49, 0x2b, 0x9f, 0x64, 0x31, 0x74, 0x1b, 0x27, 0x1b, 0x78,
	0xc6, 0x28, 0x73, 0xef, 0x91, 0x97, 0x50, 0x33, 0x4f, 0x76, 0x27, 0x59, 0xff, 0x01, 0x8e, 0xc1,
	0xc3, 0x40, 0x53, 0x8d, 0x66, 0x7b, 0x32, 0xf0, 0x2c, 0x4a, 0xbf, 0x18, 0xde, 0xe5, 0x5d, 0x59,
	0x89, 0x79, 0x0f, 0xd9, 0x93, 0x0d, 0x3c, 0xd3, 0xae, 0x30, 0x78, 0xb4, 0x96, 0x9a, 0xe4, 0x34,
	0xaf, 0x74, 0x13, 0x62, 0x4b, 0x8a, 0x62, 0xf0, 0x68, 0x0d, 0x53, 0xfd, 0xd7, 0x45, 0x57, 0xdd,
	0x04, 0xe0, 0x92, 0xab, 0xde, 0xc0, 0x7e, 0x86, 0xb3, 0xe4, 0x69, 0xc1, 0x9c, 0xe4, 0x30, 0x5c,
	0x22, 0xf7, 0x1d, 0xc0, 0xf5, 0xb6, 0xdf, 0x62, 0x5c, 0xce, 0xe0, 0xb0, 0x23, 0xb8, 0x66, 0x7c,
	0x81, 0x31, 0x95, 0xdf, 0x5b, 0xe2, 0xfb, 0x4f, 0x7f, 0x7b, 0x3a, 0x32, 0xd7, 0xb3, 0xc5, 0x5c,
	0xa8, 0xb6, 0x29, 0xa7, 0xad, 0x62, 0x0c, 0xab, 0xb6, 0xa9, 0xab, 0x1d, 0xd7, 0x75, 0xb1, 0x6b,
	0x23, 0xbf, 0xfc, 0x3f, 0x00, 0x00, 0xff, 0xff, 0xe1, 0x80, 0xc1, 0x35, 0x75, 0x0a, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// PolicyServiceClient is the client API for PolicyService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type PolicyServiceClient interface {
	EnrollUsingChrome(ctx context.Context, in *EnrollUsingChromeRequest, opts ...grpc.CallOption) (*empty.Empty, error)
	UpdatePolicies(ctx context.Context, in *UpdatePoliciesRequest, opts ...grpc.CallOption) (*empty.Empty, error)
	CheckChromeAndFakeDMS(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*empty.Empty, error)
	StopChromeAndFakeDMS(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*empty.Empty, error)
	CreateFakeDMSDir(ctx context.Context, in *CreateFakeDMSDirRequest, opts ...grpc.CallOption) (*empty.Empty, error)
	RemoveFakeDMSDir(ctx context.Context, in *RemoveFakeDMSDirRequest, opts ...grpc.CallOption) (*empty.Empty, error)
	StartExternalDataServer(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*empty.Empty, error)
	ServePolicyData(ctx context.Context, in *ServePolicyDataRequest, opts ...grpc.CallOption) (*ServePolicyDataResponse, error)
	StopExternalDataServer(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*empty.Empty, error)
	EvalStatementInExtension(ctx context.Context, in *EvalInExtensionRequest, opts ...grpc.CallOption) (*empty.Empty, error)
	EvalInExtension(ctx context.Context, in *EvalInExtensionRequest, opts ...grpc.CallOption) (*EvalInExtensionResponse, error)
	// Verifies that the notification corresponding to the id in the request is visible.
	VerifyVisibleNotification(ctx context.Context, in *VerifyVisibleNotificationRequest, opts ...grpc.CallOption) (*empty.Empty, error)
	// Creates a new connection to the Chrome URL in the request and evaluates the expression in the request on it.
	EvalExpressionInChromeURL(ctx context.Context, in *EvalExpressionInChromeUrlRequest, opts ...grpc.CallOption) (*empty.Empty, error)
	StartChrome(ctx context.Context, in *StartChromeRequest, opts ...grpc.CallOption) (*empty.Empty, error)
	StopChrome(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*empty.Empty, error)
	ContinueLogin(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*empty.Empty, error)
}

type policyServiceClient struct {
	cc *grpc.ClientConn
}

func NewPolicyServiceClient(cc *grpc.ClientConn) PolicyServiceClient {
	return &policyServiceClient{cc}
}

func (c *policyServiceClient) EnrollUsingChrome(ctx context.Context, in *EnrollUsingChromeRequest, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/tast.cros.policy.PolicyService/EnrollUsingChrome", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *policyServiceClient) UpdatePolicies(ctx context.Context, in *UpdatePoliciesRequest, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/tast.cros.policy.PolicyService/UpdatePolicies", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *policyServiceClient) CheckChromeAndFakeDMS(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/tast.cros.policy.PolicyService/CheckChromeAndFakeDMS", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *policyServiceClient) StopChromeAndFakeDMS(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/tast.cros.policy.PolicyService/StopChromeAndFakeDMS", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *policyServiceClient) CreateFakeDMSDir(ctx context.Context, in *CreateFakeDMSDirRequest, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/tast.cros.policy.PolicyService/CreateFakeDMSDir", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *policyServiceClient) RemoveFakeDMSDir(ctx context.Context, in *RemoveFakeDMSDirRequest, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/tast.cros.policy.PolicyService/RemoveFakeDMSDir", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *policyServiceClient) StartExternalDataServer(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/tast.cros.policy.PolicyService/StartExternalDataServer", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *policyServiceClient) ServePolicyData(ctx context.Context, in *ServePolicyDataRequest, opts ...grpc.CallOption) (*ServePolicyDataResponse, error) {
	out := new(ServePolicyDataResponse)
	err := c.cc.Invoke(ctx, "/tast.cros.policy.PolicyService/ServePolicyData", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *policyServiceClient) StopExternalDataServer(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/tast.cros.policy.PolicyService/StopExternalDataServer", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *policyServiceClient) EvalStatementInExtension(ctx context.Context, in *EvalInExtensionRequest, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/tast.cros.policy.PolicyService/EvalStatementInExtension", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *policyServiceClient) EvalInExtension(ctx context.Context, in *EvalInExtensionRequest, opts ...grpc.CallOption) (*EvalInExtensionResponse, error) {
	out := new(EvalInExtensionResponse)
	err := c.cc.Invoke(ctx, "/tast.cros.policy.PolicyService/EvalInExtension", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *policyServiceClient) VerifyVisibleNotification(ctx context.Context, in *VerifyVisibleNotificationRequest, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/tast.cros.policy.PolicyService/VerifyVisibleNotification", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *policyServiceClient) EvalExpressionInChromeURL(ctx context.Context, in *EvalExpressionInChromeUrlRequest, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/tast.cros.policy.PolicyService/EvalExpressionInChromeURL", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *policyServiceClient) StartChrome(ctx context.Context, in *StartChromeRequest, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/tast.cros.policy.PolicyService/StartChrome", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *policyServiceClient) StopChrome(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/tast.cros.policy.PolicyService/StopChrome", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *policyServiceClient) ContinueLogin(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/tast.cros.policy.PolicyService/ContinueLogin", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PolicyServiceServer is the server API for PolicyService service.
type PolicyServiceServer interface {
	EnrollUsingChrome(context.Context, *EnrollUsingChromeRequest) (*empty.Empty, error)
	UpdatePolicies(context.Context, *UpdatePoliciesRequest) (*empty.Empty, error)
	CheckChromeAndFakeDMS(context.Context, *empty.Empty) (*empty.Empty, error)
	StopChromeAndFakeDMS(context.Context, *empty.Empty) (*empty.Empty, error)
	CreateFakeDMSDir(context.Context, *CreateFakeDMSDirRequest) (*empty.Empty, error)
	RemoveFakeDMSDir(context.Context, *RemoveFakeDMSDirRequest) (*empty.Empty, error)
	StartExternalDataServer(context.Context, *empty.Empty) (*empty.Empty, error)
	ServePolicyData(context.Context, *ServePolicyDataRequest) (*ServePolicyDataResponse, error)
	StopExternalDataServer(context.Context, *empty.Empty) (*empty.Empty, error)
	EvalStatementInExtension(context.Context, *EvalInExtensionRequest) (*empty.Empty, error)
	EvalInExtension(context.Context, *EvalInExtensionRequest) (*EvalInExtensionResponse, error)
	// Verifies that the notification corresponding to the id in the request is visible.
	VerifyVisibleNotification(context.Context, *VerifyVisibleNotificationRequest) (*empty.Empty, error)
	// Creates a new connection to the Chrome URL in the request and evaluates the expression in the request on it.
	EvalExpressionInChromeURL(context.Context, *EvalExpressionInChromeUrlRequest) (*empty.Empty, error)
	StartChrome(context.Context, *StartChromeRequest) (*empty.Empty, error)
	StopChrome(context.Context, *empty.Empty) (*empty.Empty, error)
	ContinueLogin(context.Context, *empty.Empty) (*empty.Empty, error)
}

// UnimplementedPolicyServiceServer can be embedded to have forward compatible implementations.
type UnimplementedPolicyServiceServer struct {
}

func (*UnimplementedPolicyServiceServer) EnrollUsingChrome(ctx context.Context, req *EnrollUsingChromeRequest) (*empty.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method EnrollUsingChrome not implemented")
}
func (*UnimplementedPolicyServiceServer) UpdatePolicies(ctx context.Context, req *UpdatePoliciesRequest) (*empty.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdatePolicies not implemented")
}
func (*UnimplementedPolicyServiceServer) CheckChromeAndFakeDMS(ctx context.Context, req *empty.Empty) (*empty.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CheckChromeAndFakeDMS not implemented")
}
func (*UnimplementedPolicyServiceServer) StopChromeAndFakeDMS(ctx context.Context, req *empty.Empty) (*empty.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StopChromeAndFakeDMS not implemented")
}
func (*UnimplementedPolicyServiceServer) CreateFakeDMSDir(ctx context.Context, req *CreateFakeDMSDirRequest) (*empty.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateFakeDMSDir not implemented")
}
func (*UnimplementedPolicyServiceServer) RemoveFakeDMSDir(ctx context.Context, req *RemoveFakeDMSDirRequest) (*empty.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RemoveFakeDMSDir not implemented")
}
func (*UnimplementedPolicyServiceServer) StartExternalDataServer(ctx context.Context, req *empty.Empty) (*empty.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StartExternalDataServer not implemented")
}
func (*UnimplementedPolicyServiceServer) ServePolicyData(ctx context.Context, req *ServePolicyDataRequest) (*ServePolicyDataResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ServePolicyData not implemented")
}
func (*UnimplementedPolicyServiceServer) StopExternalDataServer(ctx context.Context, req *empty.Empty) (*empty.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StopExternalDataServer not implemented")
}
func (*UnimplementedPolicyServiceServer) EvalStatementInExtension(ctx context.Context, req *EvalInExtensionRequest) (*empty.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method EvalStatementInExtension not implemented")
}
func (*UnimplementedPolicyServiceServer) EvalInExtension(ctx context.Context, req *EvalInExtensionRequest) (*EvalInExtensionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method EvalInExtension not implemented")
}
func (*UnimplementedPolicyServiceServer) VerifyVisibleNotification(ctx context.Context, req *VerifyVisibleNotificationRequest) (*empty.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method VerifyVisibleNotification not implemented")
}
func (*UnimplementedPolicyServiceServer) EvalExpressionInChromeURL(ctx context.Context, req *EvalExpressionInChromeUrlRequest) (*empty.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method EvalExpressionInChromeURL not implemented")
}
func (*UnimplementedPolicyServiceServer) StartChrome(ctx context.Context, req *StartChromeRequest) (*empty.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StartChrome not implemented")
}
func (*UnimplementedPolicyServiceServer) StopChrome(ctx context.Context, req *empty.Empty) (*empty.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StopChrome not implemented")
}
func (*UnimplementedPolicyServiceServer) ContinueLogin(ctx context.Context, req *empty.Empty) (*empty.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ContinueLogin not implemented")
}

func RegisterPolicyServiceServer(s *grpc.Server, srv PolicyServiceServer) {
	s.RegisterService(&_PolicyService_serviceDesc, srv)
}

func _PolicyService_EnrollUsingChrome_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EnrollUsingChromeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PolicyServiceServer).EnrollUsingChrome(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/tast.cros.policy.PolicyService/EnrollUsingChrome",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PolicyServiceServer).EnrollUsingChrome(ctx, req.(*EnrollUsingChromeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PolicyService_UpdatePolicies_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdatePoliciesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PolicyServiceServer).UpdatePolicies(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/tast.cros.policy.PolicyService/UpdatePolicies",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PolicyServiceServer).UpdatePolicies(ctx, req.(*UpdatePoliciesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PolicyService_CheckChromeAndFakeDMS_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(empty.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PolicyServiceServer).CheckChromeAndFakeDMS(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/tast.cros.policy.PolicyService/CheckChromeAndFakeDMS",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PolicyServiceServer).CheckChromeAndFakeDMS(ctx, req.(*empty.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _PolicyService_StopChromeAndFakeDMS_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(empty.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PolicyServiceServer).StopChromeAndFakeDMS(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/tast.cros.policy.PolicyService/StopChromeAndFakeDMS",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PolicyServiceServer).StopChromeAndFakeDMS(ctx, req.(*empty.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _PolicyService_CreateFakeDMSDir_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateFakeDMSDirRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PolicyServiceServer).CreateFakeDMSDir(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/tast.cros.policy.PolicyService/CreateFakeDMSDir",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PolicyServiceServer).CreateFakeDMSDir(ctx, req.(*CreateFakeDMSDirRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PolicyService_RemoveFakeDMSDir_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveFakeDMSDirRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PolicyServiceServer).RemoveFakeDMSDir(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/tast.cros.policy.PolicyService/RemoveFakeDMSDir",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PolicyServiceServer).RemoveFakeDMSDir(ctx, req.(*RemoveFakeDMSDirRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PolicyService_StartExternalDataServer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(empty.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PolicyServiceServer).StartExternalDataServer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/tast.cros.policy.PolicyService/StartExternalDataServer",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PolicyServiceServer).StartExternalDataServer(ctx, req.(*empty.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _PolicyService_ServePolicyData_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ServePolicyDataRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PolicyServiceServer).ServePolicyData(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/tast.cros.policy.PolicyService/ServePolicyData",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PolicyServiceServer).ServePolicyData(ctx, req.(*ServePolicyDataRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PolicyService_StopExternalDataServer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(empty.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PolicyServiceServer).StopExternalDataServer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/tast.cros.policy.PolicyService/StopExternalDataServer",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PolicyServiceServer).StopExternalDataServer(ctx, req.(*empty.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _PolicyService_EvalStatementInExtension_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EvalInExtensionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PolicyServiceServer).EvalStatementInExtension(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/tast.cros.policy.PolicyService/EvalStatementInExtension",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PolicyServiceServer).EvalStatementInExtension(ctx, req.(*EvalInExtensionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PolicyService_EvalInExtension_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EvalInExtensionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PolicyServiceServer).EvalInExtension(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/tast.cros.policy.PolicyService/EvalInExtension",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PolicyServiceServer).EvalInExtension(ctx, req.(*EvalInExtensionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PolicyService_VerifyVisibleNotification_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VerifyVisibleNotificationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PolicyServiceServer).VerifyVisibleNotification(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/tast.cros.policy.PolicyService/VerifyVisibleNotification",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PolicyServiceServer).VerifyVisibleNotification(ctx, req.(*VerifyVisibleNotificationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PolicyService_EvalExpressionInChromeURL_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EvalExpressionInChromeUrlRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PolicyServiceServer).EvalExpressionInChromeURL(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/tast.cros.policy.PolicyService/EvalExpressionInChromeURL",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PolicyServiceServer).EvalExpressionInChromeURL(ctx, req.(*EvalExpressionInChromeUrlRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PolicyService_StartChrome_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StartChromeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PolicyServiceServer).StartChrome(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/tast.cros.policy.PolicyService/StartChrome",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PolicyServiceServer).StartChrome(ctx, req.(*StartChromeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PolicyService_StopChrome_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(empty.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PolicyServiceServer).StopChrome(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/tast.cros.policy.PolicyService/StopChrome",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PolicyServiceServer).StopChrome(ctx, req.(*empty.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _PolicyService_ContinueLogin_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(empty.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PolicyServiceServer).ContinueLogin(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/tast.cros.policy.PolicyService/ContinueLogin",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PolicyServiceServer).ContinueLogin(ctx, req.(*empty.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

var _PolicyService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "tast.cros.policy.PolicyService",
	HandlerType: (*PolicyServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "EnrollUsingChrome",
			Handler:    _PolicyService_EnrollUsingChrome_Handler,
		},
		{
			MethodName: "UpdatePolicies",
			Handler:    _PolicyService_UpdatePolicies_Handler,
		},
		{
			MethodName: "CheckChromeAndFakeDMS",
			Handler:    _PolicyService_CheckChromeAndFakeDMS_Handler,
		},
		{
			MethodName: "StopChromeAndFakeDMS",
			Handler:    _PolicyService_StopChromeAndFakeDMS_Handler,
		},
		{
			MethodName: "CreateFakeDMSDir",
			Handler:    _PolicyService_CreateFakeDMSDir_Handler,
		},
		{
			MethodName: "RemoveFakeDMSDir",
			Handler:    _PolicyService_RemoveFakeDMSDir_Handler,
		},
		{
			MethodName: "StartExternalDataServer",
			Handler:    _PolicyService_StartExternalDataServer_Handler,
		},
		{
			MethodName: "ServePolicyData",
			Handler:    _PolicyService_ServePolicyData_Handler,
		},
		{
			MethodName: "StopExternalDataServer",
			Handler:    _PolicyService_StopExternalDataServer_Handler,
		},
		{
			MethodName: "EvalStatementInExtension",
			Handler:    _PolicyService_EvalStatementInExtension_Handler,
		},
		{
			MethodName: "EvalInExtension",
			Handler:    _PolicyService_EvalInExtension_Handler,
		},
		{
			MethodName: "VerifyVisibleNotification",
			Handler:    _PolicyService_VerifyVisibleNotification_Handler,
		},
		{
			MethodName: "EvalExpressionInChromeURL",
			Handler:    _PolicyService_EvalExpressionInChromeURL_Handler,
		},
		{
			MethodName: "StartChrome",
			Handler:    _PolicyService_StartChrome_Handler,
		},
		{
			MethodName: "StopChrome",
			Handler:    _PolicyService_StopChrome_Handler,
		},
		{
			MethodName: "ContinueLogin",
			Handler:    _PolicyService_ContinueLogin_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "policy.proto",
}
