// Code generated by protoc-gen-go. DO NOT EDIT.
// source: rollback_service.proto

package policy

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	empty "github.com/golang/protobuf/ptypes/empty"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type RollbackSuccessfulResponse struct {
	RollbackSuccessful   bool     `protobuf:"varint,1,opt,name=rollback_successful,json=rollbackSuccessful,proto3" json:"rollback_successful,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RollbackSuccessfulResponse) Reset()         { *m = RollbackSuccessfulResponse{} }
func (m *RollbackSuccessfulResponse) String() string { return proto.CompactTextString(m) }
func (*RollbackSuccessfulResponse) ProtoMessage()    {}
func (*RollbackSuccessfulResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_1fd790d2ad5b21d2, []int{0}
}

func (m *RollbackSuccessfulResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RollbackSuccessfulResponse.Unmarshal(m, b)
}
func (m *RollbackSuccessfulResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RollbackSuccessfulResponse.Marshal(b, m, deterministic)
}
func (m *RollbackSuccessfulResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RollbackSuccessfulResponse.Merge(m, src)
}
func (m *RollbackSuccessfulResponse) XXX_Size() int {
	return xxx_messageInfo_RollbackSuccessfulResponse.Size(m)
}
func (m *RollbackSuccessfulResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RollbackSuccessfulResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RollbackSuccessfulResponse proto.InternalMessageInfo

func (m *RollbackSuccessfulResponse) GetRollbackSuccessful() bool {
	if m != nil {
		return m.RollbackSuccessful
	}
	return false
}

func init() {
	proto.RegisterType((*RollbackSuccessfulResponse)(nil), "tast.cros.policy.RollbackSuccessfulResponse")
}

func init() { proto.RegisterFile("rollback_service.proto", fileDescriptor_1fd790d2ad5b21d2) }

var fileDescriptor_1fd790d2ad5b21d2 = []byte{
	// 207 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x90, 0x41, 0x4b, 0xc4, 0x30,
	0x10, 0x85, 0xe9, 0x45, 0x24, 0x07, 0x95, 0x08, 0x45, 0xea, 0x45, 0x44, 0xc4, 0x83, 0x4c, 0x40,
	0xff, 0x81, 0xe0, 0xd1, 0x4b, 0x85, 0x1e, 0xbc, 0x48, 0x1b, 0xa6, 0xdd, 0xb0, 0xe9, 0x4e, 0xc8,
	0x24, 0x0b, 0xfd, 0xf7, 0x4b, 0x9b, 0xb6, 0x0b, 0xbb, 0xec, 0xf9, 0xcd, 0xfb, 0xde, 0xc7, 0x88,
	0xdc, 0x93, 0xb5, 0x4d, 0xad, 0xb7, 0xff, 0x8c, 0x7e, 0x6f, 0x34, 0x82, 0xf3, 0x14, 0x48, 0xde,
	0x85, 0x9a, 0x03, 0x68, 0x4f, 0x0c, 0x8e, 0xac, 0xd1, 0x43, 0xf1, 0xd8, 0x11, 0x75, 0x16, 0xd5,
	0x94, 0x37, 0xb1, 0x55, 0xd8, 0xbb, 0x30, 0xa4, 0xf3, 0xe7, 0x1f, 0x51, 0x94, 0x33, 0xe8, 0x37,
	0x6a, 0x8d, 0xcc, 0x6d, 0xb4, 0x25, 0xb2, 0xa3, 0x1d, 0xa3, 0x54, 0xe2, 0xfe, 0x38, 0xb3, 0xc6,
	0x0f, 0xd9, 0x53, 0xf6, 0x76, 0x5d, 0x4a, 0x7f, 0x56, 0xfc, 0x30, 0xe2, 0x76, 0xc5, 0x25, 0x2d,
	0x59, 0x89, 0x9b, 0x0a, 0xbd, 0x69, 0x87, 0x25, 0x90, 0x39, 0x24, 0x23, 0x58, 0x8c, 0xe0, 0x7b,
	0x34, 0x2a, 0xde, 0xe1, 0xd4, 0x1d, 0x2e, 0xbb, 0x7d, 0xbd, 0xfe, 0xbd, 0xe8, 0x8d, 0xa7, 0xde,
	0xc4, 0x9e, 0x58, 0x8d, 0x4d, 0x35, 0x7f, 0x82, 0xd5, 0x88, 0x50, 0x09, 0xd1, 0x5c, 0x4d, 0x2b,
	0x9f, 0x87, 0x00, 0x00, 0x00, 0xff, 0xff, 0x6e, 0xcd, 0x5c, 0x9f, 0x31, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// RollbackServiceClient is the client API for RollbackService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type RollbackServiceClient interface {
	VerifyRollback(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*RollbackSuccessfulResponse, error)
}

type rollbackServiceClient struct {
	cc *grpc.ClientConn
}

func NewRollbackServiceClient(cc *grpc.ClientConn) RollbackServiceClient {
	return &rollbackServiceClient{cc}
}

func (c *rollbackServiceClient) VerifyRollback(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*RollbackSuccessfulResponse, error) {
	out := new(RollbackSuccessfulResponse)
	err := c.cc.Invoke(ctx, "/tast.cros.policy.RollbackService/VerifyRollback", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RollbackServiceServer is the server API for RollbackService service.
type RollbackServiceServer interface {
	VerifyRollback(context.Context, *empty.Empty) (*RollbackSuccessfulResponse, error)
}

// UnimplementedRollbackServiceServer can be embedded to have forward compatible implementations.
type UnimplementedRollbackServiceServer struct {
}

func (*UnimplementedRollbackServiceServer) VerifyRollback(ctx context.Context, req *empty.Empty) (*RollbackSuccessfulResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method VerifyRollback not implemented")
}

func RegisterRollbackServiceServer(s *grpc.Server, srv RollbackServiceServer) {
	s.RegisterService(&_RollbackService_serviceDesc, srv)
}

func _RollbackService_VerifyRollback_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(empty.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RollbackServiceServer).VerifyRollback(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/tast.cros.policy.RollbackService/VerifyRollback",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RollbackServiceServer).VerifyRollback(ctx, req.(*empty.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

var _RollbackService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "tast.cros.policy.RollbackService",
	HandlerType: (*RollbackServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "VerifyRollback",
			Handler:    _RollbackService_VerifyRollback_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "rollback_service.proto",
}
